enum ShopName {
    'None' = -1,
    'Pewter_City',
    'Cerulean_City',
    'Vermillion_City',
    'Celadon_City',
    'Saffron_City',
    'Fuchsia_City',
    'Cinnabar_Island',
    'Viridian_City',
    'Lavender_Town',
    'New_Bark_Town',
    'Cherrygrove_City',
    'Violet_City',
    'Azalea_Town',
    'Goldenrod_City',
    'Olivine_City',
    'Cianwood_City',
    'Blackthorn_City',
}
