///<reference path="../party/evolutions/LevelEvolution.ts"/>
///<reference path="../party/evolutions/StoneEvolution.ts"/>
///<reference path="../GameConstants.ts"/>
/**
 * Pokémon data, accessible by name or id.
 * @type {{}}
 */

const pokemonMap: { [name: string]: any } = {};
const pokemonMapId: { [id: number]: any } = {};
const pokemonDevolutionMap: { [name: string]: string } = {};

/**
 * Datalist that contains all Pokémon data
 */
const pokemonList: {
    id: number,
    name: string,
    catchRate: number,
    evolutions?: Evolution[]
    evolution?: any[],
    evoLevel?: any[],
    type: string[],
    attack: number,
    levelType: string,
    exp: number,
    eggCycles: number
}[] =
    [{
        "id": 1,
        "name": "Bulbasaur",
        "catchRate": 45,
        "type": ["Grass", "Poison"],
        "attack": 65,
        "levelType": "mediumslow",
        "exp": 64,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Bulbasaur", "Ivysaur", 16)],
    }, {
        "id": 2,
        "name": "Ivysaur",
        "catchRate": 45,
        "type": ["Grass", "Poison"],
        "attack": 80,
        "levelType": "mediumslow",
        "exp": 142,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Ivysaur", "Venusaur", 32)],
    }, {
        "id": 3,
        "name": "Venusaur",
        "catchRate": 45,
        "type": ["Grass", "Poison"],
        "attack": 100,
        "levelType": "mediumslow",
        "exp": 236,
        "eggCycles": 20
    }, {
        "id": 4,
        "name": "Charmander",
        "catchRate": 45,
        "type": ["Fire"],
        "attack": 60,
        "levelType": "mediumslow",
        "exp": 62,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Charmander", "Charmeleon", 16)],
    }, {
        "id": 5,
        "name": "Charmeleon",
        "catchRate": 45,
        "type": ["Fire"],
        "attack": 80,
        "levelType": "mediumslow",
        "exp": 142,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Charmeleon", "Charizard", 36)],
    }, {
        "id": 6,
        "name": "Charizard",
        "catchRate": 45,
        "type": ["Fire", "Flying"],
        "attack": 105,
        "levelType": "mediumslow",
        "exp": 240,
        "eggCycles": 20
    }, {
        "id": 7,
        "name": "Squirtle",
        "catchRate": 45,
        "type": ["Water"],
        "attack": 50,
        "levelType": "mediumslow",
        "exp": 63,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Squirtle", "Wartortle", 16)],
    }, {
        "id": 8,
        "name": "Wartortle",
        "catchRate": 45,
        "type": ["Water"],
        "attack": 65,
        "levelType": "mediumslow",
        "exp": 142,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Wartortle", "Blastoise", 36)],
    }, {
        "id": 9,
        "name": "Blastoise",
        "catchRate": 45,
        "type": ["Water"],
        "attack": 85,
        "levelType": "mediumslow",
        "exp": 239,
        "eggCycles": 20
    }, {
        "id": 10,
        "name": "Caterpie",
        "catchRate": 255,
        "type": ["Bug"],
        "attack": 30,
        "levelType": "mediumfast",
        "exp": 39,
        "eggCycles": 15,
        "evolutions": [new LevelEvolution("Caterpie", "Metapod", 7)],
    }, {
        "id": 11,
        "name": "Metapod",
        "catchRate": 120,
        "type": ["Bug"],
        "attack": 25,
        "levelType": "mediumfast",
        "exp": 72,
        "eggCycles": 15,
        "evolutions": [new LevelEvolution("Metapod", "Butterfree", 10)],
    }, {
        "id": 12,
        "name": "Butterfree",
        "catchRate": 45,
        "type": ["Bug", "Flying"],
        "attack": 90,
        "levelType": "mediumfast",
        "exp": 178,
        "eggCycles": 15
    }, {
        "id": 13,
        "name": "Weedle",
        "catchRate": 255,
        "type": ["Bug", "Poison"],
        "attack": 35,
        "levelType": "mediumfast",
        "exp": 39,
        "eggCycles": 15,
        "evolutions": [new LevelEvolution("Weedle", "Kakuna", 7)],
    }, {
        "id": 14,
        "name": "Kakuna",
        "catchRate": 120,
        "type": ["Bug", "Poison"],
        "attack": 25,
        "levelType": "mediumfast",
        "exp": 72,
        "eggCycles": 15,
        "evolutions": [new LevelEvolution("Kakuna", "Beedrill", 10)],
    }, {
        "id": 15,
        "name": "Beedrill",
        "catchRate": 45,
        "type": ["Bug", "Poison"],
        "attack": 90,
        "levelType": "mediumfast",
        "exp": 178,
        "eggCycles": 15
    }, {
        "id": 16,
        "name": "Pidgey",
        "catchRate": 255,
        "type": ["Normal", "Flying"],
        "attack": 45,
        "levelType": "mediumslow",
        "exp": 50,
        "eggCycles": 15,
        "evolutions": [new LevelEvolution("Pidgey", "Pidgeotto", 18)],
    }, {
        "id": 17,
        "name": "Pidgeotto",
        "catchRate": 120,
        "type": ["Normal", "Flying"],
        "attack": 60,
        "levelType": "mediumslow",
        "exp": 122,
        "eggCycles": 15,
        "evolutions": [new LevelEvolution("Pidgeotto", "Pidgeot", 36)],
    }, {
        "id": 18,
        "name": "Pidgeot",
        "catchRate": 45,
        "type": ["Normal", "Flying"],
        "attack": 80,
        "levelType": "mediumslow",
        "exp": 216,
        "eggCycles": 15
    }, {
        "id": 19,
        "name": "Rattata",
        "catchRate": 255,
        "type": ["Normal"],
        "attack": 56,
        "levelType": "mediumfast",
        "exp": 51,
        "eggCycles": 15,
        "evolutions": [new LevelEvolution("Rattata", "Raticate", 20)],
    }, {
        "id": 20,
        "name": "Raticate",
        "catchRate": 127,
        "type": ["Normal"],
        "attack": 81,
        "levelType": "mediumfast",
        "exp": 145,
        "eggCycles": 15
    }, {
        "id": 21,
        "name": "Spearow",
        "catchRate": 255,
        "type": ["Normal", "Flying"],
        "attack": 60,
        "levelType": "mediumfast",
        "exp": 52,
        "eggCycles": 15,
        "evolutions": [new LevelEvolution("Spearow", "Fearow", 20)],
    }, {
        "id": 22,
        "name": "Fearow",
        "catchRate": 90,
        "type": ["Normal", "Flying"],
        "attack": 90,
        "levelType": "mediumfast",
        "exp": 155,
        "eggCycles": 15
    }, {
        "id": 23,
        "name": "Ekans",
        "catchRate": 255,
        "type": ["Poison"],
        "attack": 60,
        "levelType": "mediumfast",
        "exp": 58,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Ekans", "Arbok", 22)],
    }, {
        "id": 24,
        "name": "Arbok",
        "catchRate": 90,
        "type": ["Poison"],
        "attack": 85,
        "levelType": "mediumfast",
        "exp": 157,
        "eggCycles": 20
    }, {
        "id": 25,
        "name": "Pikachu",
        "catchRate": 190,
        "type": ["Electric"],
        "attack": 55,
        "levelType": "mediumfast",
        "exp": 112,
        "eggCycles": 10,
        "evolutions": [new StoneEvolution("Pikachu", "Raichu", GameConstants.StoneType.Thunder_stone)],
    }, {
        "id": 26,
        "name": "Raichu",
        "catchRate": 75,
        "type": ["Electric"],
        "attack": 90,
        "levelType": "mediumfast",
        "exp": 218,
        "eggCycles": 10
    }, {
        "id": 27,
        "name": "Sandshrew",
        "catchRate": 255,
        "type": ["Ground"],
        "attack": 75,
        "levelType": "mediumfast",
        "exp": 60,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Sandshrew", "Sandslash", 22)],
    }, {
        "id": 28,
        "name": "Sandslash",
        "catchRate": 90,
        "type": ["Ground"],
        "attack": 100,
        "levelType": "mediumfast",
        "exp": 158,
        "eggCycles": 20
    }, {
        "id": 29,
        "name": "Nidoran(F)",
        "catchRate": 235,
        "type": ["Poison"],
        "attack": 47,
        "levelType": "mediumslow",
        "exp": 55,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Nidoran(F)", "Nidorina", 16)],
    }, {
        "id": 30,
        "name": "Nidorina",
        "catchRate": 120,
        "type": ["Poison"],
        "attack": 62,
        "levelType": "mediumslow",
        "exp": 128,
        "eggCycles": 20,
        "evolutions": [new StoneEvolution("Nidorina", "Nidoqueen", GameConstants.StoneType.Moon_stone)],
    }, {
        "id": 31,
        "name": "Nidoqueen",
        "catchRate": 45,
        "type": ["Poison", "Ground"],
        "attack": 92,
        "levelType": "mediumslow",
        "exp": 227,
        "eggCycles": 20
    }, {
        "id": 32,
        "name": "Nidoran(M)",
        "catchRate": 235,
        "type": ["Poison"],
        "attack": 57,
        "levelType": "mediumslow",
        "exp": 55,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Nidoran(M)", "Nidorino", 16)],
    }, {
        "id": 33,
        "name": "Nidorino",
        "catchRate": 120,
        "type": ["Poison"],
        "attack": 72,
        "levelType": "mediumslow",
        "exp": 128,
        "eggCycles": 20,
        "evolutions": [new StoneEvolution("Nidorino", "Nidoking", GameConstants.StoneType.Moon_stone)],
    }, {
        "id": 34,
        "name": "Nidoking",
        "catchRate": 45,
        "type": ["Poison", "Ground"],
        "attack": 102,
        "levelType": "mediumslow",
        "exp": 227,
        "eggCycles": 20
    }, {
        "id": 35,
        "name": "Clefairy",
        "catchRate": 150,
        "type": ["Fairy"],
        "attack": 60,
        "levelType": "fast",
        "exp": 113,
        "eggCycles": 10,
        "evolutions": [new StoneEvolution("Clefairy", "Clefable", GameConstants.StoneType.Moon_stone)],
    }, {
        "id": 36,
        "name": "Clefable",
        "catchRate": 25,
        "type": ["Fairy"],
        "attack": 95,
        "levelType": "fast",
        "exp": 217,
        "eggCycles": 10
    }, {
        "id": 37,
        "name": "Vulpix",
        "catchRate": 190,
        "type": ["Fire"],
        "attack": 50,
        "levelType": "mediumfast",
        "exp": 60,
        "eggCycles": 20,
        "evolutions": [new StoneEvolution("Vulpix", "Ninetales", GameConstants.StoneType.Fire_stone)],
    }, {
        "id": 38,
        "name": "Ninetales",
        "catchRate": 75,
        "type": ["Fire"],
        "attack": 81,
        "levelType": "mediumfast",
        "exp": 177,
        "eggCycles": 20
    }, {
        "id": 39,
        "name": "Jigglypuff",
        "catchRate": 170,
        "type": ["Normal", "Fairy"],
        "attack": 45,
        "levelType": "fast",
        "exp": 95,
        "eggCycles": 10,
        "evolutions": [new StoneEvolution("Jigglypuff", "Wigglytuff", GameConstants.StoneType.Moon_stone)],
    }, {
        "id": 40,
        "name": "Wigglytuff",
        "catchRate": 50,
        "type": ["Normal", "Fairy"],
        "attack": 85,
        "levelType": "fast",
        "exp": 196,
        "eggCycles": 10
    }, {
        "id": 41,
        "name": "Zubat",
        "catchRate": 255,
        "type": ["Poison", "Flying"],
        "attack": 45,
        "levelType": "mediumfast",
        "exp": 49,
        "eggCycles": 15,
        "evolutions": [new LevelEvolution("Zubat", "Golbat", 22)],
    }, {
        "id": 42,
        "name": "Golbat",
        "catchRate": 90,
        "type": ["Poison", "Flying"],
        "attack": 80,
        "levelType": "mediumfast",
        "exp": 159,
        "eggCycles": 15,
        "evolutions": [new LevelEvolution("Golbat", "Crobat", 100)],
    }, {
        "id": 43,
        "name": "Oddish",
        "catchRate": 255,
        "type": ["Grass", "Poison"],
        "attack": 75,
        "levelType": "mediumslow",
        "exp": 64,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Oddish", "Gloom", 21)],
    }, {
        "id": 44,
        "name": "Gloom",
        "catchRate": 120,
        "type": ["Grass", "Poison"],
        "attack": 85,
        "levelType": "mediumslow",
        "exp": 138,
        "eggCycles": 20,
        "evolutions": [
            new StoneEvolution("Gloom", "Vileplume", GameConstants.StoneType.Leaf_stone),
            new StoneEvolution("Gloom", "Bellossom", GameConstants.StoneType.Sun_stone),
        ],
    }, {
        "id": 45,
        "name": "Vileplume",
        "catchRate": 45,
        "type": ["Grass", "Poison"],
        "attack": 110,
        "levelType": "mediumslow",
        "exp": 221,
        "eggCycles": 20
    }, {
        "id": 46,
        "name": "Paras",
        "catchRate": 190,
        "type": ["Bug", "Grass"],
        "attack": 70,
        "levelType": "mediumfast",
        "exp": 57,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Paras", "Parasect", 24)],
    }, {
        "id": 47,
        "name": "Parasect",
        "catchRate": 75,
        "type": ["Bug", "Grass"],
        "attack": 95,
        "levelType": "mediumfast",
        "exp": 142,
        "eggCycles": 20
    }, {
        "id": 48,
        "name": "Venonat",
        "catchRate": 190,
        "type": ["Bug", "Poison"],
        "attack": 55,
        "levelType": "mediumfast",
        "exp": 61,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Venonat", "Venomoth", 31)],
    }, {
        "id": 49,
        "name": "Venomoth",
        "catchRate": 75,
        "type": ["Bug", "Poison"],
        "attack": 90,
        "levelType": "mediumfast",
        "exp": 158,
        "eggCycles": 20
    }, {
        "id": 50,
        "name": "Diglett",
        "catchRate": 255,
        "type": ["Ground"],
        "attack": 55,
        "levelType": "mediumfast",
        "exp": 53,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Diglett", "Dugtrio", 26)],
    }, {
        "id": 51,
        "name": "Dugtrio",
        "catchRate": 50,
        "type": ["Ground"],
        "attack": 80,
        "levelType": "mediumfast",
        "exp": 149,
        "eggCycles": 20
    }, {
        "id": 52,
        "name": "Meowth",
        "catchRate": 255,
        "type": ["Normal"],
        "attack": 45,
        "levelType": "mediumfast",
        "exp": 58,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Meowth", "Persian", 28)],
    }, {
        "id": 53,
        "name": "Persian",
        "catchRate": 90,
        "type": ["Normal"],
        "attack": 70,
        "levelType": "mediumfast",
        "exp": 154,
        "eggCycles": 20
    }, {
        "id": 54,
        "name": "Psyduck",
        "catchRate": 190,
        "type": ["Water"],
        "attack": 65,
        "levelType": "mediumfast",
        "exp": 64,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Psyduck", "Golduck", 33)],
    }, {
        "id": 55,
        "name": "Golduck",
        "catchRate": 75,
        "type": ["Water"],
        "attack": 95,
        "levelType": "mediumfast",
        "exp": 175,
        "eggCycles": 20
    }, {
        "id": 56,
        "name": "Mankey",
        "catchRate": 190,
        "type": ["Fighting"],
        "attack": 80,
        "levelType": "mediumfast",
        "exp": 61,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Mankey", "Primeape", 28)],
    }, {
        "id": 57,
        "name": "Primeape",
        "catchRate": 75,
        "type": ["Fighting"],
        "attack": 105,
        "levelType": "mediumfast",
        "exp": 159,
        "eggCycles": 20
    }, {
        "id": 58,
        "name": "Growlithe",
        "catchRate": 190,
        "type": ["Fire"],
        "attack": 70,
        "levelType": "slow",
        "exp": 70,
        "eggCycles": 20,
        "evolutions": [new StoneEvolution("Growlithe", "Arcanine", GameConstants.StoneType.Fire_stone)],
    }, {
        "id": 59,
        "name": "Arcanine",
        "catchRate": 75,
        "type": ["Fire"],
        "attack": 110,
        "levelType": "slow",
        "exp": 194,
        "eggCycles": 20
    }, {
        "id": 60,
        "name": "Poliwag",
        "catchRate": 255,
        "type": ["Water"],
        "attack": 50,
        "levelType": "mediumslow",
        "exp": 60,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Poliwag", "Poliwhirl", 25)],
    }, {
        "id": 61,
        "name": "Poliwhirl",
        "catchRate": 120,
        "type": ["Water"],
        "attack": 65,
        "levelType": "mediumslow",
        "exp": 135,
        "eggCycles": 20,
        "evolutions": [new StoneEvolution("Poliwhirl", "Poliwrath", GameConstants.StoneType.Water_stone), new StoneEvolution("Poliwhirl", "Politoed", GameConstants.StoneType.Kings_rock)],
    }, {
        "id": 62,
        "name": "Poliwrath",
        "catchRate": 45,
        "type": ["Water", "Fighting"],
        "attack": 95,
        "levelType": "mediumslow",
        "exp": 230,
        "eggCycles": 20
    }, {
        "id": 63,
        "name": "Abra",
        "catchRate": 200,
        "type": ["Psychic"],
        "attack": 105,
        "levelType": "mediumslow",
        "exp": 62,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Abra", "Kadabra", 16)],
    }, {
        "id": 64,
        "name": "Kadabra",
        "catchRate": 100,
        "type": ["Psychic"],
        "attack": 120,
        "levelType": "mediumslow",
        "exp": 140,
        "eggCycles": 20,
        "evolutions": [new StoneEvolution("Kadabra", "Alakazam", GameConstants.StoneType.Trade_stone)],
    }, {
        "id": 65,
        "name": "Alakazam",
        "catchRate": 50,
        "type": ["Psychic"],
        "attack": 135,
        "levelType": "mediumslow",
        "exp": 225,
        "eggCycles": 20
    }, {
        "id": 66,
        "name": "Machop",
        "catchRate": 180,
        "type": ["Fighting"],
        "attack": 80,
        "levelType": "mediumslow",
        "exp": 61,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Machop", "Machoke", 28)],
    }, {
        "id": 67,
        "name": "Machoke",
        "catchRate": 90,
        "type": ["Fighting"],
        "attack": 100,
        "levelType": "mediumslow",
        "exp": 142,
        "eggCycles": 20,
        "evolutions": [new StoneEvolution("Machoke", "Machamp", GameConstants.StoneType.Trade_stone)],
    }, {
        "id": 68,
        "name": "Machamp",
        "catchRate": 45,
        "type": ["Fighting"],
        "attack": 130,
        "levelType": "mediumslow",
        "exp": 227,
        "eggCycles": 20
    }, {
        "id": 69,
        "name": "Bellsprout",
        "catchRate": 255,
        "type": ["Grass", "Poison"],
        "attack": 75,
        "levelType": "mediumslow",
        "exp": 60,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Bellsprout", "Weepinbell", 21)],
    }, {
        "id": 70,
        "name": "Weepinbell",
        "catchRate": 120,
        "type": ["Grass", "Poison"],
        "attack": 90,
        "levelType": "mediumslow",
        "exp": 137,
        "eggCycles": 20,
        "evolutions": [new StoneEvolution("Weepinbell", "Victreebel", GameConstants.StoneType.Leaf_stone)],
    }, {
        "id": 71,
        "name": "Victreebel",
        "catchRate": 45,
        "type": ["Grass", "Poison"],
        "attack": 105,
        "levelType": "mediumslow",
        "exp": 221,
        "eggCycles": 20
    }, {
        "id": 72,
        "name": "Tentacool",
        "catchRate": 190,
        "type": ["Water", "Poison"],
        "attack": 50,
        "levelType": "slow",
        "exp": 67,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Tentacool", "Tentacruel", 30)],
    }, {
        "id": 73,
        "name": "Tentacruel",
        "catchRate": 60,
        "type": ["Water", "Poison"],
        "attack": 80,
        "levelType": "slow",
        "exp": 180,
        "eggCycles": 20
    }, {
        "id": 74,
        "name": "Geodude",
        "catchRate": 255,
        "type": ["Rock", "Ground"],
        "attack": 80,
        "levelType": "mediumslow",
        "exp": 60,
        "eggCycles": 15,
        "evolutions": [new LevelEvolution("Geodude", "Graveler", 25)],
    }, {
        "id": 75,
        "name": "Graveler",
        "catchRate": 120,
        "type": ["Rock", "Ground"],
        "attack": 95,
        "levelType": "mediumslow",
        "exp": 137,
        "eggCycles": 15,
        "evolutions": [new StoneEvolution("Graveler", "Golem", GameConstants.StoneType.Trade_stone)],
    }, {
        "id": 76,
        "name": "Golem",
        "catchRate": 45,
        "type": ["Rock", "Ground"],
        "attack": 120,
        "levelType": "mediumslow",
        "exp": 223,
        "eggCycles": 15
    }, {
        "id": 77,
        "name": "Ponyta",
        "catchRate": 190,
        "type": ["Fire"],
        "attack": 85,
        "levelType": "mediumfast",
        "exp": 82,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Ponyta", "Rapidash", 40)],
    }, {
        "id": 78,
        "name": "Rapidash",
        "catchRate": 60,
        "type": ["Fire"],
        "attack": 100,
        "levelType": "mediumfast",
        "exp": 175,
        "eggCycles": 20
    }, {
        "id": 79,
        "name": "Slowpoke",
        "catchRate": 190,
        "type": ["Water", "Psychic"],
        "attack": 65,
        "levelType": "mediumfast",
        "exp": 63,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Slowpoke", "Slowbro", 37), new StoneEvolution("Slowpoke", "Slowking", GameConstants.StoneType.Kings_rock)],
    }, {
        "id": 80,
        "name": "Slowbro",
        "catchRate": 75,
        "type": ["Water", "Psychic"],
        "attack": 100,
        "levelType": "mediumfast",
        "exp": 172,
        "eggCycles": 20
    }, {
        "id": 81,
        "name": "Magnemite",
        "catchRate": 190,
        "type": ["Electric", "Steel"],
        "attack": 95,
        "levelType": "mediumfast",
        "exp": 65,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Magnemite", "Magneton", 30)],
    }, {
        "id": 82,
        "name": "Magneton",
        "catchRate": 60,
        "type": ["Electric", "Steel"],
        "attack": 120,
        "levelType": "mediumfast",
        "exp": 163,
        "eggCycles": 20,
    }, {
        "id": 83,
        "name": "Farfetch'd",
        "catchRate": 45,
        "type": ["Normal", "Flying"],
        "attack": 65,
        "levelType": "mediumfast",
        "exp": 132,
        "eggCycles": 20,
    }, {
        "id": 84,
        "name": "Doduo",
        "catchRate": 190,
        "type": ["Normal", "Flying"],
        "attack": 85,
        "levelType": "mediumfast",
        "exp": 62,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Doduo", "Dodrio", 31)],
    }, {
        "id": 85,
        "name": "Dodrio",
        "catchRate": 45,
        "type": ["Normal", "Flying"],
        "attack": 110,
        "levelType": "mediumfast",
        "exp": 165,
        "eggCycles": 20
    }, {
        "id": 86,
        "name": "Seel",
        "catchRate": 190,
        "type": ["Water"],
        "attack": 45,
        "levelType": "mediumfast",
        "exp": 65,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Seel", "Dewgong", 34)],
    }, {
        "id": 87,
        "name": "Dewgong",
        "catchRate": 75,
        "type": ["Water", "Ice"],
        "attack": 70,
        "levelType": "mediumfast",
        "exp": 166,
        "eggCycles": 20
    }, {
        "id": 88,
        "name": "Grimer",
        "catchRate": 190,
        "type": ["Poison"],
        "attack": 80,
        "levelType": "mediumfast",
        "exp": 65,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Grimer", "Muk", 38)],
    }, {
        "id": 89,
        "name": "Muk",
        "catchRate": 75,
        "type": ["Poison"],
        "attack": 105,
        "levelType": "mediumfast",
        "exp": 175,
        "eggCycles": 20
    }, {
        "id": 90,
        "name": "Shellder",
        "catchRate": 190,
        "type": ["Water"],
        "attack": 65,
        "levelType": "slow",
        "exp": 61,
        "eggCycles": 20,
        "evolutions": [new StoneEvolution("Shellder", "Cloyster", GameConstants.StoneType.Water_stone)],
    }, {
        "id": 91,
        "name": "Cloyster",
        "catchRate": 60,
        "type": ["Water", "Ice"],
        "attack": 95,
        "levelType": "slow",
        "exp": 184,
        "eggCycles": 20
    }, {
        "id": 92,
        "name": "Gastly",
        "catchRate": 190,
        "type": ["Ghost", "Poison"],
        "attack": 100,
        "levelType": "mediumslow",
        "exp": 62,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Gastly", "Haunter", 25)],
    }, {
        "id": 93,
        "name": "Haunter",
        "catchRate": 90,
        "type": ["Ghost", "Poison"],
        "attack": 115,
        "levelType": "mediumslow",
        "exp": 142,
        "eggCycles": 20,
        "evolutions": [new StoneEvolution("Haunter", "Gengar", GameConstants.StoneType.Trade_stone)],
    }, {
        "id": 94,
        "name": "Gengar",
        "catchRate": 45,
        "type": ["Ghost", "Poison"],
        "attack": 130,
        "levelType": "mediumslow",
        "exp": 225,
        "eggCycles": 20
    }, {
        "id": 95,
        "name": "Onix",
        "catchRate": 45,
        "type": ["Rock", "Ground"],
        "attack": 45,
        "levelType": "mediumfast",
        "exp": 77,
        "eggCycles": 25,
        "evolutions": [new StoneEvolution("Onix", "Steelix", GameConstants.StoneType.Metal_coat)],
    }, {
        "id": 96,
        "name": "Drowzee",
        "catchRate": 190,
        "type": ["Psychic"],
        "attack": 48,
        "levelType": "mediumfast",
        "exp": 66,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Drowzee", "Hypno", 26)],
    }, {
        "id": 97,
        "name": "Hypno",
        "catchRate": 75,
        "type": ["Psychic"],
        "attack": 73,
        "levelType": "mediumfast",
        "exp": 169,
        "eggCycles": 20
    }, {
        "id": 98,
        "name": "Krabby",
        "catchRate": 225,
        "type": ["Water"],
        "attack": 105,
        "levelType": "mediumfast",
        "exp": 65,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Krabby", "Kingler", 28)],
    }, {
        "id": 99,
        "name": "Kingler",
        "catchRate": 60,
        "type": ["Water"],
        "attack": 130,
        "levelType": "mediumfast",
        "exp": 166,
        "eggCycles": 20
    }, {
        "id": 100,
        "name": "Voltorb",
        "catchRate": 190,
        "type": ["Electric"],
        "attack": 55,
        "levelType": "mediumfast",
        "exp": 66,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Voltorb", "Electrode", 30)],
    }, {
        "id": 101,
        "name": "Electrode",
        "catchRate": 60,
        "type": ["Electric"],
        "attack": 80,
        "levelType": "mediumfast",
        "exp": 172,
        "eggCycles": 20
    }, {
        "id": 102,
        "name": "Exeggcute",
        "catchRate": 90,
        "type": ["Grass", "Psychic"],
        "attack": 60,
        "levelType": "slow",
        "exp": 65,
        "eggCycles": 20,
        "evolutions": [new StoneEvolution("Exeggcute", "Exeggutor", GameConstants.StoneType.Leaf_stone)],
    }, {
        "id": 103,
        "name": "Exeggutor",
        "catchRate": 45,
        "type": ["Grass", "Psychic"],
        "attack": 125,
        "levelType": "slow",
        "exp": 186,
        "eggCycles": 20
    }, {
        "id": 104,
        "name": "Cubone",
        "catchRate": 190,
        "type": ["Ground"],
        "attack": 50,
        "levelType": "mediumfast",
        "exp": 64,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Cubone", "Marowak", 28)],
    }, {
        "id": 105,
        "name": "Marowak",
        "catchRate": 75,
        "type": ["Ground"],
        "attack": 80,
        "levelType": "mediumfast",
        "exp": 149,
        "eggCycles": 20
    }, {
        "id": 106,
        "name": "Hitmonlee",
        "catchRate": 45,
        "type": ["Fighting"],
        "attack": 120,
        "levelType": "mediumfast",
        "exp": 159,
        "eggCycles": 25
    }, {
        "id": 107,
        "name": "Hitmonchan",
        "catchRate": 45,
        "type": ["Fighting"],
        "attack": 105,
        "levelType": "mediumfast",
        "exp": 159,
        "eggCycles": 25
    }, {
        "id": 108,
        "name": "Lickitung",
        "catchRate": 45,
        "type": ["Normal"],
        "attack": 60,
        "levelType": "mediumfast",
        "exp": 77,
        "eggCycles": 20,
    }, {
        "id": 109,
        "name": "Koffing",
        "catchRate": 190,
        "type": ["Poison"],
        "attack": 65,
        "levelType": "mediumfast",
        "exp": 68,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Koffing", "Weezing", 35)],
    }, {
        "id": 110,
        "name": "Weezing",
        "catchRate": 60,
        "type": ["Poison"],
        "attack": 90,
        "levelType": "mediumfast",
        "exp": 172,
        "eggCycles": 20
    }, {
        "id": 111,
        "name": "Rhyhorn",
        "catchRate": 120,
        "type": ["Ground", "Rock"],
        "attack": 85,
        "levelType": "slow",
        "exp": 69,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Rhyhorn", "Rhydon", 42)],
    }, {
        "id": 112,
        "name": "Rhydon",
        "catchRate": 60,
        "type": ["Ground", "Rock"],
        "attack": 130,
        "levelType": "slow",
        "exp": 170,
        "eggCycles": 20,
    }, {
        "id": 113,
        "name": "Chansey",
        "catchRate": 30,
        "type": ["Normal"],
        "attack": 35,
        "levelType": "fast",
        "exp": 395,
        "eggCycles": 40,
        "evolutions": [new LevelEvolution("Chansey", "Blissey", 100)],
    }, {
        "id": 114,
        "name": "Tangela",
        "catchRate": 45,
        "type": ["Grass"],
        "attack": 100,
        "levelType": "mediumfast",
        "exp": 87,
        "eggCycles": 20,
    }, {
        "id": 115,
        "name": "Kangaskhan",
        "catchRate": 45,
        "type": ["Normal"],
        "attack": 95,
        "levelType": "mediumfast",
        "exp": 172,
        "eggCycles": 20
    }, {
        "id": 116,
        "name": "Horsea",
        "catchRate": 225,
        "type": ["Water"],
        "attack": 70,
        "levelType": "mediumfast",
        "exp": 59,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Horsea", "Seadra", 32)],
    }, {
        "id": 117,
        "name": "Seadra",
        "catchRate": 75,
        "type": ["Water"],
        "attack": 95,
        "levelType": "mediumfast",
        "exp": 154,
        "eggCycles": 20,
        "evolutions": [new StoneEvolution("Seadra", "Kingdra", GameConstants.StoneType.Dragon_scale)],
    }, {
        "id": 118,
        "name": "Goldeen",
        "catchRate": 225,
        "type": ["Water"],
        "attack": 67,
        "levelType": "mediumfast",
        "exp": 64,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Goldeen", "Seaking", 33)],
    }, {
        "id": 119,
        "name": "Seaking",
        "catchRate": 60,
        "type": ["Water"],
        "attack": 92,
        "levelType": "mediumfast",
        "exp": 158,
        "eggCycles": 20
    }, {
        "id": 120,
        "name": "Staryu",
        "catchRate": 225,
        "type": ["Water"],
        "attack": 70,
        "levelType": "slow",
        "exp": 68,
        "eggCycles": 20,
        "evolutions": [new StoneEvolution("Staryu", "Starmie", GameConstants.StoneType.Water_stone)],
    }, {
        "id": 121,
        "name": "Starmie",
        "catchRate": 60,
        "type": ["Water", "Psychic"],
        "attack": 100,
        "levelType": "slow",
        "exp": 182,
        "eggCycles": 20
    }, {
        "id": 122,
        "name": "Mr. Mime",
        "catchRate": 45,
        "type": ["Psychic", "Fairy"],
        "attack": 100,
        "levelType": "mediumfast",
        "exp": 161,
        "eggCycles": 25
    }, {
        "id": 123,
        "name": "Scyther",
        "catchRate": 45,
        "type": ["Bug", "Flying"],
        "attack": 110,
        "levelType": "mediumfast",
        "exp": 100,
        "eggCycles": 25,
        "evolutions": [new StoneEvolution("Scyther", "Scizor", GameConstants.StoneType.Metal_coat)],
    }, {
        "id": 124,
        "name": "Jynx",
        "catchRate": 45,
        "type": ["Ice", "Psychic"],
        "attack": 115,
        "levelType": "mediumfast",
        "exp": 159,
        "eggCycles": 25
    }, {
        "id": 125,
        "name": "Electabuzz",
        "catchRate": 45,
        "type": ["Electric"],
        "attack": 95,
        "levelType": "mediumfast",
        "exp": 172,
        "eggCycles": 25,
        "evolutions": [new StoneEvolution("Electabuzz", "Electivire", GameConstants.StoneType.Trade_stone)],
    }, {
        "id": 126,
        "name": "Magmar",
        "catchRate": 45,
        "type": ["Fire"],
        "attack": 100,
        "levelType": "mediumfast",
        "exp": 173,
        "eggCycles": 25,
        "evolutions": [new StoneEvolution("Magmar", "Magmortar", GameConstants.StoneType.Trade_stone)],
    }, {
        "id": 127,
        "name": "Pinsir",
        "catchRate": 45,
        "type": ["Bug"],
        "attack": 125,
        "levelType": "slow",
        "exp": 175,
        "eggCycles": 25
    }, {
        "id": 128,
        "name": "Tauros",
        "catchRate": 45,
        "type": ["Normal"],
        "attack": 100,
        "levelType": "slow",
        "exp": 172,
        "eggCycles": 20
    }, {
        "id": 129,
        "name": "Magikarp",
        "catchRate": 255,
        "type": ["Water"],
        "attack": 15,
        "levelType": "slow",
        "exp": 40,
        "eggCycles": 5,
        "evolutions": [new LevelEvolution("Magikarp", "Gyarados", 20)],
    }, {
        "id": 130,
        "name": "Gyarados",
        "catchRate": 45,
        "type": ["Water", "Flying"],
        "attack": 125,
        "levelType": "slow",
        "exp": 189,
        "eggCycles": 5
    }, {
        "id": 131,
        "name": "Lapras",
        "catchRate": 45,
        "type": ["Water", "Ice"],
        "attack": 85,
        "levelType": "slow",
        "exp": 187,
        "eggCycles": 40
    }, {
        "id": 132,
        "name": "Ditto",
        "catchRate": 35,
        "type": ["Normal"],
        "attack": 48,
        "levelType": "mediumfast",
        "exp": 101,
        "eggCycles": 20
    }, {
        "id": 133,
        "name": "Eevee",
        "catchRate": 255,
        "type": ["Normal"],
        "attack": 55,
        "levelType": "mediumfast",
        "exp": 65,
        "eggCycles": 35,
        "evolutions": [
            new StoneEvolution("Eevee", "Vaporeon", GameConstants.StoneType.Water_stone),
            new StoneEvolution("Eevee", "Jolteon", GameConstants.StoneType.Thunder_stone),
            new StoneEvolution("Eevee", "Flareon", GameConstants.StoneType.Fire_stone),
            new StoneEvolution("Eevee", "Espeon", GameConstants.StoneType.Time_stone),
            new StoneEvolution("Eevee", "Umbreon", GameConstants.StoneType.Time_stone),
        ],
    }, {
        "id": 134,
        "name": "Vaporeon",
        "catchRate": 45,
        "type": ["Water"],
        "attack": 110,
        "levelType": "mediumfast",
        "exp": 184,
        "eggCycles": 35
    }, {
        "id": 135,
        "name": "Jolteon",
        "catchRate": 45,
        "type": ["Electric"],
        "attack": 110,
        "levelType": "mediumfast",
        "exp": 184,
        "eggCycles": 35
    }, {
        "id": 136,
        "name": "Flareon",
        "catchRate": 45,
        "type": ["Fire"],
        "attack": 130,
        "levelType": "mediumfast",
        "exp": 184,
        "eggCycles": 35
    }, {
        "id": 137,
        "name": "Porygon",
        "catchRate": 45,
        "type": ["Normal"],
        "attack": 85,
        "levelType": "mediumfast",
        "exp": 79,
        "eggCycles": 20,
        // TODO implement porygon2
        // "evolutions": [new LevelEvolution("Porygon", "Porygon2", Upgrade)],
    }, {
        "id": 138,
        "name": "Omanyte",
        "catchRate": 45,
        "type": ["Rock", "Water"],
        "attack": 90,
        "levelType": "mediumfast",
        "exp": 71,
        "eggCycles": 30,
        "evolutions": [new LevelEvolution("Omanyte", "Omastar", 40)],
    }, {
        "id": 139,
        "name": "Omastar",
        "catchRate": 45,
        "type": ["Rock", "Water"],
        "attack": 115,
        "levelType": "mediumfast",
        "exp": 173,
        "eggCycles": 30
    }, {
        "id": 140,
        "name": "Kabuto",
        "catchRate": 45,
        "type": ["Rock", "Water"],
        "attack": 80,
        "levelType": "mediumfast",
        "exp": 71,
        "eggCycles": 30,
        "evolutions": [new LevelEvolution("Kabuto", "Kabutops", 40)],
    }, {
        "id": 141,
        "name": "Kabutops",
        "catchRate": 45,
        "type": ["Rock", "Water"],
        "attack": 115,
        "levelType": "mediumfast",
        "exp": 173,
        "eggCycles": 30
    }, {
        "id": 142,
        "name": "Aerodactyl",
        "catchRate": 45,
        "type": ["Rock", "Flying"],
        "attack": 105,
        "levelType": "slow",
        "exp": 180,
        "eggCycles": 35
    }, {
        "id": 143,
        "name": "Snorlax",
        "catchRate": 25,
        "type": ["Normal"],
        "attack": 110,
        "levelType": "slow",
        "exp": 189,
        "eggCycles": 40
    }, {
        "id": 144,
        "name": "Articuno",
        "catchRate": 3,
        "type": ["Ice", "Flying"],
        "attack": 95,
        "levelType": "slow",
        "exp": 261,
        "eggCycles": 80
    }, {
        "id": 145,
        "name": "Zapdos",
        "catchRate": 3,
        "type": ["Electric", "Flying"],
        "attack": 125,
        "levelType": "slow",
        "exp": 261,
        "eggCycles": 80
    }, {
        "id": 146,
        "name": "Moltres",
        "catchRate": 3,
        "type": ["Fire", "Flying"],
        "attack": 125,
        "levelType": "slow",
        "exp": 261,
        "eggCycles": 80
    }, {
        "id": 147,
        "name": "Dratini",
        "catchRate": 45,
        "type": ["Dragon"],
        "attack": 64,
        "levelType": "slow",
        "exp": 60,
        "eggCycles": 40,
        "evolutions": [new LevelEvolution("Dratini", "Dragonair", 30)],
    }, {
        "id": 148,
        "name": "Dragonair",
        "catchRate": 45,
        "type": ["Dragon"],
        "attack": 84,
        "levelType": "slow",
        "exp": 147,
        "eggCycles": 40,
        "evolutions": [new LevelEvolution("Dragonair", "Dragonite", 55)],
    }, {
        "id": 149,
        "name": "Dragonite",
        "catchRate": 45,
        "type": ["Dragon", "Flying"],
        "attack": 134,
        "levelType": "slow",
        "exp": 270,
        "eggCycles": 40
    }, {
        "id": 150,
        "name": "Mewtwo",
        "catchRate": 3,
        "type": ["Psychic"],
        "attack": 154,
        "levelType": "slow",
        "exp": 306,
        "eggCycles": 120
    }, {
        "id": 151,
        "name": "Mew",
        "catchRate": 45,
        "type": ["Psychic"],
        "attack": 100,
        "levelType": "mediumslow",
        "exp": 270,
        "eggCycles": 120
    }, {
        "id": 152,
        "name": "Chikorita",
        "catchRate": 45,
        "type": ["Grass"],
        "attack": 65,
        "levelType": "mediumslow",
        "exp": 64,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Chikorita", "Bayleef", 16)],
    }, {
        "id": 153,
        "name": "Bayleef",
        "catchRate": 45,
        "type": ["Grass"],
        "attack": 80,
        "levelType": "mediumslow",
        "exp": 142,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Bayleef", "Meganium", 32)],
    }, {
        "id": 154,
        "name": "Meganium",
        "catchRate": 45,
        "type": ["Grass"],
        "attack": 100,
        "levelType": "mediumslow",
        "exp": 236,
        "eggCycles": 20
    }, {
        "id": 155,
        "name": "Cyndaquil",
        "catchRate": 45,
        "type": ["Fire"],
        "attack": 52,
        "levelType": "mediumslow",
        "exp": 62,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Cyndaquil", "Quilava", 14)],
    }, {
        "id": 156,
        "name": "Quilava",
        "catchRate": 45,
        "type": ["Fire"],
        "attack": 65,
        "levelType": "mediumslow",
        "exp": 142,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Quilava", "Typhlosion", 36)],
    }, {
        "id": 157,
        "name": "Typhlosion",
        "catchRate": 45,
        "type": ["Fire"],
        "attack": 85,
        "levelType": "mediumslow",
        "exp": 240,
        "eggCycles": 20
    }, {
        "id": 158,
        "name": "Totodile",
        "catchRate": 45,
        "type": ["Water"],
        "attack": 65,
        "levelType": "mediumslow",
        "exp": 63,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Totodile", "Croconaw", 18)],
    }, {
        "id": 159,
        "name": "Croconaw",
        "catchRate": 45,
        "type": ["Water"],
        "attack": 80,
        "levelType": "mediumslow",
        "exp": 142,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Croconaw", "Feraligatr", 30)],
    }, {
        "id": 160,
        "name": "Feraligatr",
        "catchRate": 45,
        "type": ["Water"],
        "attack": 105,
        "levelType": "mediumslow",
        "exp": 239,
        "eggCycles": 20
    }, {
        "id": 161,
        "name": "Sentret",
        "catchRate": 255,
        "type": ["Normal"],
        "attack": 46,
        "levelType": "mediumfast",
        "exp": 43,
        "eggCycles": 15,
        "evolutions": [new LevelEvolution("Sentret", "Furret", 15)],
    }, {
        "id": 162,
        "name": "Furret",
        "catchRate": 90,
        "type": ["Normal"],
        "attack": 76,
        "levelType": "mediumfast",
        "exp": 145,
        "eggCycles": 15
    }, {
        "id": 163,
        "name": "Hoothoot",
        "catchRate": 255,
        "type": ["Normal", "Flying"],
        "attack": 56,
        "levelType": "mediumfast",
        "exp": 52,
        "eggCycles": 15,
        "evolutions": [new LevelEvolution("Hoothoot", "Noctowl", 20)],
    }, {
        "id": 164,
        "name": "Noctowl",
        "catchRate": 90,
        "type": ["Normal", "Flying"],
        "attack": 96,
        "levelType": "mediumfast",
        "exp": 158,
        "eggCycles": 15
    }, {
        "id": 165,
        "name": "Ledyba",
        "catchRate": 255,
        "type": ["Bug", "Flying"],
        "attack": 80,
        "levelType": "fast",
        "exp": 53,
        "eggCycles": 15,
        "evolutions": [new LevelEvolution("Ledyba", "Ledian", 18)],
    }, {
        "id": 166,
        "name": "Ledian",
        "catchRate": 90,
        "type": ["Bug", "Flying"],
        "attack": 110,
        "levelType": "fast",
        "exp": 137,
        "eggCycles": 15
    }, {
        "id": 167,
        "name": "Spinarak",
        "catchRate": 255,
        "type": ["Bug", "Poison"],
        "attack": 60,
        "levelType": "fast",
        "exp": 50,
        "eggCycles": 15,
        "evolutions": [new LevelEvolution("Spinarak", "Ariados", 22)],
    }, {
        "id": 168,
        "name": "Ariados",
        "catchRate": 90,
        "type": ["Bug", "Poison"],
        "attack": 90,
        "levelType": "fast",
        "exp": 140,
        "eggCycles": 15
    }, {
        "id": 169,
        "name": "Crobat",
        "catchRate": 90,
        "type": ["Poison", "Flying"],
        "attack": 90,
        "levelType": "mediumfast",
        "exp": 241,
        "eggCycles": 15
    }, {
        "id": 170,
        "name": "Chinchou",
        "catchRate": 190,
        "type": ["Water", "Electric"],
        "attack": 56,
        "levelType": "slow",
        "exp": 66,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Chinchou", "Lanturn", 27)],
    }, {
        "id": 171,
        "name": "Lanturn",
        "catchRate": 75,
        "type": ["Water", "Electric"],
        "attack": 76,
        "levelType": "slow",
        "exp": 161,
        "eggCycles": 20
    }, {
        "id": 172,
        "name": "Pichu",
        "catchRate": 190,
        "type": ["Electric"],
        "attack": 40,
        "levelType": "mediumfast",
        "exp": 41,
        "eggCycles": 10,
        "evolutions": [new LevelEvolution("Pichu", "Pikachu", 100)],
    }, {
        "id": 173,
        "name": "Cleffa",
        "catchRate": 150,
        "type": ["Fairy"],
        "attack": 55,
        "levelType": "fast",
        "exp": 44,
        "eggCycles": 10,
        "evolutions": [new LevelEvolution("Cleffa", "Clefairy", 100)],
    }, {
        "id": 174,
        "name": "Igglybuff",
        "catchRate": 170,
        "type": ["Normal", "Fairy"],
        "attack": 30,
        "levelType": "fast",
        "exp": 42,
        "eggCycles": 10,
        "evolutions": [new LevelEvolution("Igglybuff", "Jigglypuff", 100)],
    }, {
        "id": 175,
        "name": "Togepi",
        "catchRate": 190,
        "type": ["Fairy"],
        "attack": 65,
        "levelType": "fast",
        "exp": 49,
        "eggCycles": 10,
        "evolutions": [new LevelEvolution("Togepi", "Togetic", 100)],
    }, {
        "id": 176,
        "name": "Togetic",
        "catchRate": 75,
        "type": ["Fairy", "Flying"],
        "attack": 105,
        "levelType": "fast",
        "exp": 142,
        "eggCycles": 10,
    }, {
        "id": 177,
        "name": "Natu",
        "catchRate": 190,
        "type": ["Psychic", "Flying"],
        "attack": 50,
        "levelType": "mediumfast",
        "exp": 64,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Natu", "Xatu", 25)],
    }, {
        "id": 178,
        "name": "Xatu",
        "catchRate": 75,
        "type": ["Psychic", "Flying"],
        "attack": 75,
        "levelType": "mediumfast",
        "exp": 165,
        "eggCycles": 20
    }, {
        "id": 179,
        "name": "Mareep",
        "catchRate": 235,
        "type": ["Electric"],
        "attack": 45,
        "levelType": "mediumslow",
        "exp": 56,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Mareep", "Flaaffy", 15)],
    }, {
        "id": 180,
        "name": "Flaaffy",
        "catchRate": 120,
        "type": ["Electric"],
        "attack": 60,
        "levelType": "mediumslow",
        "exp": 128,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Flaaffy", "Ampharos", 30)],
    }, {
        "id": 181,
        "name": "Ampharos",
        "catchRate": 45,
        "type": ["Electric"],
        "attack": 110,
        "levelType": "mediumslow",
        "exp": 230,
        "eggCycles": 20
    }, {
        "id": 182,
        "name": "Bellossom",
        "catchRate": 45,
        "type": ["Grass"],
        "attack": 100,
        "levelType": "mediumslow",
        "exp": 221,
        "eggCycles": 20
    }, {
        "id": 183,
        "name": "Marill",
        "catchRate": 190,
        "type": ["Water", "Fairy"],
        "attack": 50,
        "levelType": "fast",
        "exp": 88,
        "eggCycles": 10,
        "evolutions": [new LevelEvolution("Marill", "Azumarill", 18)],
    }, {
        "id": 184,
        "name": "Azumarill",
        "catchRate": 75,
        "type": ["Water", "Fairy"],
        "attack": 80,
        "levelType": "fast",
        "exp": 189,
        "eggCycles": 10
    }, {
        "id": 185,
        "name": "Sudowoodo",
        "catchRate": 65,
        "type": ["Rock"],
        "attack": 100,
        "levelType": "mediumfast",
        "exp": 144,
        "eggCycles": 20
    }, {
        "id": 186,
        "name": "Politoed",
        "catchRate": 45,
        "type": ["Water"],
        "attack": 100,
        "levelType": "mediumslow",
        "exp": 225,
        "eggCycles": 20
    }, {
        "id": 187,
        "name": "Hoppip",
        "catchRate": 255,
        "type": ["Grass", "Flying"],
        "attack": 55,
        "levelType": "mediumslow",
        "exp": 50,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Hoppip", "Skiploom", 18)],
    }, {
        "id": 188,
        "name": "Skiploom",
        "catchRate": 120,
        "type": ["Grass", "Flying"],
        "attack": 65,
        "levelType": "mediumslow",
        "exp": 119,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Skiploom", "Jumpluff", 27)],
    }, {
        "id": 189,
        "name": "Jumpluff",
        "catchRate": 45,
        "type": ["Grass", "Flying"],
        "attack": 95,
        "levelType": "mediumslow",
        "exp": 207,
        "eggCycles": 20
    }, {
        "id": 190,
        "name": "Aipom",
        "catchRate": 45,
        "type": ["Normal"],
        "attack": 70,
        "levelType": "fast",
        "exp": 72,
        "eggCycles": 20,
    }, {
        "id": 191,
        "name": "Sunkern",
        "catchRate": 235,
        "type": ["Grass"],
        "attack": 30,
        "levelType": "mediumslow",
        "exp": 36,
        "eggCycles": 20,
        "evolutions": [new StoneEvolution("Sunkern", "Sunflora", GameConstants.StoneType.Sun_stone)],
    }, {
        "id": 192,
        "name": "Sunflora",
        "catchRate": 120,
        "type": ["Grass"],
        "attack": 85,
        "levelType": "mediumslow",
        "exp": 149,
        "eggCycles": 20
    }, {
        "id": 193,
        "name": "Yanma",
        "catchRate": 75,
        "type": ["Bug", "Flying"],
        "attack": 65,
        "levelType": "mediumfast",
        "exp": 78,
        "eggCycles": 20,
    }, {
        "id": 194,
        "name": "Wooper",
        "catchRate": 255,
        "type": ["Water", "Ground"],
        "attack": 45,
        "levelType": "mediumfast",
        "exp": 42,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Wooper", "Quagsire", 20)],
    }, {
        "id": 195,
        "name": "Quagsire",
        "catchRate": 90,
        "type": ["Water", "Ground"],
        "attack": 85,
        "levelType": "mediumfast",
        "exp": 151,
        "eggCycles": 20
    }, {
        "id": 196,
        "name": "Espeon",
        "catchRate": 45,
        "type": ["Psychic"],
        "attack": 95,
        "levelType": "mediumfast",
        "exp": 184,
        "eggCycles": 35
    }, {
        "id": 197,
        "name": "Umbreon",
        "catchRate": 45,
        "type": ["Dark"],
        "attack": 130,
        "levelType": "mediumfast",
        "exp": 184,
        "eggCycles": 35
    }, {
        "id": 198,
        "name": "Murkrow",
        "catchRate": 30,
        "type": ["Dark", "Flying"],
        "attack": 85,
        "levelType": "mediumslow",
        "exp": 81,
        "eggCycles": 20,
    }, {
        "id": 199,
        "name": "Slowking",
        "catchRate": 70,
        "type": ["Water", "Psychic"],
        "attack": 110,
        "levelType": "mediumfast",
        "exp": 172,
        "eggCycles": 20
    }, {
        "id": 200,
        "name": "Misdreavus",
        "catchRate": 45,
        "type": ["Ghost"],
        "attack": 85,
        "levelType": "fast",
        "exp": 87,
        "eggCycles": 25,
    }, {
        "id": 201,
        "name": "Unown",
        "catchRate": 225,
        "type": ["Psychic"],
        "attack": 72,
        "levelType": "mediumfast",
        "exp": 118,
        "eggCycles": 40
    }, {
        "id": 202,
        "name": "Wobbuffet",
        "catchRate": 45,
        "type": ["Psychic"],
        "attack": 58,
        "levelType": "mediumfast",
        "exp": 142,
        "eggCycles": 20
    }, {
        "id": 203,
        "name": "Girafarig",
        "catchRate": 60,
        "type": ["Normal", "Psychic"],
        "attack": 80,
        "levelType": "mediumfast",
        "exp": 159,
        "eggCycles": 20
    }, {
        "id": 204,
        "name": "Pineco",
        "catchRate": 190,
        "type": ["Bug"],
        "attack": 65,
        "levelType": "mediumfast",
        "exp": 58,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Pineco", "Forretress", 31)],
    }, {
        "id": 205,
        "name": "Forretress",
        "catchRate": 75,
        "type": ["Bug", "Steel"],
        "attack": 90,
        "levelType": "mediumfast",
        "exp": 163,
        "eggCycles": 20
    }, {
        "id": 206,
        "name": "Dunsparce",
        "catchRate": 190,
        "type": ["Normal"],
        "attack": 70,
        "levelType": "mediumfast",
        "exp": 145,
        "eggCycles": 20
    }, {
        "id": 207,
        "name": "Gligar",
        "catchRate": 60,
        "type": ["Ground", "Flying"],
        "attack": 75,
        "levelType": "mediumslow",
        "exp": 86,
        "eggCycles": 20,
    }, {
        "id": 208,
        "name": "Steelix",
        "catchRate": 25,
        "type": ["Steel", "Ground"],
        "attack": 125,
        "levelType": "mediumfast",
        "exp": 179,
        "eggCycles": 25
    }, {
        "id": 209,
        "name": "Snubbull",
        "catchRate": 190,
        "type": ["Fairy"],
        "attack": 80,
        "levelType": "fast",
        "exp": 60,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Snubbull", "Granbull", 23)],
    }, {
        "id": 210,
        "name": "Granbull",
        "catchRate": 75,
        "type": ["Fairy"],
        "attack": 120,
        "levelType": "fast",
        "exp": 158,
        "eggCycles": 20
    }, {
        "id": 211,
        "name": "Qwilfish",
        "catchRate": 45,
        "type": ["Water", "Poison"],
        "attack": 95,
        "levelType": "mediumfast",
        "exp": 88,
        "eggCycles": 20
    }, {
        "id": 212,
        "name": "Scizor",
        "catchRate": 25,
        "type": ["Bug", "Steel"],
        "attack": 150,
        "levelType": "mediumfast",
        "exp": 175,
        "eggCycles": 25
    }, {
        "id": 213,
        "name": "Shuckle",
        "catchRate": 190,
        "type": ["Bug", "Rock"],
        "attack": 230,
        "levelType": "mediumslow",
        "exp": 177,
        "eggCycles": 20
    }, {
        "id": 214,
        "name": "Heracross",
        "catchRate": 45,
        "type": ["Bug", "Fighting"],
        "attack": 185,
        "levelType": "slow",
        "exp": 175,
        "eggCycles": 25
    }, {
        "id": 215,
        "name": "Sneasel",
        "catchRate": 60,
        "type": ["Dark", "Ice"],
        "attack": 95,
        "levelType": "mediumslow",
        "exp": 86,
        "eggCycles": 20,
    }, {
        "id": 216,
        "name": "Teddiursa",
        "catchRate": 120,
        "type": ["Normal"],
        "attack": 80,
        "levelType": "mediumfast",
        "exp": 66,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Teddiursa", "Ursaring", 30)],
    }, {
        "id": 217,
        "name": "Ursaring",
        "catchRate": 60,
        "type": ["Normal"],
        "attack": 130,
        "levelType": "mediumfast",
        "exp": 175,
        "eggCycles": 20
    }, {
        "id": 218,
        "name": "Slugma",
        "catchRate": 190,
        "type": ["Fire"],
        "attack": 40,
        "levelType": "mediumfast",
        "exp": 50,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Slugma", "Magcargo", 38)],
    }, {
        "id": 219,
        "name": "Magcargo",
        "catchRate": 75,
        "type": ["Fire", "Rock"],
        "attack": 80,
        "levelType": "mediumfast",
        "exp": 151,
        "eggCycles": 20
    }, {
        "id": 220,
        "name": "Swinub",
        "catchRate": 225,
        "type": ["Ice", "Ground"],
        "attack": 50,
        "levelType": "slow",
        "exp": 50,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Swinub", "Piloswine", 33)],
    }, {
        "id": 221,
        "name": "Piloswine",
        "catchRate": 75,
        "type": ["Ice", "Ground"],
        "attack": 100,
        "levelType": "slow",
        "exp": 158,
        "eggCycles": 20,
    }, {
        "id": 222,
        "name": "Corsola",
        "catchRate": 60,
        "type": ["Water", "Rock"],
        "attack": 95,
        "levelType": "fast",
        "exp": 144,
        "eggCycles": 20
    }, {
        "id": 223,
        "name": "Remoraid",
        "catchRate": 190,
        "type": ["Water"],
        "attack": 65,
        "levelType": "mediumfast",
        "exp": 60,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Remoraid", "Octillery", 25)],
    }, {
        "id": 224,
        "name": "Octillery",
        "catchRate": 75,
        "type": ["Water"],
        "attack": 105,
        "levelType": "mediumfast",
        "exp": 168,
        "eggCycles": 20
    }, {
        "id": 225,
        "name": "Delibird",
        "catchRate": 45,
        "type": ["Ice", "Flying"],
        "attack": 55,
        "levelType": "fast",
        "exp": 116,
        "eggCycles": 20
    }, {
        "id": 226,
        "name": "Mantine",
        "catchRate": 25,
        "type": ["Water", "Flying"],
        "attack": 140,
        "levelType": "slow",
        "exp": 170,
        "eggCycles": 25
    }, {
        "id": 227,
        "name": "Skarmory",
        "catchRate": 25,
        "type": ["Steel", "Flying"],
        "attack": 80,
        "levelType": "slow",
        "exp": 163,
        "eggCycles": 25
    }, {
        "id": 228,
        "name": "Houndour",
        "catchRate": 120,
        "type": ["Dark", "Fire"],
        "attack": 60,
        "levelType": "slow",
        "exp": 66,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Houndour", "Houndoom", 24)],
    }, {
        "id": 229,
        "name": "Houndoom",
        "catchRate": 45,
        "type": ["Dark", "Fire"],
        "attack": 90,
        "levelType": "slow",
        "exp": 175,
        "eggCycles": 20
    }, {
        "id": 230,
        "name": "Kingdra",
        "catchRate": 45,
        "type": ["Water", "Dragon"],
        "attack": 95,
        "levelType": "mediumfast",
        "exp": 243,
        "eggCycles": 20
    }, {
        "id": 231,
        "name": "Phanpy",
        "catchRate": 120,
        "type": ["Ground"],
        "attack": 60,
        "levelType": "mediumfast",
        "exp": 66,
        "eggCycles": 20,
        "evolutions": [new LevelEvolution("Phanpy", "Donphan", 25)],
    }, {
        "id": 232,
        "name": "Donphan",
        "catchRate": 60,
        "type": ["Ground"],
        "attack": 120,
        "levelType": "mediumfast",
        "exp": 175,
        "eggCycles": 20
    }, {
        "id": 233,
        "name": "Porygon2",
        "catchRate": 45,
        "type": ["Normal"],
        "attack": 95,
        "levelType": "mediumfast",
        "exp": 180,
        "eggCycles": 20,
    }, {
        "id": 234,
        "name": "Stantler",
        "catchRate": 45,
        "type": ["Normal"],
        "attack": 95,
        "levelType": "slow",
        "exp": 163,
        "eggCycles": 20
    }, {
        "id": 235,
        "name": "Smeargle",
        "catchRate": 45,
        "type": ["Normal"],
        "attack": 45,
        "levelType": "fast",
        "exp": 88,
        "eggCycles": 20
    }, {
        "id": 236,
        "name": "Tyrogue",
        "catchRate": 75,
        "type": ["Fighting"],
        "attack": 35,
        "levelType": "mediumfast",
        "exp": 42,
        "eggCycles": 25,
        "evolutions": [
            new LevelEvolution("Tyrogue", "Hitmonlee", 20),
            new LevelEvolution("Tyrogue", "Hitmonchan", 20),
            new LevelEvolution("Tyrogue", "Hitmontop", 20),
        ],
    }, {
        "id": 237,
        "name": "Hitmontop",
        "catchRate": 45,
        "type": ["Fighting"],
        "attack": 110,
        "levelType": "mediumfast",
        "exp": 159,
        "eggCycles": 25
    }, {
        "id": 238,
        "name": "Smoochum",
        "catchRate": 45,
        "type": ["Ice", "Psychic"],
        "attack": 65,
        "levelType": "mediumfast",
        "exp": 61,
        "eggCycles": 25,
        "evolutions": [new LevelEvolution("Smoochum", "Jynx", 30)],
    }, {
        "id": 239,
        "name": "Elekid",
        "catchRate": 45,
        "type": ["Electric"],
        "attack": 63,
        "levelType": "mediumfast",
        "exp": 72,
        "eggCycles": 25,
        "evolutions": [new LevelEvolution("Elekid", "Electabuzz", 30)],
    }, {
        "id": 240,
        "name": "Magby",
        "catchRate": 45,
        "type": ["Fire"],
        "attack": 75,
        "levelType": "mediumfast",
        "exp": 73,
        "eggCycles": 25,
        "evolutions": [new LevelEvolution("Magby", "Magmar", 30)],
    }, {
        "id": 241,
        "name": "Miltank",
        "catchRate": 45,
        "type": ["Normal"],
        "attack": 80,
        "levelType": "slow",
        "exp": 172,
        "eggCycles": 20
    }, {
        "id": 242,
        "name": "Blissey",
        "catchRate": 30,
        "type": ["Normal"],
        "attack": 135,
        "levelType": "fast",
        "exp": 608,
        "eggCycles": 40
    }, {
        "id": 243,
        "name": "Raikou",
        "catchRate": 3,
        "type": ["Electric"],
        "attack": 100,
        "levelType": "slow",
        "exp": 261,
        "eggCycles": 80
    }, {
        "id": 244,
        "name": "Entei",
        "catchRate": 3,
        "type": ["Fire"],
        "attack": 115,
        "levelType": "slow",
        "exp": 261,
        "eggCycles": 80
    }, {
        "id": 245,
        "name": "Suicune",
        "catchRate": 3,
        "type": ["Water"],
        "attack": 115,
        "levelType": "slow",
        "exp": 261,
        "eggCycles": 80
    }, {
        "id": 246,
        "name": "Larvitar",
        "catchRate": 45,
        "type": ["Rock", "Ground"],
        "attack": 64,
        "levelType": "slow",
        "exp": 60,
        "eggCycles": 40,
        "evolutions": [new LevelEvolution("Larvitar", "Pupitar", 30)],
    }, {
        "id": 247,
        "name": "Pupitar",
        "catchRate": 45,
        "type": ["Rock", "Ground"],
        "attack": 84,
        "levelType": "slow",
        "exp": 144,
        "eggCycles": 40,
        "evolutions": [new LevelEvolution("Pupitar", "Tyranitar", 55)],
    }, {
        "id": 248,
        "name": "Tyranitar",
        "catchRate": 45,
        "type": ["Rock", "Dark"],
        "attack": 164,
        "levelType": "slow",
        "exp": 270,
        "eggCycles": 40
    }, {
        "id": 249,
        "name": "Lugia",
        "catchRate": 3,
        "type": ["Psychic", "Flying"],
        "attack": 154,
        "levelType": "slow",
        "exp": 306,
        "eggCycles": 120
    }, {
        "id": 250,
        "name": "Ho-Oh",
        "catchRate": 3,
        "type": ["Fire", "Flying"],
        "attack": 154,
        "levelType": "slow",
        "exp": 306,
        "eggCycles": 120
    }, {
        "id": 251,
        "name": "Celebi",
        "catchRate": 45,
        "type": ["Psychic", "Grass"],
        "attack": 100,
        "levelType": "mediumslow",
        "exp": 270,
        "eggCycles": 120
    }, {
        "id": 252,
        "name": "Treecko",
        "type": ["Grass"],
        "attack": 70,
        "eggCycles": 20,
        "levelType": "mediumslow",
        "exp": 62,
        "catchRate": 45,
        "evolutions": [new LevelEvolution("Treecko", "Grovyle", 16)],
    }, {
        "id": 253,
        "name": "Grovyle",
        "type": ["Grass"],
        "attack": 95,
        "eggCycles": 20,
        "levelType": "mediumslow",
        "exp": 142,
        "catchRate": 45,
        "evolutions": [new LevelEvolution("Grovyle", "Sceptile", 36)],
    }, {
        "id": 254,
        "name": "Sceptile",
        "type": ["Grass"],
        "attack": 120,
        "eggCycles": 20,
        "levelType": "mediumslow",
        "exp": 239,
        "catchRate": 45
    }, {
        "id": 255,
        "name": "Torchic",
        "type": ["Fire"],
        "attack": 70,
        "eggCycles": 20,
        "levelType": "mediumslow",
        "exp": 62,
        "catchRate": 45,
        "evolutions": [new LevelEvolution("Torchic", "Combusken", 16)],
    }, {
        "id": 256,
        "name": "Combusken",
        "type": ["Fire", "Fighting"],
        "attack": 85,
        "eggCycles": 20,
        "levelType": "mediumslow",
        "exp": 142,
        "catchRate": 45,
        "evolutions": [new LevelEvolution("Combusken", "Blaziken", 36)],
    }, {
        "id": 257,
        "name": "Blaziken",
        "type": ["Fire", "Fighting"],
        "attack": 120,
        "eggCycles": 20,
        "levelType": "mediumslow",
        "exp": 239,
        "catchRate": 45
    }, {
        "id": 258,
        "name": "Mudkip",
        "type": ["Water"],
        "attack": 70,
        "eggCycles": 20,
        "levelType": "mediumslow",
        "exp": 62,
        "catchRate": 45,
        "evolutions": [new LevelEvolution("Mudkip", "Marshtomp", 16)],
    }, {
        "id": 259,
        "name": "Marshtomp",
        "type": ["Water", "Ground"],
        "attack": 85,
        "eggCycles": 20,
        "levelType": "mediumslow",
        "exp": 142,
        "catchRate": 45,
        "evolutions": [new LevelEvolution("Marshtomp", "Swampert", 36)],
    }, {
        "id": 260,
        "name": "Swampert",
        "type": ["Water", "Ground"],
        "attack": 110,
        "eggCycles": 20,
        "levelType": "mediumslow",
        "exp": 241,
        "catchRate": 45
    }, {
        "id": 261,
        "name": "Poochyena",
        "type": ["Dark"],
        "attack": 55,
        "eggCycles": 15,
        "levelType": "mediumfast",
        "exp": 56,
        "catchRate": 255,
        "evolutions": [new LevelEvolution("Poochyena", "Mightyena", 18)],
    }, {
        "id": 262,
        "name": "Mightyena",
        "type": ["Dark"],
        "attack": 90,
        "eggCycles": 15,
        "levelType": "mediumfast",
        "exp": 147,
        "catchRate": 127
    }, {
        "id": 263,
        "name": "Zigzagoon",
        "type": ["Normal"],
        "attack": 60,
        "eggCycles": 15,
        "levelType": "mediumfast",
        "exp": 56,
        "catchRate": 255,
        "evolutions": [new LevelEvolution("Zigzagoon", "Linoone", 20)],
    }, {
        "id": 264,
        "name": "Linoone",
        "type": ["Normal"],
        "attack": 100,
        "eggCycles": 15,
        "levelType": "mediumfast",
        "exp": 147,
        "catchRate": 90,
    }, {
        "id": 265,
        "name": "Wurmple",
        "type": ["Bug"],
        "attack": 45,
        "eggCycles": 15,
        "levelType": "mediumfast",
        "exp": 56,
        "catchRate": 255,
        "evolutions": [
            new LevelEvolution("Wurmple", "Silcoon", 7),
            new LevelEvolution("Wurmple", "Cascoon", 7)
        ],
    }, {
        "id": 266,
        "name": "Silcoon",
        "type": ["Bug"],
        "attack": 55,
        "eggCycles": 15,
        "levelType": "mediumfast",
        "exp": 72,
        "catchRate": 120,
        "evolutions": [new LevelEvolution("Silcoon", "Beautifly", 10)],
    }, {
        "id": 267,
        "name": "Beautifly",
        "type": ["Bug", "Flying"],
        "attack": 100,
        "eggCycles": 15,
        "levelType": "mediumfast",
        "exp": 178,
        "catchRate": 45
    }, {
        "id": 268,
        "name": "Cascoon",
        "type": ["Bug"],
        "attack": 55,
        "eggCycles": 15,
        "levelType": "mediumfast",
        "exp": 72,
        "catchRate": 120
    }, {
        "id": 269,
        "name": "Dustox",
        "type": ["Bug", "Poison"],
        "attack": 90,
        "eggCycles": 15,
        "levelType": "mediumfast",
        "exp": 173,
        "catchRate": 45
    }, {
        "id": 270,
        "name": "Lotad",
        "type": ["Water", "Grass"],
        "attack": 50,
        "eggCycles": 15,
        "levelType": "mediumslow",
        "exp": 44,
        "catchRate": 255,
        "evolutions": [new LevelEvolution("Lotad", "Lombre", 14)],
    }, {
        "id": 271,
        "name": "Lombre",
        "type": ["Water", "Grass"],
        "attack": 70,
        "eggCycles": 15,
        "levelType": "mediumslow",
        "exp": 119,
        "catchRate": 120,
        "evolutions": [new StoneEvolution("Lombre", "Ludicolo", GameConstants.StoneType.Water_stone)],
    }, {
        "id": 272,
        "name": "Ludicolo",
        "type": ["Water", "Grass"],
        "attack": 100,
        "eggCycles": 15,
        "levelType": "mediumslow",
        "exp": 216,
        "catchRate": 45
    }, {
        "id": 273,
        "name": "Seedot",
        "type": ["Grass"],
        "attack": 50,
        "eggCycles": 15,
        "levelType": "mediumslow",
        "exp": 44,
        "catchRate": 255,
        "evolutions": [new LevelEvolution("Seedot", "Nuzleaf", 14)],
    }, {
        "id": 274,
        "name": "Nuzleaf",
        "type": ["Grass", "Dark"],
        "attack": 70,
        "eggCycles": 15,
        "levelType": "mediumslow",
        "exp": 119,
        "catchRate": 120,
        "evolutions": [new StoneEvolution("Nuzleaf", "Shiftry", GameConstants.StoneType.Leaf_stone)],
    }, {
        "id": 275,
        "name": "Shiftry",
        "type": ["Grass", "Dark"],
        "attack": 100,
        "eggCycles": 15,
        "levelType": "mediumslow",
        "exp": 216,
        "catchRate": 45
    }, {
        "id": 276,
        "name": "Taillow",
        "type": ["Normal", "Flying"],
        "attack": 85,
        "eggCycles": 15,
        "levelType": "mediumslow",
        "exp": 54,
        "catchRate": 200,
        "evolutions": [new LevelEvolution("Taillow", "Swellow", 22)],
    }, {
        "id": 277,
        "name": "Swellow",
        "type": ["Normal", "Flying"],
        "attack": 125,
        "eggCycles": 15,
        "levelType": "mediumslow",
        "exp": 159,
        "catchRate": 45
    }, {
        "id": 278,
        "name": "Wingull",
        "type": ["Water", "Flying"],
        "attack": 85,
        "eggCycles": 20,
        "levelType": "mediumfast",
        "exp": 54,
        "catchRate": 190,
        "evolutions": [new LevelEvolution("Wingull", "Pelipper", 25)],
    }, {
        "id": 279,
        "name": "Pelipper",
        "type": ["Water", "Flying"],
        "attack": 100,
        "eggCycles": 20,
        "levelType": "mediumfast",
        "exp": 154,
        "catchRate": 45
    }, {
        "id": 280,
        "name": "Ralts",
        "type": ["Psychic", "Fairy"],
        "attack": 45,
        "eggCycles": 20,
        "levelType": "slow",
        "exp": 40,
        "catchRate": 235,
        "evolutions": [new LevelEvolution("Ralts", "Kirlia", 20)],
    }, {
        "id": 281,
        "name": "Kirlia",
        "type": ["Psychic", "Fairy"],
        "attack": 65,
        "eggCycles": 20,
        "levelType": "slow",
        "exp": 97,
        "catchRate": 120,
        "evolutions": [new LevelEvolution("Kirlia", "Gardevoir", 30)],
    }, {
        "id": 282,
        "name": "Gardevoir",
        "type": ["Psychic", "Fairy"],
        "attack": 125,
        "eggCycles": 20,
        "levelType": "slow",
        "exp": 233,
        "catchRate": 45
    }, {
        "id": 283,
        "name": "Surskit",
        "type": ["Bug", "Water"],
        "attack": 65,
        "eggCycles": 15,
        "levelType": "mediumfast",
        "exp": 54,
        "catchRate": 200,
        "evolutions": [new LevelEvolution("Surskit", "Masquerain", 22)],
    }, {
        "id": 284,
        "name": "Masquerain",
        "type": ["Bug", "Flying"],
        "attack": 100,
        "eggCycles": 15,
        "levelType": "mediumfast",
        "exp": 159,
        "catchRate": 75
    }, {
        "id": 285,
        "name": "Shroomish",
        "type": ["Grass"],
        "attack": 60,
        "eggCycles": 15,
        "levelType": "fluctuating",
        "exp": 59,
        "catchRate": 255,
        "evolutions": [new LevelEvolution("Shroomish", "Breloom", 23)],
    }, {
        "id": 286,
        "name": "Breloom",
        "type": ["Grass", "Fighting"],
        "attack": 130,
        "eggCycles": 15,
        "levelType": "fluctuating",
        "exp": 161,
        "catchRate": 90
    }, {
        "id": 287,
        "name": "Slakoth",
        "type": ["Normal"],
        "attack": 60,
        "eggCycles": 15,
        "levelType": "slow",
        "exp": 56,
        "catchRate": 255,
        "evolutions": [new LevelEvolution("Slakoth", "Vigoroth", 18)],
    }, {
        "id": 288,
        "name": "Vigoroth",
        "type": ["Normal"],
        "attack": 90,
        "eggCycles": 15,
        "levelType": "slow",
        "exp": 154,
        "catchRate": 120,
        "evolutions": [new LevelEvolution("Vigoroth", "Slaking", 36)],
    }, {
        "id": 289,
        "name": "Slaking",
        "type": ["Normal"],
        "attack": 160,
        "eggCycles": 15,
        "levelType": "slow",
        "exp": 252,
        "catchRate": 45
    }, {
        "id": 290,
        "name": "Nincada",
        "type": ["Bug", "Ground"],
        "attack": 90,
        "eggCycles": 15,
        "levelType": "erratic",
        "exp": 53,
        "catchRate": 255,
        "evolutions": [new LevelEvolution("Nincada", "Ninjask", 20)],
    }, {
        "id": 291,
        "name": "Ninjask",
        "type": ["Bug", "Flying"],
        "attack": 160,
        "eggCycles": 15,
        "levelType": "erratic",
        "exp": 160,
        "catchRate": 120
    }, {
        "id": 292,
        "name": "Shedinja",
        "type": ["Bug", "Ghost"],
        "attack": 90,
        "eggCycles": 15,
        "levelType": "erratic",
        "exp": 83,
        "catchRate": 45
    }, {
        "id": 293,
        "name": "Whismur",
        "type": ["Normal"],
        "attack": 64,
        "eggCycles": 20,
        "levelType": "mediumslow",
        "exp": 48,
        "catchRate": 190,
        "evolutions": [new LevelEvolution("Whismur", "Loudred", 20)],
    }, {
        "id": 294,
        "name": "Loudred",
        "type": ["Normal"],
        "attack": 84,
        "eggCycles": 20,
        "levelType": "mediumslow",
        "exp": 126,
        "catchRate": 120,
        "evolutions": [new LevelEvolution("Loudred", "Exploud", 40)],
    }, {
        "id": 295,
        "name": "Exploud",
        "type": ["Normal"],
        "attack": 104,
        "eggCycles": 20,
        "levelType": "mediumslow",
        "exp": 221,
        "catchRate": 45
    }, {
        "id": 296,
        "name": "Makuhita",
        "type": ["Fighting"],
        "attack": 72,
        "eggCycles": 20,
        "levelType": "fluctuating",
        "exp": 47,
        "catchRate": 180,
        "evolutions": [new LevelEvolution("Makuhita", "Hariyama", 24)],
    }, {
        "id": 297,
        "name": "Hariyama",
        "type": ["Fighting"],
        "attack": 144,
        "eggCycles": 20,
        "levelType": "fluctuating",
        "exp": 166,
        "catchRate": 200
    }, {
        "id": 298,
        "name": "Azurill",
        "type": ["Normal", "Fairy"],
        "attack": 50,
        "eggCycles": 10,
        "levelType": "fast",
        "exp": 38,
        "catchRate": 150,
        "evolutions": [new LevelEvolution("Azurill", "Marill", 100)],
    }, {
        "id": 299,
        "name": "Nosepass",
        "type": ["Rock"],
        "attack": 135,
        "eggCycles": 20,
        "levelType": "mediumfast",
        "exp": 75,
        "catchRate": 255,
    }, {
        "id": 300,
        "name": "Skitty",
        "type": ["Normal"],
        "attack": 50,
        "eggCycles": 15,
        "levelType": "fast",
        "exp": 52,
        "catchRate": 255,
        "evolutions": [new StoneEvolution("Skitty", "Delcatty", GameConstants.StoneType.Moon_stone)],
    }, {
        "id": 301,
        "name": "Delcatty",
        "type": ["Normal"],
        "attack": 90,
        "eggCycles": 15,
        "levelType": "fast",
        "exp": 140,
        "catchRate": 60
    }, {
        "id": 302,
        "name": "Sableye",
        "type": ["Dark", "Ghost"],
        "attack": 75,
        "eggCycles": 25,
        "levelType": "mediumslow",
        "exp": 133,
        "catchRate": 45
    }, {
        "id": 303,
        "name": "Mawile",
        "type": ["Steel", "Fairy"],
        "attack": 85,
        "eggCycles": 20,
        "levelType": "fast",
        "exp": 133,
        "catchRate": 45
    }, {
        "id": 304,
        "name": "Aron",
        "type": ["Steel", "Rock"],
        "attack": 100,
        "eggCycles": 35,
        "levelType": "slow",
        "exp": 66,
        "catchRate": 180,
        "evolutions": [new LevelEvolution("Aron", "Lairon", 32)],
    }, {
        "id": 305,
        "name": "Lairon",
        "type": ["Steel", "Rock"],
        "attack": 140,
        "eggCycles": 35,
        "levelType": "slow",
        "exp": 151,
        "catchRate": 90,
        "evolutions": [new LevelEvolution("Lairon", "Aggron", 42)],
    }, {
        "id": 306,
        "name": "Aggron",
        "type": ["Steel", "Rock"],
        "attack": 180,
        "eggCycles": 35,
        "levelType": "slow",
        "exp": 239,
        "catchRate": 45
    }, {
        "id": 307,
        "name": "Meditite",
        "type": ["Fighting", "Psychic"],
        "attack": 60,
        "eggCycles": 20,
        "levelType": "mediumfast",
        "exp": 56,
        "catchRate": 180,
        "evolutions": [new LevelEvolution("Meditite", "Medicham", 37)],
    }, {
        "id": 308,
        "name": "Medicham",
        "type": ["Fighting", "Psychic"],
        "attack": 80,
        "eggCycles": 20,
        "levelType": "mediumfast",
        "exp": 144,
        "catchRate": 90
    }, {
        "id": 309,
        "name": "Electrike",
        "type": ["Electric"],
        "attack": 65,
        "eggCycles": 20,
        "levelType": "slow",
        "exp": 59,
        "catchRate": 120,
        "evolutions": [new LevelEvolution("Electrike", "Manectric", 26)],
    }, {
        "id": 310,
        "name": "Manectric",
        "type": ["Electric"],
        "attack": 105,
        "eggCycles": 20,
        "levelType": "slow",
        "exp": 166,
        "catchRate": 45
    }, {
        "id": 311,
        "name": "Plusle",
        "type": ["Electric"],
        "attack": 95,
        "eggCycles": 20,
        "levelType": "mediumfast",
        "exp": 142,
        "catchRate": 200
    }, {
        "id": 312,
        "name": "Minun",
        "type": ["Electric"],
        "attack": 95,
        "eggCycles": 20,
        "levelType": "mediumfast",
        "exp": 142,
        "catchRate": 200
    }, {
        "id": 313,
        "name": "Volbeat",
        "type": ["Bug"],
        "attack": 85,
        "eggCycles": 15,
        "levelType": "erratic",
        "exp": 151,
        "catchRate": 150
    }, {
        "id": 314,
        "name": "Illumise",
        "type": ["Bug"],
        "attack": 85,
        "eggCycles": 15,
        "levelType": "fluctuating",
        "exp": 151,
        "catchRate": 150
    }, {
        "id": 315,
        "name": "Roselia",
        "type": ["Grass", "Poison"],
        "attack": 100,
        "eggCycles": 20,
        "levelType": "mediumslow",
        "exp": 140,
        "catchRate": 150,
    }, {
        "id": 316,
        "name": "Gulpin",
        "type": ["Poison"],
        "attack": 70,
        "eggCycles": 20,
        "levelType": "fluctuating",
        "exp": 60,
        "catchRate": 225,
        "evolutions": [new LevelEvolution("Gulpin", "Swalot", 26)],
    }, {
        "id": 317,
        "name": "Swalot",
        "type": ["Poison"],
        "attack": 100,
        "eggCycles": 20,
        "levelType": "fluctuating",
        "exp": 163,
        "catchRate": 75
    }, {
        "id": 318,
        "name": "Carvanha",
        "type": ["Water", "Dark"],
        "attack": 90,
        "eggCycles": 20,
        "levelType": "slow",
        "exp": 61,
        "catchRate": 225,
        "evolutions": [new LevelEvolution("Carvanha", "Sharpedo", 30)],
    }, {
        "id": 319,
        "name": "Sharpedo",
        "type": ["Water", "Dark"],
        "attack": 120,
        "eggCycles": 20,
        "levelType": "slow",
        "exp": 161,
        "catchRate": 60
    }, {
        "id": 320,
        "name": "Wailmer",
        "type": ["Water"],
        "attack": 130,
        "eggCycles": 40,
        "levelType": "fluctuating",
        "exp": 80,
        "catchRate": 125,
        "evolutions": [new LevelEvolution("Wailmer", "Wailord", 40)],
    }, {
        "id": 321,
        "name": "Wailord",
        "type": ["Water"],
        "attack": 170,
        "eggCycles": 40,
        "levelType": "fluctuating",
        "exp": 175,
        "catchRate": 60
    }, {
        "id": 322,
        "name": "Numel",
        "type": ["Fire", "Ground"],
        "attack": 65,
        "eggCycles": 20,
        "levelType": "mediumfast",
        "exp": 61,
        "catchRate": 255,
        "evolutions": [new LevelEvolution("Numel", "Camerupt", 33)],
    }, {
        "id": 323,
        "name": "Camerupt",
        "type": ["Fire", "Ground"],
        "attack": 105,
        "eggCycles": 20,
        "levelType": "mediumfast",
        "exp": 161,
        "catchRate": 150
    }, {
        "id": 324,
        "name": "Torkoal",
        "type": ["Fire"],
        "attack": 140,
        "eggCycles": 20,
        "levelType": "mediumfast",
        "exp": 165,
        "catchRate": 90
    }, {
        "id": 325,
        "name": "Spoink",
        "type": ["Psychic"],
        "attack": 80,
        "eggCycles": 20,
        "levelType": "fast",
        "exp": 66,
        "catchRate": 255,
        "evolutions": [new LevelEvolution("Spoink", "Grumpig", 32)],
    }, {
        "id": 326,
        "name": "Grumpig",
        "type": ["Psychic"],
        "attack": 110,
        "eggCycles": 20,
        "levelType": "fast",
        "exp": 165,
        "catchRate": 60
    }, {
        "id": 327,
        "name": "Spinda",
        "type": ["Normal"],
        "attack": 60,
        "eggCycles": 15,
        "levelType": "fast",
        "exp": 126,
        "catchRate": 255
    }, {
        "id": 328,
        "name": "Trapinch",
        "type": ["Ground"],
        "attack": 100,
        "eggCycles": 20,
        "levelType": "mediumslow",
        "exp": 58,
        "catchRate": 255,
        "evolutions": [new LevelEvolution("Trapinch", "Vibrava", 35)],
    }, {
        "id": 329,
        "name": "Vibrava",
        "type": ["Ground", "Dragon"],
        "attack": 70,
        "eggCycles": 20,
        "levelType": "mediumslow",
        "exp": 119,
        "catchRate": 120,
        "evolutions": [new LevelEvolution("Vibrava", "Flygon", 45)],
    }, {
        "id": 330,
        "name": "Flygon",
        "type": ["Ground", "Dragon"],
        "attack": 100,
        "eggCycles": 20,
        "levelType": "mediumslow",
        "exp": 234,
        "catchRate": 45
    }, {
        "id": 331,
        "name": "Cacnea",
        "type": ["Grass"],
        "attack": 85,
        "eggCycles": 20,
        "levelType": "mediumslow",
        "exp": 67,
        "catchRate": 190,
        "evolutions": [new LevelEvolution("Cacnea", "Cacturne", 32)],
    }, {
        "id": 332,
        "name": "Cacturne",
        "type": ["Grass", "Dark"],
        "attack": 115,
        "eggCycles": 20,
        "levelType": "mediumslow",
        "exp": 166,
        "catchRate": 60
    }, {
        "id": 333,
        "name": "Swablu",
        "type": ["Normal", "Flying"],
        "attack": 75,
        "eggCycles": 20,
        "levelType": "erratic",
        "exp": 62,
        "catchRate": 255,
        "evolutions": [new LevelEvolution("Swablu", "Altaria", 35)],
    }, {
        "id": 334,
        "name": "Altaria",
        "type": ["Dragon", "Flying"],
        "attack": 105,
        "eggCycles": 20,
        "levelType": "erratic",
        "exp": 172,
        "catchRate": 45
    }, {
        "id": 335,
        "name": "Zangoose",
        "type": ["Normal"],
        "attack": 115,
        "eggCycles": 20,
        "levelType": "erratic",
        "exp": 160,
        "catchRate": 90
    }, {
        "id": 336,
        "name": "Seviper",
        "type": ["Poison"],
        "attack": 100,
        "eggCycles": 20,
        "levelType": "fluctuating",
        "exp": 160,
        "catchRate": 90
    }, {
        "id": 337,
        "name": "Lunatone",
        "type": ["Rock", "Psychic"],
        "attack": 95,
        "eggCycles": 25,
        "levelType": "fast",
        "exp": 161,
        "catchRate": 45
    }, {
        "id": 338,
        "name": "Solrock",
        "type": ["Rock", "Psychic"],
        "attack": 95,
        "eggCycles": 25,
        "levelType": "fast",
        "exp": 161,
        "catchRate": 45
    }, {
        "id": 339,
        "name": "Barboach",
        "type": ["Water", "Ground"],
        "attack": 60,
        "eggCycles": 20,
        "levelType": "mediumfast",
        "exp": 58,
        "catchRate": 190,
        "evolutions": [new LevelEvolution("Barboach", "Whiscash", 30)],
    }, {
        "id": 340,
        "name": "Whiscash",
        "type": ["Water", "Ground"],
        "attack": 110,
        "eggCycles": 20,
        "levelType": "mediumfast",
        "exp": 164,
        "catchRate": 75
    }, {
        "id": 341,
        "name": "Corphish",
        "type": ["Water"],
        "attack": 80,
        "eggCycles": 15,
        "levelType": "fluctuating",
        "exp": 62,
        "catchRate": 205,
        "evolutions": [new LevelEvolution("Corphish", "Crawdaunt", 30)],
    }, {
        "id": 342,
        "name": "Crawdaunt",
        "type": ["Water", "Dark"],
        "attack": 120,
        "eggCycles": 15,
        "levelType": "fluctuating",
        "exp": 164,
        "catchRate": 155
    }, {
        "id": 343,
        "name": "Baltoy",
        "type": ["Ground", "Psychic"],
        "attack": 70,
        "eggCycles": 20,
        "levelType": "mediumfast",
        "exp": 60,
        "catchRate": 255,
        "evolutions": [new LevelEvolution("Baltoy", "Claydol", 36)],
    }, {
        "id": 344,
        "name": "Claydol",
        "type": ["Ground", "Psychic"],
        "attack": 120,
        "eggCycles": 20,
        "levelType": "mediumfast",
        "exp": 175,
        "catchRate": 90
    }, {
        "id": 345,
        "name": "Lileep",
        "type": ["Rock", "Grass"],
        "attack": 87,
        "eggCycles": 30,
        "levelType": "erratic",
        "exp": 71,
        "catchRate": 45,
        "evolutions": [new LevelEvolution("Lileep", "Cradily", 40)],
    }, {
        "id": 346,
        "name": "Cradily",
        "type": ["Rock", "Grass"],
        "attack": 107,
        "eggCycles": 30,
        "levelType": "erratic",
        "exp": 173,
        "catchRate": 45
    }, {
        "id": 347,
        "name": "Anorith",
        "type": ["Rock", "Bug"],
        "attack": 95,
        "eggCycles": 30,
        "levelType": "erratic",
        "exp": 71,
        "catchRate": 45,
        "evolutions": [new LevelEvolution("Anorith", "Armaldo", 40)],
    }, {
        "id": 348,
        "name": "Armaldo",
        "type": ["Rock", "Bug"],
        "attack": 125,
        "eggCycles": 30,
        "levelType": "erratic",
        "exp": 173,
        "catchRate": 45
    }, {
        "id": 349,
        "name": "Feebas",
        "type": ["Water"],
        "attack": 80,
        "eggCycles": 20,
        "levelType": "erratic",
        "exp": 40,
        "catchRate": 255,
        "evolutions": [new StoneEvolution("Feebas", "Milotic", GameConstants.StoneType.Trade_stone)],
    }, {
        "id": 350,
        "name": "Milotic",
        "type": ["Water"],
        "attack": 125,
        "eggCycles": 20,
        "levelType": "erratic",
        "exp": 189,
        "catchRate": 60
    }, {
        "id": 351,
        "name": "Castform",
        "type": ["Normal"],
        "attack": 70,
        "eggCycles": 25,
        "levelType": "mediumfast",
        "exp": 147,
        "catchRate": 45
    }, {
        "id": 352,
        "name": "Kecleon",
        "type": ["Normal"],
        "attack": 120,
        "eggCycles": 20,
        "levelType": "mediumslow",
        "exp": 154,
        "catchRate": 200
    }, {
        "id": 353,
        "name": "Shuppet",
        "type": ["Ghost"],
        "attack": 75,
        "eggCycles": 25,
        "levelType": "fast",
        "exp": 59,
        "catchRate": 225,
        "evolutions": [new LevelEvolution("Shuppet", "Banette", 37)],
    }, {
        "id": 354,
        "name": "Banette",
        "type": ["Ghost"],
        "attack": 115,
        "eggCycles": 25,
        "levelType": "fast",
        "exp": 159,
        "catchRate": 45
    }, {
        "id": 355,
        "name": "Duskull",
        "type": ["Ghost"],
        "attack": 90,
        "eggCycles": 25,
        "levelType": "fast",
        "exp": 59,
        "catchRate": 190,
        "evolutions": [new LevelEvolution("Duskull", "Dusclops", 37)],
    }, {
        "id": 356,
        "name": "Dusclops",
        "type": ["Ghost"],
        "attack": 130,
        "eggCycles": 25,
        "levelType": "fast",
        "exp": 159,
        "catchRate": 90,
    }, {
        "id": 357,
        "name": "Tropius",
        "type": ["Grass", "Flying"],
        "attack": 99,
        "eggCycles": 25,
        "levelType": "slow",
        "exp": 161,
        "catchRate": 200
    }, {
        "id": 358,
        "name": "Chimecho",
        "type": ["Psychic"],
        "attack": 95,
        "eggCycles": 25,
        "levelType": "fast",
        "exp": 159,
        "catchRate": 45
    }, {
        "id": 359,
        "name": "Absol",
        "type": ["Dark"],
        "attack": 130,
        "eggCycles": 25,
        "levelType": "mediumslow",
        "exp": 163,
        "catchRate": 30
    }, {
        "id": 360,
        "name": "Wynaut",
        "type": ["Psychic"],
        "attack": 95,
        "eggCycles": 20,
        "levelType": "mediumfast",
        "exp": 52,
        "catchRate": 125,
        "evolutions": [new LevelEvolution("Wynaut", "Wobbuffet", 15)],
    }, {
        "id": 361,
        "name": "Snorunt",
        "type": ["Ice"],
        "attack": 50,
        "eggCycles": 20,
        "levelType": "mediumfast",
        "exp": 60,
        "catchRate": 190,
        "evolutions": [new LevelEvolution("Snorunt", "Glalie", 42)],
    }, {
        "id": 362,
        "name": "Glalie",
        "type": ["Ice"],
        "attack": 80,
        "eggCycles": 20,
        "levelType": "mediumfast",
        "exp": 168,
        "catchRate": 75
    }, {
        "id": 363,
        "name": "Spheal",
        "type": ["Ice", "Water"],
        "attack": 70,
        "eggCycles": 20,
        "levelType": "mediumslow",
        "exp": 58,
        "catchRate": 255,
        "evolutions": [new LevelEvolution("Spheal", "Sealeo", 32)],
    }, {
        "id": 364,
        "name": "Sealeo",
        "type": ["Ice", "Water"],
        "attack": 90,
        "eggCycles": 20,
        "levelType": "mediumslow",
        "exp": 144,
        "catchRate": 120,
        "evolutions": [new LevelEvolution("Sealeo", "Walrein", 44)],
    }, {
        "id": 365,
        "name": "Walrein",
        "type": ["Ice", "Water"],
        "attack": 110,
        "eggCycles": 20,
        "levelType": "mediumslow",
        "exp": 239,
        "catchRate": 45
    }, {
        "id": 366,
        "name": "Clamperl",
        "type": ["Water"],
        "attack": 85,
        "eggCycles": 20,
        "levelType": "erratic",
        "exp": 69,
        "catchRate": 255,
        "evolutions": [new StoneEvolution("Clamperl", "Huntail", GameConstants.StoneType.Trade_stone)],
    }, {
        "id": 367,
        "name": "Huntail",
        "type": ["Water"],
        "attack": 105,
        "eggCycles": 20,
        "levelType": "erratic",
        "exp": 170,
        "catchRate": 60
    }, {
        "id": 368,
        "name": "Gorebyss",
        "type": ["Water"],
        "attack": 114,
        "eggCycles": 20,
        "levelType": "erratic",
        "exp": 170,
        "catchRate": 60
    }, {
        "id": 369,
        "name": "Relicanth",
        "type": ["Water", "Rock"],
        "attack": 130,
        "eggCycles": 40,
        "levelType": "slow",
        "exp": 170,
        "catchRate": 25
    }, {
        "id": 370,
        "name": "Luvdisc",
        "type": ["Water"],
        "attack": 97,
        "eggCycles": 20,
        "levelType": "fast",
        "exp": 116,
        "catchRate": 225
    }, {
        "id": 371,
        "name": "Bagon",
        "type": ["Dragon"],
        "attack": 75,
        "eggCycles": 40,
        "levelType": "slow",
        "exp": 60,
        "catchRate": 45,
        "evolutions": [new LevelEvolution("Bagon", "Shelgon", 30)],
    }, {
        "id": 372,
        "name": "Shelgon",
        "type": ["Dragon"],
        "attack": 100,
        "eggCycles": 40,
        "levelType": "slow",
        "exp": 147,
        "catchRate": 45,
        "evolutions": [new LevelEvolution("Shelgon", "Salamence", 50)],
    }, {
        "id": 373,
        "name": "Salamence",
        "type": ["Dragon", "Flying"],
        "attack": 135,
        "eggCycles": 40,
        "levelType": "slow",
        "exp": 270,
        "catchRate": 45
    }, {
        "id": 374,
        "name": "Beldum",
        "type": ["Steel", "Psychic"],
        "attack": 80,
        "eggCycles": 40,
        "levelType": "slow",
        "exp": 60,
        "catchRate": 3,
        "evolutions": [new LevelEvolution("Beldum", "Metang", 20)],
    }, {
        "id": 375,
        "name": "Metang",
        "type": ["Steel", "Psychic"],
        "attack": 100,
        "eggCycles": 40,
        "levelType": "slow",
        "exp": 147,
        "catchRate": 3,
        "evolutions": [new LevelEvolution("Metang", "Metagross", 45)],
    }, {
        "id": 376,
        "name": "Metagross",
        "type": ["Steel", "Psychic"],
        "attack": 135,
        "eggCycles": 40,
        "levelType": "slow",
        "exp": 270,
        "catchRate": 3
    }, {
        "id": 377,
        "name": "Regirock",
        "type": ["Rock"],
        "attack": 200,
        "eggCycles": 80,
        "levelType": "slow",
        "exp": 261,
        "catchRate": 3
    }, {
        "id": 378,
        "name": "Regice",
        "type": ["Ice"],
        "attack": 200,
        "eggCycles": 80,
        "levelType": "slow",
        "exp": 261,
        "catchRate": 3
    }, {
        "id": 379,
        "name": "Registeel",
        "type": ["Steel"],
        "attack": 150,
        "eggCycles": 80,
        "levelType": "slow",
        "exp": 261,
        "catchRate": 3
    }, {
        "id": 380,
        "name": "Latias",
        "type": ["Dragon", "Psychic"],
        "attack": 130,
        "eggCycles": 120,
        "levelType": "slow",
        "exp": 270,
        "catchRate": 3
    }, {
        "id": 381,
        "name": "Latios",
        "type": ["Dragon", "Psychic"],
        "attack": 130,
        "eggCycles": 120,
        "levelType": "slow",
        "exp": 270,
        "catchRate": 3
    }, {
        "id": 382,
        "name": "Kyogre",
        "type": ["Water"],
        "attack": 150,
        "eggCycles": 120,
        "levelType": "slow",
        "exp": 302,
        "catchRate": 3
    }, {
        "id": 383,
        "name": "Groudon",
        "type": ["Ground"],
        "attack": 150,
        "eggCycles": 120,
        "levelType": "slow",
        "exp": 302,
        "catchRate": 3
    }, {
        "id": 384,
        "name": "Rayquaza",
        "type": ["Dragon", "Flying"],
        "attack": 150,
        "eggCycles": 120,
        "levelType": "slow",
        "exp": 306,
        "catchRate": 45
    }, {
        "id": 385,
        "name": "Jirachi",
        "type": ["Steel", "Psychic"],
        "attack": 100,
        "eggCycles": 120,
        "levelType": "slow",
        "exp": 270,
        "catchRate": 3
    }, {
        "id": 386,
        "name": "Deoxys\nNormal Forme",
        "type": ["Psychic"],
        "attack": 150,
        "eggCycles": 120,
        "levelType": "slow",
        "exp": 270,
        "catchRate": 3
    }];


// TODO move to its own initialize method that gets called on game start.
pokemonList.forEach(p => {
    if (p.evolution) {
        if (p.evolution.constructor !== Array) {
            p.evolution = [p.evolution];
        }
        p.evolution.forEach(evo => pokemonDevolutionMap[evo] = p.name);
    }
    if (p.evoLevel && p.evoLevel.constructor !== Array) {
        p.evoLevel = [p.evoLevel];
    }
    pokemonMap[p.name] = p;
    pokemonMapId[p.id] = p;
});
