import Changelog, { changelogType } from './Changelog';
import ChangelogUpdate from './ChangelogUpdate';

/**
 * Add your changes to the top of the changelog. Please do not increase the version number.
 *
 * MAJOR - Will stay at 0 during development, 1 after the first public release
 * MINOR - Will increment for each feature refactor or large changes to a feature
 * PATCH - Increment for small changes, bugfixes, UI changes.
 */
const ChangelogItems = [
    // note that month is 0 indexed
    // v0.10.4
    new ChangelogUpdate('v0.10.4', new Date(2022, 10, 22)),
    new Changelog(changelogType.CHANGE, 'Shop Magikarp no longer awards EVs'),
    new Changelog(changelogType.CHANGE, 'Base wandering Pokémon no longer award EVs'),
    new Changelog(changelogType.CHANGE, 'Misc text changes'),
    new Changelog(changelogType.CHANGE, 'Misc UI changes'),
    new Changelog(changelogType.CHANGE, 'Misc image changes'),
    new Changelog(changelogType.FIXED, 'Starter not gaining Pokérus status'),
    new Changelog(changelogType.FIXED, 'Game not loading in special instances when you are at particular quest steps'),
    new Changelog(changelogType.FIXED, 'Potential script execution exploit - Remember to only import trusted save files'),

    // v0.10.3
    new ChangelogUpdate('v0.10.3', new Date(2022, 10, 20)),
    new Changelog(changelogType.CHANGE, 'Misc text changes'),
    new Changelog(changelogType.FIXED, 'Some questline steps causing players to be stuck'),
    new Changelog(changelogType.FIXED, 'Real evolution challenge mode'),
    new Changelog(changelogType.FIXED, 'Shard quests not updating in specific instances'),

    // v0.10.2
    new ChangelogUpdate('v0.10.2', new Date(2022, 10, 19)),
    new Changelog(changelogType.NEW, 'Kecleon overworld battles added'),
    new Changelog(changelogType.NEW, 'New Challenge mode added'),
    new Changelog(changelogType.NEW, 'Translations for some game componenets'),
    new Changelog(changelogType.NEW, 'Desktop Client exclusive Pokémon'),
    new Changelog(changelogType.NEW, 'Able to nickname Pokémon'),
    new Changelog(changelogType.NEW, 'More offline progress rewards added'),
    new Changelog(changelogType.NEW, 'Some mega evolutions are now available'),
    new Changelog(changelogType.NEW, 'Meltan questline'),
    new Changelog(changelogType.NEW, 'Giratina questline'),
    new Changelog(changelogType.NEW, 'Rival battles'),
    new Changelog(changelogType.CHANGE, 'Adjusted click attack calculations'),
    new Changelog(changelogType.CHANGE, 'Adjusted Kalos Elite Four'),
    new Changelog(changelogType.CHANGE, 'EV bonus now taken into account for Breeding Effeciency sorting'),
    new Changelog(changelogType.CHANGE, 'Removed guaranteed Unown (A) from Ruins of Alph'),
    new Changelog(changelogType.CHANGE, 'Adjusted some Pokémon teams'),
    new Changelog(changelogType.CHANGE, 'Adjusted some Pokémon encounter locations'),
    new Changelog(changelogType.CHANGE, 'Misc text changes'),
    new Changelog(changelogType.CHANGE, 'Misc UI changes'),
    new Changelog(changelogType.CHANGE, 'Misc image changes'),
    new Changelog(changelogType.FIXED, 'Reduced some lag caused by achievements'),

    // v0.10.1
    new ChangelogUpdate('v0.10.1', new Date(2022, 9, 31)),
    new Changelog(changelogType.NEW, 'Spooky Togepi evolution line'),
    new Changelog(changelogType.CHANGE, 'Increased chance of undiscovered fossils appearing in the Underground'),
    new Changelog(changelogType.CHANGE, 'Adjusted held item drop locations'),
    new Changelog(changelogType.CHANGE, 'Adjusted battle café spins per day'),
    new Changelog(changelogType.CHANGE, 'More profile options'),
    new Changelog(changelogType.CHANGE, 'Misc text changes'),
    new Changelog(changelogType.CHANGE, 'Misc UI changes'),
    new Changelog(changelogType.CHANGE, 'Misc image changes'),
    new Changelog(changelogType.FIXED, 'Some people not being able to create a new save'),

    // v0.10.0
    new ChangelogUpdate('v0.10.0 - Galar', new Date(2022, 9, 22)),
    new Changelog(changelogType.NEW, 'The Galar region is now available'),
    new Changelog(changelogType.NEW, 'Farm Point hatchery helper added'),
    new Changelog(changelogType.NEW, 'More questlines'),
    new Changelog(changelogType.NEW, 'More held items'),
    new Changelog(changelogType.NEW, 'Pokémon now have genders'),
    new Changelog(changelogType.NEW, 'Routes and dungeons now show the EV status of all encounters'),
    new Changelog(changelogType.CHANGE, 'Battle Frontier reward Pokémon now have a chance to be shiny'),
    new Changelog(changelogType.CHANGE, 'Adjusted shard prices'),
    new Changelog(changelogType.CHANGE, 'Adjusted farm wanderers'),
    new Changelog(changelogType.CHANGE, 'Misc text changes'),
    new Changelog(changelogType.CHANGE, 'Misc UI changes'),
    new Changelog(changelogType.CHANGE, 'Misc image changes'),
    new Changelog(changelogType.FIXED, 'Town to be sent to after snorlax and sudowoodo battles'),

    // v0.9.18
    new ChangelogUpdate('v0.9.18', new Date(2022, 9, 10)),
    new Changelog(changelogType.FIXED, 'Some saves not being able to update to v0.9.17'),

    // v0.9.17
    new ChangelogUpdate('v0.9.17', new Date(2022, 9, 10)),
    new Changelog(changelogType.NEW, 'Held items [BETA]'),
    new Changelog(changelogType.NEW, 'Sudowoodo overworld battles added'),
    new Changelog(changelogType.NEW, 'Sevii now has it\'s own achievement pool'),
    new Changelog(changelogType.NEW, 'Dungeon floors added for dungeons of size 10 or bigger'),
    new Changelog(changelogType.CHANGE, 'Updated Kalos route 1 encounters'),
    new Changelog(changelogType.CHANGE, 'Hoenn badge requirement ordering'),
    new Changelog(changelogType.CHANGE, 'Updated typed egg pools'),
    new Changelog(changelogType.CHANGE, 'Caught indicator for berry deals'),
    new Changelog(changelogType.CHANGE, 'Dungeon Token flute now helps with EVs instead'),
    new Changelog(changelogType.CHANGE, 'Farm hands will no longer attempt to place berries you do not have'),
    new Changelog(changelogType.CHANGE, 'Global achievement bonus increased to 150%'),
    new Changelog(changelogType.CHANGE, 'Improved Hatchery and Pokédex loading times'),
    new Changelog(changelogType.CHANGE, 'Adjusted Underground layer generation'),
    new Changelog(changelogType.CHANGE, 'Misc text changes'),
    new Changelog(changelogType.CHANGE, 'Misc UI changes'),
    new Changelog(changelogType.CHANGE, 'Misc image changes'),
    new Changelog(changelogType.FIXED, 'Enigma will now show the full hint once unlocked'),
    new Changelog(changelogType.FIXED, 'Diancie Questline requirements'),
    new Changelog(changelogType.FIXED, 'Farm aura calculations'),
    new Changelog(changelogType.FIXED, 'Pokérus spreading between helpers'),

    // v0.9.16
    new ChangelogUpdate('v0.9.16', new Date(2022, 8, 21)),
    new Changelog(changelogType.NEW, 'New Furfrou form added'),
    new Changelog(changelogType.CHANGE, 'Buffed Pinkan berry harvest rate'),
    new Changelog(changelogType.CHANGE, 'Misc text changes'),
    new Changelog(changelogType.CHANGE, 'Misc UI changes'),
    new Changelog(changelogType.CHANGE, 'Misc image changes'),
    new Changelog(changelogType.CHANGE, 'Added a Dock to Seafolk Village'),
    new Changelog(changelogType.CHANGE, 'Re-adjusted when hatchery sounds play'),
    new Changelog(changelogType.FIXED, 'Fix farm harvested statistics'),
    new Changelog(changelogType.FIXED, 'Master Farmer achievement'),

    // v0.9.15
    new ChangelogUpdate('v0.9.15', new Date(2022, 8, 20)),
    new Changelog(changelogType.NEW, 'More Pokémon forms added'),
    new Changelog(changelogType.NEW, 'More one off battles added'),
    new Changelog(changelogType.NEW, 'New questlines'),
    new Changelog(changelogType.NEW, 'New setting added for quest modal'),
    new Changelog(changelogType.NEW, 'Hatchery size settings'),
    new Changelog(changelogType.NEW, 'Updated Alola maps'),
    new Changelog(changelogType.NEW, 'Added Pinkan berry'),
    new Changelog(changelogType.CHANGE, 'Unova, Kalos and Alola Elite 4 can now be challenged in any order'),
    new Changelog(changelogType.CHANGE, 'Misc text changes'),
    new Changelog(changelogType.CHANGE, 'Misc UI changes'),
    new Changelog(changelogType.CHANGE, 'Misc map changes'),
    new Changelog(changelogType.CHANGE, 'Misc Pokémon stats updated'),
    new Changelog(changelogType.CHANGE, 'Misc NPC changes'),
    new Changelog(changelogType.CHANGE, 'Improved load times for Pokédex and Hatchery'),
    new Changelog(changelogType.FIXED, 'Harvest rates for berries with a 0.5 harvest rate'),
    new Changelog(changelogType.FIXED, 'Farm hands not remembering to focus Cheri berries'),
    new Changelog(changelogType.FIXED, 'Farm hands not ignoring locked plots'),
    new Changelog(changelogType.FIXED, 'Discord login should be more consistent'),
    new Changelog(changelogType.FIXED, 'Fixed disappearing Pokémon bug for most players'),
    new Changelog(changelogType.FIXED, 'Buying multiple Pokémon at the shop now applies the correct amount of EVs'),

    // v0.9.14
    new ChangelogUpdate('v0.9.14', new Date(2022, 8, 2)),
    new Changelog(changelogType.CHANGE, 'Pinkan Dodrio is now purchasable in place of Pinkan Exeggutor'),
    new Changelog(changelogType.CHANGE, 'Misc text changes'),
    new Changelog(changelogType.CHANGE, 'Misc Pokémon stats updated'),
    new Changelog(changelogType.FIXED, 'Sevii island fixes'),
    new Changelog(changelogType.FIXED, 'Alola islands being inaccessible for some people'),
    new Changelog(changelogType.FIXED, 'Questline requirements'),
    new Changelog(changelogType.FIXED, 'All badges now displayed in badge case when available'),

    // v0.9.13
    new ChangelogUpdate('v0.9.13', new Date(2022, 8, 1)),
    new Changelog(changelogType.NEW, 'Sevii islands 4, 5, 6 and 7'),
    new Changelog(changelogType.NEW, 'Sevii questline'),
    new Changelog(changelogType.NEW, 'Detective Pikachu questline'),
    new Changelog(changelogType.CHANGE, 'Adjusted Team Plasma questline'),
    new Changelog(changelogType.CHANGE, 'Adjusted Underground item sorting'),
    new Changelog(changelogType.CHANGE, 'Misc text changes'),
    new Changelog(changelogType.CHANGE, 'Misc UI changes'),
    new Changelog(changelogType.CHANGE, 'Misc NPC changes'),

    // v0.9.12
    new ChangelogUpdate('v0.9.12', new Date(2022, 7, 18)),
    new Changelog(changelogType.FIXED, 'Revert regional update'),

    // v0.9.11
    new ChangelogUpdate('v0.9.11', new Date(2022, 7, 18)),
    new Changelog(changelogType.NEW, 'Celebi questline'),
    new Changelog(changelogType.NEW, 'Added ability to lock plots in the farm'),
    new Changelog(changelogType.NEW, 'Bulletin Board, With misc quests available'),
    new Changelog(changelogType.CHANGE, 'More Battle Frontier rewards'),
    new Changelog(changelogType.CHANGE, 'Misc text changes'),
    new Changelog(changelogType.CHANGE, 'Misc UI changes'),
    new Changelog(changelogType.CHANGE, 'Misc NPC changes'),
    new Changelog(changelogType.FIXED, 'Pokérus status not visually updating in the hatchery'),
    new Changelog(changelogType.FIXED, 'Multi quest progression'),

    // v0.9.10
    new ChangelogUpdate('v0.9.10', new Date(2022, 7, 3)),
    new Changelog(changelogType.NEW, 'Added Furfrou (star)'),
    new Changelog(changelogType.CHANGE, 'Misc text changes'),
    new Changelog(changelogType.CHANGE, 'Misc UI changes'),
    new Changelog(changelogType.CHANGE, 'Misc NPC changes'),
    new Changelog(changelogType.FIXED, 'Underground survey now shows shards'),
    new Changelog(changelogType.FIXED, 'Correct amount of Chest/Enemies shown in Dungeon'),
    new Changelog(changelogType.FIXED, 'Dungeon loot requirements'),

    // v0.9.9
    new ChangelogUpdate('v0.9.9', new Date(2022, 6, 22)),
    new Changelog(changelogType.FIXED, 'Hatching new Pokémon causing errors'),
    new Changelog(changelogType.FIXED, 'Pokémon gaining Pokérus and EVs early'),

    // v0.9.8
    new ChangelogUpdate('v0.9.8', new Date(2022, 6, 22)),
    new Changelog(changelogType.NEW, 'Ability to name Oak item loadouts'),
    new Changelog(changelogType.NEW, 'Shards now appear in Underground'),
    new Changelog(changelogType.NEW, 'Shard traders'),
    new Changelog(changelogType.NEW, 'New one time battles'),
    new Changelog(changelogType.NEW, 'More questlines'),
    new Changelog(changelogType.NEW, 'First 3 Sevii islands'),
    new Changelog(changelogType.NEW, 'Freeze mulch added to Farm'),
    new Changelog(changelogType.NEW, 'Rowap berry now affects EVs gained'),
    new Changelog(changelogType.NEW, 'More methods to gain EVs'),
    new Changelog(changelogType.NEW, 'More sounds'),
    new Changelog(changelogType.CHANGE, 'Pokérus can now spread between Pokémon sharing a type'),
    new Changelog(changelogType.CHANGE, 'Updated current location to use player sprite'),
    new Changelog(changelogType.CHANGE, 'Updated default quest location color'),
    new Changelog(changelogType.CHANGE, 'More notification options'),
    new Changelog(changelogType.CHANGE, 'Unlock extra quest slots 5 levels earlier'),
    new Changelog(changelogType.CHANGE, 'Trade stone is now Linking cord'),
    new Changelog(changelogType.CHANGE, 'More filters and sorting options added'),
    new Changelog(changelogType.CHANGE, 'Updated Tutorial quests'),
    new Changelog(changelogType.CHANGE, 'Baby Pokémon can now be obtained by breeding any evolution in the line'),
    new Changelog(changelogType.CHANGE, 'Display chests and Pokémon remaining in dungeon'),
    new Changelog(changelogType.CHANGE, 'Some Sinnoh and Alola stones added to Underground'),
    new Changelog(changelogType.CHANGE, 'Adjusted loot found in dungeon chests'),
    new Changelog(changelogType.CHANGE, 'Updated some Pokémon evolution methods'),
    new Changelog(changelogType.CHANGE, 'Setting for wider game UI'),
    new Changelog(changelogType.CHANGE, 'Updated some sprites'),
    new Changelog(changelogType.CHANGE, 'Misc text changes'),
    new Changelog(changelogType.CHANGE, 'Misc UI changes'),
    new Changelog(changelogType.FIXED, 'Withered berries statistics not increasing correctly'),
    new Changelog(changelogType.FIXED, 'Some dungeons rewarding fighting eggs every time they were completed'),
    new Changelog(changelogType.FIXED, 'Unable to use some battle items on mobile'),
    new Changelog(changelogType.FIXED, 'Missing town images'),

    // v0.9.7
    new ChangelogUpdate('v0.9.7', new Date(2022, 5, 28)),
    new Changelog(changelogType.NEW, 'Added Fighting Dojo to Saffron City'),
    new Changelog(changelogType.CHANGE, 'Removed \'None\' region from hatchery filters'),
    new Changelog(changelogType.CHANGE, 'Adjusted some dungeons environments'),
    new Changelog(changelogType.CHANGE, 'Updated Floette (Eternal) stats'),
    new Changelog(changelogType.CHANGE, 'Display EV stats in pokédex'),
    new Changelog(changelogType.CHANGE, 'Recieve fighting eggs from some fights'),
    new Changelog(changelogType.FIXED, 'Survival Area shop breaking other shops'),
    new Changelog(changelogType.FIXED, 'Incorrect trainer showing in dungeons'),
    new Changelog(changelogType.FIXED, 'Fixed incorrect experience debuff'),
    new Changelog(changelogType.FIXED, 'Not applying Pokérus if modal was not closed correctly'),
    new Changelog(changelogType.FIXED, 'Can no longer bomb/survey before new layer loaded in the Underground'),
    new Changelog(changelogType.FIXED, 'Missing town images'),

    // v0.9.6
    new ChangelogUpdate('v0.9.6', new Date(2022, 5, 26)),
    new Changelog(changelogType.NEW, 'Able to disable offline money gains in settngs menu'),
    new Changelog(changelogType.NEW, 'Added a some more NPCs to towns'),
    new Changelog(changelogType.NEW, 'Able to filter Pokémon in Protein menu'),
    new Changelog(changelogType.NEW, 'Currency lost animation'),
    new Changelog(changelogType.NEW, 'Save reminder notifications'),
    new Changelog(changelogType.NEW, 'Kanto Team Rocket quest line'),
    new Changelog(changelogType.NEW, 'Mina\'s Trial quest line'),
    new Changelog(changelogType.NEW, 'Added EVs and Pokérus'),
    new Changelog(changelogType.CHANGE, 'Open links in a new tab'),
    new Changelog(changelogType.CHANGE, 'Buffed Diglett\'s cave'),
    new Changelog(changelogType.CHANGE, 'Roaming Pokémon encounters now use their own sound and notification'),
    new Changelog(changelogType.CHANGE, 'Experience gain has been rebalanced'),
    new Changelog(changelogType.CHANGE, 'Flutes have been adjusted'),
    new Changelog(changelogType.CHANGE, 'Adjusted shops stock of items'),
    new Changelog(changelogType.CHANGE, 'Updated encounter environment backgrounds'),
    new Changelog(changelogType.CHANGE, 'Discord Pokémon can no longer be obtained before you reach the respective regions'),
    new Changelog(changelogType.CHANGE, 'Save data can be copied to clipboard if unable to download'),
    new Changelog(changelogType.CHANGE, 'Changed Kanto encounters to follow Fire Red and Leaf Green instead of Yellow version'),
    new Changelog(changelogType.CHANGE, 'Misc map changes'),
    new Changelog(changelogType.CHANGE, 'Misc text changes'),
    new Changelog(changelogType.FIXED, 'Town and Route requirements'),
    new Changelog(changelogType.FIXED, 'Having negative quest amounts'),
    new Changelog(changelogType.FIXED, 'Unown (A) HP in Ruins of Alph'),
    new Changelog(changelogType.FIXED, 'Being able to leave the region early if pokédex challenge enabled'),
    new Changelog(changelogType.FIXED, 'Some quest lines not starting when they should have'),
    new Changelog(changelogType.FIXED, 'Farm hands being reset on reload'),
    new Changelog(changelogType.FIXED, 'Some battle modals not closing'),
    new Changelog(changelogType.FIXED, 'Some achievements not showing as completed'),
    new Changelog(changelogType.FIXED, 'Hatchery queue not filling empty slots occasionally'),
    new Changelog(changelogType.FIXED, 'Area completion status highlighting'),

    // v0.9.5
    new ChangelogUpdate('v0.9.5', new Date(2022, 4, 26)),
    new Changelog(changelogType.FIXED, 'Starter modal appearing multiple times when grass type picked'),
    new Changelog(changelogType.FIXED, 'Error when obtaining a badge'),
    new Changelog(changelogType.FIXED, 'Key items not being obtained'),
    new Changelog(changelogType.FIXED, 'Underground hammer sprite not appearing'),
    new Changelog(changelogType.FIXED, 'Misc text changes'),

    // v0.9.4
    new ChangelogUpdate('v0.9.4', new Date(2022, 4, 26)),
    new Changelog(changelogType.NEW, 'Quest locations now highlighted where possible'),
    new Changelog(changelogType.NEW, 'Battle Frontier now saves your stage if you leave early'),
    new Changelog(changelogType.NEW, 'You will now choose a starter each time you reach a new region'),
    new Changelog(changelogType.NEW, 'Added weather selection to Damage Calculator'),
    new Changelog(changelogType.NEW, 'Added Shop hotkeys'),
    new Changelog(changelogType.NEW, 'Added ability to sort Achievements'),
    new Changelog(changelogType.CHANGE, 'Show current sub region name'),
    new Changelog(changelogType.CHANGE, 'Updated Hammer and Chisel sprites in Underground'),
    new Changelog(changelogType.CHANGE, 'Updated Hatchery sort options and directions, Added a tooltip'),
    new Changelog(changelogType.CHANGE, 'Display highest stage reached while in Battle Frontier'),
    new Changelog(changelogType.CHANGE, 'Added option to display Proteins used in Hatchery'),
    new Changelog(changelogType.CHANGE, 'Updated Pokémon League sprites on map'),
    new Changelog(changelogType.CHANGE, 'Adjusted some themes'),
    new Changelog(changelogType.CHANGE, 'Adjusted dungeon loot'),
    new Changelog(changelogType.CHANGE, 'Grouped Mt. Chimney surrounding Dungeons'),
    new Changelog(changelogType.CHANGE, 'Can now change movement keys for Safari Zone'),
    new Changelog(changelogType.CHANGE, 'Timer now starts in Dungeons once you have moved'),
    new Changelog(changelogType.CHANGE, 'Professor Oak will now tell you how many Pokémon you still need to obtain to move on'),
    new Changelog(changelogType.CHANGE, 'Reduce load time, no longer preload all town images'),
    new Changelog(changelogType.CHANGE, 'Fossils display caught status in Hatchery'),
    new Changelog(changelogType.CHANGE, 'Links on the Save Selector screen will now open in a new tab'),
    new Changelog(changelogType.CHANGE, 'Updated Pokédex filtering options'),
    new Changelog(changelogType.CHANGE, 'Added option to hide Shiny Pokémon in the Protein menu'),
    new Changelog(changelogType.FIXED, 'Berry Master shop buttons'),
    new Changelog(changelogType.FIXED, 'Safari Zone movement animations'),
    new Changelog(changelogType.FIXED, 'Shiny code wrong name displayed occasionally'),
    new Changelog(changelogType.FIXED, 'Damage calculator updates correctly when you hatch Pokémon'),
    new Changelog(changelogType.FIXED, 'Misc text changes'),

    // v0.9.3
    new ChangelogUpdate('v0.9.3', new Date(2022, 3, 28)),
    new Changelog(changelogType.NEW, 'Added Hatchery Helpers [BETA]'),
    new Changelog(changelogType.NEW, 'Added Flutes [BETA]'),
    new Changelog(changelogType.CHANGE, 'Changed default setting for Farm timer'),
    new Changelog(changelogType.CHANGE, 'Added some more settings'),
    new Changelog(changelogType.CHANGE, 'Grouped Mt. Coronet and Melemele Woods surrounding Dungeons'),
    new Changelog(changelogType.CHANGE, 'Moved sell all button in Underground to the Treasures tab'),
    new Changelog(changelogType.CHANGE, 'Ruins of Alph added Unown (A) as a boss until caught'),
    new Changelog(changelogType.FIXED, 'Pokémon now sorted by ID in the evolution stone menu'),

    // v0.9.2
    new ChangelogUpdate('v0.9.2', new Date(2022, 3, 21)),
    new Changelog(changelogType.NEW, 'Updated Alola Akala map'),
    new Changelog(changelogType.NEW, 'Select region with number keys while dock modal is open'),
    new Changelog(changelogType.CHANGE, 'Updated save selector view on mobile'),
    new Changelog(changelogType.CHANGE, 'Badge case split up by region'),
    new Changelog(changelogType.CHANGE, 'Updated some dungeon encounters'),
    new Changelog(changelogType.CHANGE, 'Updated Unown encounters'),
    new Changelog(changelogType.CHANGE, 'Updated webworker and game ticks'),
    new Changelog(changelogType.CHANGE, 'Updated some sprite inconsistencies'),
    new Changelog(changelogType.FIXED, 'Underground sell all no longer starts breeding fossils'),

    // v0.9.1
    new ChangelogUpdate('v0.9.1', new Date(2022, 3, 14)),
    new Changelog(changelogType.FIXED, 'Easter quest line not starting on new saves'),
    new Changelog(changelogType.FIXED, 'Save deletion/importing in game'),
    new Changelog(changelogType.FIXED, 'Shop Pokémon prices rounding'),
    new Changelog(changelogType.FIXED, 'On screen Safari Zone controls not working'),
    new Changelog(changelogType.FIXED, 'Achievement filtering'),
    new Changelog(changelogType.FIXED, 'Dungeon showing as incomplete if locked Pokémon not obtained yet'),

    // v0.9.0
    new ChangelogUpdate('v0.9.0 - Alola', new Date(2022, 3, 13)),
    new Changelog(changelogType.NEW, 'The Alola region is now available'),
    new Changelog(changelogType.NEW, 'More hotkeys'),
    new Changelog(changelogType.NEW, 'Customizable hotkeys'),
    new Changelog(changelogType.NEW, 'Desktop notifications'),
    new Changelog(changelogType.NEW, 'Added Sell-all button to Underground'),
    new Changelog(changelogType.NEW, 'Sinnoh Quest Line'),
    new Changelog(changelogType.CHANGE, 'Adjusted Dungeon Achievement amounts required'),
    new Changelog(changelogType.CHANGE, 'Adjusted shop Evolution Stone caught indicator'),
    new Changelog(changelogType.CHANGE, 'Adjusted some sprites'),
    new Changelog(changelogType.CHANGE, 'Indicate HP buff when opening chests in Dungeons'),
    new Changelog(changelogType.CHANGE, 'Changed some Sinnoh Dungeons'),
    new Changelog(changelogType.CHANGE, 'Ruins of Alph Unown encounters'),
    new Changelog(changelogType.FIXED, 'Save profiles not loading if they contained a % symbol'),

    // v0.8.17
    new ChangelogUpdate('v0.8.17', new Date(2022, 2, 31)),
    new Changelog(changelogType.NEW, 'Added Shiny achievements per region'),
    new Changelog(changelogType.CHANGE, 'Show Evolution Stones from future regions in the items menu if you have at least 1'),
    new Changelog(changelogType.FIXED, 'Incorrect regions for some evolution items'),
    new Changelog(changelogType.FIXED, 'Damage calculator showing NaN'),

    // v0.8.16
    new ChangelogUpdate('v0.8.16', new Date(2022, 2, 30)),
    new Changelog(changelogType.NEW, 'Added map colors for Achievement not yet complete'),
    new Changelog(changelogType.NEW, 'Show Dungeon and Gym clears'),
    new Changelog(changelogType.NEW, 'Can re-order saves on the save selection screen'),
    new Changelog(changelogType.CHANGE, 'Notification and sounds settings now grouped'),
    new Changelog(changelogType.CHANGE, 'Increased size of Gem icons'),
    new Changelog(changelogType.CHANGE, 'Added option to damage calculator that ignores Pokémon level'),
    new Changelog(changelogType.CHANGE, 'Updated the Quest Point cost for some Pokémon'),
    new Changelog(changelogType.CHANGE, 'Different Champion defeat message per region'),
    new Changelog(changelogType.CHANGE, 'Hide Evolution Stones from future regions in the items menu'),
    new Changelog(changelogType.FIXED, 'Progress bar showing as incomplete when an Oak Item is ready to be upgraded'),

    // v0.8.15
    new ChangelogUpdate('v0.8.15', new Date(2022, 2, 14)),
    new Changelog(changelogType.NEW, 'Team Plasma questline'),
    new Changelog(changelogType.CHANGE, 'Shards are now called Gems'),
    new Changelog(changelogType.CHANGE, 'Adjusted some dungeon loot'),
    new Changelog(changelogType.CHANGE, 'DNA no longer shows in master farmer trades'),
    new Changelog(changelogType.CHANGE, 'Lum berry now affects Haban'),
    new Changelog(changelogType.CHANGE, 'Updated route movement hotkeys order (-, +)'),
    new Changelog(changelogType.CHANGE, 'Adjusted Timerball effect'),
    new Changelog(changelogType.CHANGE, 'Updated Sinnoh route 224 requirements'),
    new Changelog(changelogType.CHANGE, 'Updated dungeon achievement order'),
    new Changelog(changelogType.CHANGE, 'Updated start menu order'),
    new Changelog(changelogType.CHANGE, 'Trim search text in Pokédex'),
    new Changelog(changelogType.CHANGE, 'Weather changes'),
    new Changelog(changelogType.CHANGE, 'Show players trainer image as the trainer in the dungeon'),
    new Changelog(changelogType.FIXED, 'Missing shop items'),
    new Changelog(changelogType.FIXED, 'Enigma Discord requirement'),
    new Changelog(changelogType.FIXED, 'Updated some achivement descriptions'),
    new Changelog(changelogType.FIXED, 'Updated message about disabling challenges'),
    new Changelog(changelogType.FIXED, 'Town images breaking if they contained a \' character'),
    new Changelog(changelogType.FIXED, 'Some notifications containing extra . characters'),
    new Changelog(changelogType.FIXED, 'MissingNo. appearing in Gyms/Routes'),
    new Changelog(changelogType.FIXED, 'Shop evolution items showing incorrect caught status'),
    new Changelog(changelogType.FIXED, 'Dungeon XP gained for defeating Pokémon'),
    new Changelog(changelogType.FIXED, 'Minor theme adjustments'),
    new Changelog(changelogType.FIXED, 'New day message no longer appears on new saves'),

    // v0.8.14
    new ChangelogUpdate('v0.8.14', new Date(2022, 1, 11)),
    new Changelog(changelogType.NEW, 'Land vs Water questline in Hoenn'),
    new Changelog(changelogType.NEW, 'Can now shovel away Mulch in the Farm'),
    new Changelog(changelogType.NEW, 'Added some new Pokéball types'),
    new Changelog(changelogType.CHANGE, 'Updated Undella Bay on the Unova map'),
    new Changelog(changelogType.CHANGE, 'Reduced cost of Furfrou (Kabuki)'),
    new Changelog(changelogType.CHANGE, 'Adjusted some NPCs'),
    new Changelog(changelogType.CHANGE, 'Adjusted some dungeon loot'),
    new Changelog(changelogType.CHANGE, 'Extra loot gained from Treasure Scanner now counts towards quests'),
    new Changelog(changelogType.CHANGE, 'Challenges can now be disabled at any point'),
    new Changelog(changelogType.CHANGE, 'Can now download saves from main menu'),
    new Changelog(changelogType.CHANGE, 'Adjusted some shops items'),
    new Changelog(changelogType.CHANGE, 'Adjusted the way evolutions are shown in Evolution Item modal'),
    new Changelog(changelogType.CHANGE, 'Pokémon have variable health on routes based on HP stat'),
    new Changelog(changelogType.CHANGE, 'Can hide Pokémon that have max protein in the protein menu'),
    new Changelog(changelogType.CHANGE, 'Saves Shard menu collapsed state'),
    new Changelog(changelogType.CHANGE, 'Added more options for notifications relating to the Farm'),
    new Changelog(changelogType.FIXED, 'Fixed a problem with dungeons having incorrect item names for loot'),
    new Changelog(changelogType.FIXED, 'Attack value shown on hover in Battle Frontier'),
    new Changelog(changelogType.FIXED, 'Distortion World image on map'),
    new Changelog(changelogType.FIXED, 'Progress bar percentages shown'),
    new Changelog(changelogType.FIXED, 'Extended Johto Pokémon League to cover more map'),
    new Changelog(changelogType.FIXED, 'Gaining dungeon tokens based on new route while catching'),
    new Changelog(changelogType.FIXED, 'Offline progress message not shown on new game creation'),
    new Changelog(changelogType.FIXED, 'New Underground deals notification not shown if Underground not unlocked'),

    // v0.8.13
    new ChangelogUpdate('v0.8.13', new Date(2021, 11, 21)),
    new Changelog(changelogType.NEW, 'Dungeon loot Mimic encounters'),
    new Changelog(changelogType.NEW, 'Added new Furfrou forms'),
    new Changelog(changelogType.FIXED, 'Team Rocket HP'),
    new Changelog(changelogType.FIXED, 'Dungeon loot not being tracked in statistics'),
    new Changelog(changelogType.FIXED, 'Nerfed dungeon loot (still being re-worked)'),

    // v0.8.12
    new ChangelogUpdate('v0.8.12', new Date(2021, 11, 20)),
    new Changelog(changelogType.NEW, 'Added 2 new optional (recommended) challenges'),
    new Changelog(changelogType.NEW, 'Added 2 new x-mas Pokémon'),
    new Changelog(changelogType.NEW, 'Added new Johto questline'),
    new Changelog(changelogType.NEW, 'Added new Johto trainers'),
    new Changelog(changelogType.NEW, 'Added new Johto dungeons'),
    new Changelog(changelogType.NEW, 'Kyurem forms are now obtainable'),
    new Changelog(changelogType.NEW, 'Better looting in dungeons'),
    new Changelog(changelogType.NEW, 'Added a Roamer encounter increase boost to Jaboca berries'),
    new Changelog(changelogType.CHANGE, 'Updated Logbook encounter message formatting'),
    new Changelog(changelogType.CHANGE, 'Reduced Plume Fossil sizing'),
    new Changelog(changelogType.CHANGE, 'Adjusted Castform encounters'),
    new Changelog(changelogType.CHANGE, 'Adjusted some Pokémon encounter locations'),
    new Changelog(changelogType.CHANGE, 'Adjusted some items purchase locations'),
    new Changelog(changelogType.CHANGE, 'Shuffled around some item orders in menus'),
    new Changelog(changelogType.FIXED, 'Minor text fixes'),
    new Changelog(changelogType.FIXED, 'Being able to go into Bait debt in the Safari Zone'),

    // v0.8.11
    new ChangelogUpdate('v0.8.11', new Date(2021, 10, 19)),
    new Changelog(changelogType.CHANGE, 'Trainers and Background will now show a list of images when changing them on your profile'),
    new Changelog(changelogType.CHANGE, 'Hatchery and Protein list now sort independently of Party'),
    new Changelog(changelogType.FIXED, 'Hatchery and Protein list not sorting'),

    // v0.8.10
    new ChangelogUpdate('v0.8.10', new Date(2021, 10, 17)),
    new Changelog(changelogType.NEW, 'Allow using web workers for game ticks'),
    new Changelog(changelogType.NEW, 'Added setting to not reset shop amount when purchasing'),
    new Changelog(changelogType.CHANGE, 'Updated Sinnoh route orders and encounters'),
    new Changelog(changelogType.CHANGE, 'Updated Slowpoke rare item drops'),
    new Changelog(changelogType.CHANGE, 'Added Farm, Daycare, Underground locations to all maps'),
    new Changelog(changelogType.CHANGE, 'Moved a few dungeons out of towns'),
    new Changelog(changelogType.CHANGE, 'Updated Kalos visually'),
    new Changelog(changelogType.CHANGE, 'Lowered some berry unlock requirements'),
    new Changelog(changelogType.FIXED, 'When shoveling a fully grown crop it will be harvested instead'),
    new Changelog(changelogType.FIXED, 'Lag caused by sorting by Pokémon attack'),
    new Changelog(changelogType.FIXED, 'Auto Gym button sizing'),
    new Changelog(changelogType.FIXED, 'Reduce some lag'),
    new Changelog(changelogType.FIXED, 'Minor text fixes'),

    // v0.8.9
    new ChangelogUpdate('v0.8.9', new Date(2021, 8, 12)),
    new Changelog(changelogType.NEW, 'Log book can now be filtered by event type'),
    new Changelog(changelogType.NEW, 'Regional Pokédex achievements'),
    new Changelog(changelogType.NEW, 'Protein achievements'),
    new Changelog(changelogType.NEW, 'Gym auto re-battle system'),
    new Changelog(changelogType.CHANGE, 'Updated Kalos environments'),
    new Changelog(changelogType.CHANGE, 'Added a legend to the map'),
    new Changelog(changelogType.FIXED, 'Misc text fixes'),
    new Changelog(changelogType.FIXED, 'Some locations not showing as locked'),
    new Changelog(changelogType.FIXED, 'Missing/incorrect code contributors links'),
    new Changelog(changelogType.FIXED, 'Dungeon grid lines not appearing on FireFox'),
    new Changelog(changelogType.FIXED, 'MissingNo. appearing in log book'),
    new Changelog(changelogType.FIXED, 'MissingNo. appearing in Battle Frontier'),

    // v0.8.8
    new ChangelogUpdate('v0.8.8', new Date(2021, 8, 5)),
    new Changelog(changelogType.NEW, 'Credits modal for sprites and code contributions'),
    new Changelog(changelogType.CHANGE, 'Can only move to tiles adjacent to visited tiles within Dungeons'),
    new Changelog(changelogType.CHANGE, 'Can start attacking Gyms as soon as the GO text appears'),
    new Changelog(changelogType.CHANGE, 'Added more NPCs'),
    new Changelog(changelogType.CHANGE, 'Farm hands will restore energy while not hired'),
    new Changelog(changelogType.CHANGE, 'Game settings are now stored within the each individual save'),
    new Changelog(changelogType.CHANGE, 'Route highlights for uncaught Pokémon, uncaught shiny Pokémon'),
    new Changelog(changelogType.CHANGE, 'Settings to change colors of route highlights'),
    new Changelog(changelogType.CHANGE, 'Dungeons now decrease in size for every 10, 100, 1000 etc clears'),
    new Changelog(changelogType.CHANGE, 'Show net value of Underground in footer'),
    new Changelog(changelogType.FIXED, 'Some Fossils appearing in the underground too early'),
    new Changelog(changelogType.FIXED, 'Dungeon trainers re-appearing after failing them previously'),

    // v0.8.7
    new ChangelogUpdate('v0.8.7', new Date(2021, 7, 31)),
    new Changelog(changelogType.NEW, '(BETA) Added Farm Hands (Farm Automation) - Check out the Help tab in the Farm for more info'),
    new Changelog(changelogType.NEW, 'Added an option to hide challenge related modules'),
    new Changelog(changelogType.CHANGE, 'Display total route defeats when on a route'),
    new Changelog(changelogType.CHANGE, 'Player will return to last Dungeon/Town they were in before closing game'),
    new Changelog(changelogType.CHANGE, 'Buffed Pokémon typed quest reward amounts'),
    new Changelog(changelogType.CHANGE, 'Should no longer receive quest that cannot be completed right now (unless starting a new region)'),
    new Changelog(changelogType.CHANGE, 'Nerfed Dungeon Token gains in Dungeons'),
    new Changelog(changelogType.CHANGE, 'Added unobtainable berries for No Oak Item saves to Johto Berry Master (must have prerequisites to purchase)'),
    new Changelog(changelogType.FIXED, 'Minor theme fixes'),
    new Changelog(changelogType.FIXED, 'Trainer image fixes'),
    new Changelog(changelogType.FIXED, 'Being able to win and lose when fighting a Gym'),

    // v0.8.6
    new ChangelogUpdate('v0.8.6', new Date(2021, 7, 22)),
    new Changelog(changelogType.CHANGE, 'Added more NPCs'),
    new Changelog(changelogType.CHANGE, 'Buffed Capture Pokémon Type quest rewards'),
    new Changelog(changelogType.CHANGE, 'Buffed Pledge Grove'),
    new Changelog(changelogType.FIXED, 'Decrease shop multiplier when fighting Trainers/Gyms/Elite 4'),
    new Changelog(changelogType.FIXED, 'Boss icon visible on light themes'),
    new Changelog(changelogType.FIXED, 'Some Pokémon level speed types'),
    new Changelog(changelogType.FIXED, 'Achievements percentage going above maximum'),
    new Changelog(changelogType.FIXED, 'Quest box sometimes dissapearing'),
    new Changelog(changelogType.FIXED, 'Minor text fixes'),

    // v0.8.5
    new ChangelogUpdate('v0.8.5', new Date(2021, 7, 4)),
    new Changelog(changelogType.FIXED, 'Battle Frontier not awarding items'),

    // v0.8.4
    new ChangelogUpdate('v0.8.4', new Date(2021, 7, 4)),
    new Changelog(changelogType.NEW, 'Able to unlock Apicot and Lancat berries'),
    new Changelog(changelogType.NEW, 'Added Farming related achievements'),
    new Changelog(changelogType.NEW, 'Added Battle Frontier related achievements'),
    new Changelog(changelogType.NEW, 'Added option to settings menu to shorten currency amounts displayed on main game screen'),
    new Changelog(changelogType.NEW, 'Added Offline earnings for money (max of 24 hours)'),
    new Changelog(changelogType.NEW, 'Added a couple of new quest types'),
    new Changelog(changelogType.CHANGE, 'Buffed click attack calculation'),
    new Changelog(changelogType.CHANGE, 'Nerfed Kalos Route 22 HP'),
    new Changelog(changelogType.CHANGE, 'Englarged clickable area for Kanto map towns and dungeons'),
    new Changelog(changelogType.CHANGE, 'Vivillon base form changed to Vivillon (Meadow)'),
    new Changelog(changelogType.CHANGE, 'Removed Rare Candy from shops until it has a use'),
    new Changelog(changelogType.FIXED, 'Vivillon quest step not being completable if you had already defeated stage 666 in the Battle Frontier'),
    new Changelog(changelogType.FIXED, 'Some Gyms had incorrect HP'),
    new Changelog(changelogType.FIXED, 'Some trainers teams'),
    new Changelog(changelogType.FIXED, 'Some Pokémon were not counted towards the catch a type quests'),
    new Changelog(changelogType.FIXED, 'Show item count for non Underground items in the Daily deals'),
    new Changelog(changelogType.FIXED, 'Being able to enter some dungeons early'),

    // v0.8.3
    new ChangelogUpdate('v0.8.3', new Date(2021, 6, 30)),
    new Changelog(changelogType.NEW, 'Vivillon quest line'),
    new Changelog(changelogType.CHANGE, 'Achievement bonus percentage now also applies to Dungeon Tokens'),
    new Changelog(changelogType.CHANGE, 'Added Mystery Egg to Unova shop'),
    new Changelog(changelogType.CHANGE, 'Updated the look of most maps'),
    new Changelog(changelogType.CHANGE, 'Added an icon to dungeon bosses'),
    new Changelog(changelogType.CHANGE, 'Show inventory amount of item you are receiving from Underground daily deal'),
    new Changelog(changelogType.FIXED, 'Updated Oak Item achivements for no click challenge players'),
    new Changelog(changelogType.FIXED, 'Underground not refreshing after completing layer and purchasing size upgrade'),
    new Changelog(changelogType.FIXED, 'Softlock from Safari Ticket and Shard Case if the user refreshed the page after obtaining a badge'),
    new Changelog(changelogType.FIXED, 'Some trainers teams'),
    new Changelog(changelogType.FIXED, 'Gym/Elite Four money reward amounts'),
    new Changelog(changelogType.FIXED, 'Kanto dock ship not showing on client'),
    new Changelog(changelogType.FIXED, 'Pokémon League images'),
    new Changelog(changelogType.FIXED, 'When purchasing multiple shop Pokémon the shiny chance was only rolled once'),
    new Changelog(changelogType.FIXED, 'Some Pokémon silhouettes showing colors when not obtained yet'),

    // v0.8.2
    new ChangelogUpdate('v0.8.2', new Date(2021, 4, 3)),
    new Changelog(changelogType.NEW, 'Added in game FAQ'),
    new Changelog(changelogType.CHANGE, 'Updated look of Kanto map'),
    new Changelog(changelogType.CHANGE, 'Added achievement for maxing all 12 Oak items'),
    new Changelog(changelogType.FIXED, 'Hatched display value not updating in hatchery'),
    new Changelog(changelogType.FIXED, 'Various text fixes'),
    new Changelog(changelogType.FIXED, 'Dungeon bosses can now drop held items'),
    new Changelog(changelogType.FIXED, 'Update some dungeon trainers HP'),
    new Changelog(changelogType.FIXED, '2nd part of re-capturing tutorial is now optional, as may still appear odd on some browsers'),

    // v0.8.1
    new ChangelogUpdate('v0.8.1', new Date(2021, 3, 28)),
    new Changelog(changelogType.NEW, 'Added Kalos fossil Pokémon'),
    new Changelog(changelogType.NEW, 'Added trainers to Hoenn dungeons'),
    new Changelog(changelogType.NEW, 'Added trainers to Unova dungeons'),
    new Changelog(changelogType.CHANGE, 'Tidy up some badge sprites'),
    new Changelog(changelogType.CHANGE, 'Starting tutorial no longer skippable'),
    new Changelog(changelogType.CHANGE, 'Hide unobtainable achievements when running challenge modes'),
    new Changelog(changelogType.FIXED, 'Added starting towns to Unova and Kalos'),
    new Changelog(changelogType.FIXED, 'Fixed a few Pokémon sprites'),
    new Changelog(changelogType.FIXED, 'Minor text fixes'),
    new Changelog(changelogType.FIXED, 'Added some missing/unobtainable Kalos Pokémon'),

    // v0.8.0
    new ChangelogUpdate('v0.8.0 - Kalos', new Date(2021, 3, 4)),
    new Changelog(changelogType.NEW, 'The Kalos region is now available!\n<i>Some trainer sprites will be missing</i>'),
    new Changelog(changelogType.FIXED, 'Fixed missing Battle Frontier images'),
    new Changelog(changelogType.FIXED, 'Attempt to fix svg image on map for older Safari versions'),

    // v0.7.9
    new ChangelogUpdate('v0.7.9 - Patches', new Date(2021, 2, 3)),
    new Changelog(changelogType.FIXED, 'Attempting to fix some lag, please report on Discord/Github if you are still having major lag compared with v0.7.7, there may be a few patches pushed out for testing'),

    // v0.7.8
    new ChangelogUpdate('v0.7.8', new Date(2021, 2, 2)),
    new Changelog(changelogType.NEW, 'Increased roamer odds on specific routes changing every 8 hours, NPCs in certain towns will tell you the current route'),
    new Changelog(changelogType.NEW, 'Mine items quest in Underground'),
    new Changelog(changelogType.FIXED, 'Fixed dungeon token gain'),
    new Changelog(changelogType.FIXED, 'Safari Zone animations'),
    new Changelog(changelogType.FIXED, 'Safari Zone encounter statistics'),
    new Changelog(changelogType.FIXED, 'Some roaming event mons'),
    new Changelog(changelogType.FIXED, 'Not being able to import saves from < v0.5.x'),

    // v0.7.7
    new ChangelogUpdate('v0.7.7', new Date(2021, 1, 20)),
    new Changelog(changelogType.FIXED, 'Fixed currency quests'),
    new Changelog(changelogType.FIXED, 'Fixed currency multipliers'),
    new Changelog(changelogType.FIXED, 'Fixed quest refreshing without waiting for confirmation'),

    // v0.7.6
    new ChangelogUpdate('v0.7.6', new Date(2021, 1, 19)),
    new Changelog(changelogType.NEW, 'Oak item loadouts'),
    new Changelog(changelogType.CHANGE, 'No more impossible quest when doing challenges'),
    new Changelog(changelogType.CHANGE, 'Able to delete saves on the windows client'),
    new Changelog(changelogType.CHANGE, 'Dungeon Trainers Pokémon will now reward Dungeon Tokens when defeated'),
    new Changelog(changelogType.CHANGE, 'Dungeon Trainers will now reward Money when defeated'),
    new Changelog(changelogType.FIXED, 'Sound not remembering previously set volume'),
    new Changelog(changelogType.FIXED, 'Let\'s Go mons not showing in Pokémon list'),
    new Changelog(changelogType.FIXED, 'Some missing stone evolutions'),
    new Changelog(changelogType.FIXED, 'Elite four shortcut keys working again'),
    new Changelog(changelogType.FIXED, 'Fixed some Pokémon shop sprites'),
    new Changelog(changelogType.FIXED, 'Fixed some missing trainer sprites'),
    new Changelog(changelogType.FIXED, 'Fixed some routes/dungeons showing incorrect backgrounds'),
    new Changelog(changelogType.FIXED, 'Saved game not importing if settings are not set'),

    // v0.7.5
    new ChangelogUpdate('v0.7.5 - Challenges, Trainers and Saves', new Date(2021, 0, 29)),
    new Changelog(changelogType.FIXED, 'Fix proteins not increasing on usage'),
    new Changelog(changelogType.FIXED, 'Some trainer images not loading'),
    new Changelog(changelogType.FIXED, 'Dynamic Pokémon disappearing  before leaving screen'),

    // v0.7.4
    new ChangelogUpdate('v0.7.4 - Challenges, Trainers and Saves', new Date(2021, 0, 29)),
    new Changelog(changelogType.NEW, 'Multiple save file support'),
    new Changelog(changelogType.NEW, 'Challenge modes'),
    new Changelog(changelogType.NEW, 'Trainers added to Kanto Dungeons'),
    new Changelog(changelogType.CHANGE, 'Log wandering Pokémon for Farm'),
    new Changelog(changelogType.CHANGE, 'Change Lum berry Aura effect'),
    new Changelog(changelogType.CHANGE, 'Add more Burmy forms'),
    new Changelog(changelogType.CHANGE, 'Underground items can spawn in any rotation'),
    new Changelog(changelogType.CHANGE, 'Quest generation updated'),
    new Changelog(changelogType.CHANGE, 'Dynamic background Pokémon now have variable speed'),
    new Changelog(changelogType.CHANGE, 'Leave button won\'t appear in Dungeon until the player has moved'),
    new Changelog(changelogType.FIXED, 'Underground survey upgrade display'),
    new Changelog(changelogType.FIXED, 'Fix Heatran & Kyurem HP'),
    new Changelog(changelogType.FIXED, 'Underground no longer notifies on new game'),
    new Changelog(changelogType.FIXED, 'Hide future region forms from Battle Frontier'),
    new Changelog(changelogType.FIXED, 'Fixed quick catch glitch'),

    // v0.7.3
    new ChangelogUpdate('v0.7.3 - Underground', new Date(2021, 0, 18)),
    new Changelog(changelogType.NEW, 'Underground revamped'),
    new Changelog(changelogType.CHANGE, 'More Pokémon held items added'),
    new Changelog(changelogType.CHANGE, 'Add tooltips to battle item values'),
    new Changelog(changelogType.CHANGE, 'Misc Farm changes and fixes'),
    new Changelog(changelogType.CHANGE, 'Add Leave button to dungeon entrance'),
    new Changelog(changelogType.FIXED, 'Hatchery steps given from Unvoa dungeons'),
    new Changelog(changelogType.FIXED, 'Old Amber quest reward'),
    new Changelog(changelogType.FIXED, 'Event description line breaks'),

    // v0.7.2
    new ChangelogUpdate('v0.7.2', new Date(2021, 0, 3)),
    new Changelog(changelogType.FIXED, 'Poison Barb not gaining experience'),
    new Changelog(changelogType.FIXED, 'Map tooltips not always showing'),

    // v0.7.1
    new ChangelogUpdate('v0.7.1', new Date(2021, 0, 1)),
    new Changelog(changelogType.NEW, 'Unova Fossils now available in the Underground'),
    new Changelog(changelogType.NEW, 'Add option to display Pokédex ID in hatchery'),
    new Changelog(changelogType.NEW, 'Save achievement filters'),
    new Changelog(changelogType.NEW, 'Use multiple Protein at once'),
    new Changelog(changelogType.CHANGE, 'Buff P2 Lab, increase boss pool'),
    new Changelog(changelogType.FIXED, 'Fixed some parasitic Farm mutations'),
    new Changelog(changelogType.FIXED, 'Fixed shiny chance when hatching and using Shiny Charm'),
    new Changelog(changelogType.FIXED, 'Vermilion City image & name'),
    new Changelog(changelogType.FIXED, 'Quest changing when traveling to a new region'),

    // v0.7.0
    new ChangelogUpdate('v0.7.0 - Unova', new Date(2020, 11, 23)),
    new Changelog(changelogType.NEW, 'The Unova region is now available!'),
    new Changelog(changelogType.NEW, 'Added notification for when Berry about to wither'),
    new Changelog(changelogType.CHANGE, 'Minor text fixes'),
    new Changelog(changelogType.CHANGE, 'Route HP slightly buffed'),
    new Changelog(changelogType.CHANGE, 'Some Gyms and Dungeons HP buffed'),
    new Changelog(changelogType.FIXED, 'Babiri berry removed from Enigma pool'),

    // v0.6.9
    new ChangelogUpdate('v0.6.9', new Date(2020, 11, 20)),
    new Changelog(changelogType.CHANGE, 'Give free quest refresh on all quests completed'),
    new Changelog(changelogType.CHANGE, 'Updated some environments'),
    new Changelog(changelogType.CHANGE, 'Buffed Babiri berry effect'),
    new Changelog(changelogType.CHANGE, 'Buffed Enigma berry'),
    new Changelog(changelogType.CHANGE, 'Buffed Farm wandering Pokémon rate'),
    new Changelog(changelogType.CHANGE, 'Updated Petaya berry effect'),
    new Changelog(changelogType.CHANGE, 'Updated Kasib berry effect'),
    new Changelog(changelogType.CHANGE, 'Added hints for more berries'),
    new Changelog(changelogType.CHANGE, 'Updated some NPC text'),
    new Changelog(changelogType.CHANGE, 'Buffed egg steps for baby Pokémon'),
    new Changelog(changelogType.CHANGE, 'Nerfed egg steps for evolved Pokémon forms'),
    new Changelog(changelogType.FIXED, 'Fixed Farm auras not updating'),
    new Changelog(changelogType.FIXED, 'Modals locking game if clicked too fast'),

    // v0.6.8
    new ChangelogUpdate('v0.6.8', new Date(2020, 11, 9)),
    new Changelog(changelogType.NEW, 'Added weather to the regions'),
    new Changelog(changelogType.NEW, 'Empty Hatchery queue notification added'),
    new Changelog(changelogType.CHANGE, 'Nerfed Heatran'),
    new Changelog(changelogType.FIXED, 'Minor text fixes'),
    new Changelog(changelogType.FIXED, 'Fixed some Farm mutations'),
    new Changelog(changelogType.FIXED, 'Fixed Farm auras not updating'),
    new Changelog(changelogType.FIXED, 'Can no longer move around the Safari Zone before paying'),

    // v0.6.7
    new ChangelogUpdate('v0.6.7', new Date(2020, 10, 22)),
    new Changelog(changelogType.CHANGE, 'Added some more NPC around Kanto'),
    new Changelog(changelogType.CHANGE, 'Doubled the chance of encountering uncaught Roaming Pokémon'),
    new Changelog(changelogType.CHANGE, 'Save category filter in Hatchery upon reloading'),
    new Changelog(changelogType.CHANGE, 'Decreased the Shovel cost'),
    new Changelog(changelogType.CHANGE, 'Farm items cost decreases faster based on berry type harvested'),
    new Changelog(changelogType.FIXED, 'Minor text fixes'),
    new Changelog(changelogType.FIXED, 'Recalculate Pokémon attack upon hatch'),
    new Changelog(changelogType.FIXED, 'Fixed some Farm mutations'),
    new Changelog(changelogType.FIXED, 'Fixed larger BerryDex timers'),
    new Changelog(changelogType.FIXED, 'Fixed quests auto refreshing if you gain a level then refreshed the page'),
    new Changelog(changelogType.FIXED, 'Fix Quickball on routes with less than 10 kills'),

    // v0.6.6
    new ChangelogUpdate('v0.6.6', new Date(2020, 10, 18)),
    new Changelog(changelogType.CHANGE, 'Show shiny symbol for Pokémon in Protein modal'),
    new Changelog(changelogType.FIXED, 'Achievement pages being empty after completing last item on page'),
    new Changelog(changelogType.FIXED, 'Start menu visible while loading screen shown'),
    new Changelog(changelogType.FIXED, 'Save update from older versions'),
    new Changelog(changelogType.FIXED, 'Time displayed in BerryDex'),
    new Changelog(changelogType.FIXED, 'Pokédex hide shiny images toggle correctly reflects current state'),

    // v0.6.5
    new ChangelogUpdate('v0.6.5', new Date(2020, 10, 18)),
    new Changelog(changelogType.NEW, 'Added toggle to hide shiny images in Pokédex'),
    new Changelog(changelogType.NEW, 'New display options added to Hatchery'),
    new Changelog(changelogType.NEW, 'Can sort Pokémon list by total proteins used'),
    new Changelog(changelogType.NEW, 'New Pokéball types added, Can be obtained by trading with the Johto Berry Master'),
    new Changelog(changelogType.NEW, 'Add setting to switch between different growth timers in the Farm'),
    new Changelog(changelogType.CHANGE, 'Nerfed Protein, only 5 can be used per region visited'),
    new Changelog(changelogType.CHANGE, 'Protein is now used from the Items menu'),
    new Changelog(changelogType.CHANGE, 'Updated BerryDex to show more readable time format'),
    new Changelog(changelogType.CHANGE, 'Berries are less likely to mutate nearby plots to themselves'),
    new Changelog(changelogType.CHANGE, 'Berries are less likely to create mutations of themselves'),
    new Changelog(changelogType.CHANGE, 'Nerfed some of the Berry Auras'),
    new Changelog(changelogType.CHANGE, 'Increase Farm wandering Pokémon shiny chance'),
    new Changelog(changelogType.CHANGE, 'Misc Farm changes'),
    new Changelog(changelogType.CHANGE, 'Misc text changes'),
    new Changelog(changelogType.FIXED, 'Hotkeys will no longer activate while focused on inputs'),
    new Changelog(changelogType.FIXED, 'Category list no longer cut off in Hacthery'),

    // v0.6.4
    new ChangelogUpdate('v0.6.4', new Date(2020, 10, 17)),
    new Changelog(changelogType.NEW, 'More Farm statistics'),
    new Changelog(changelogType.CHANGE, 'UI/text changes'),
    new Changelog(changelogType.CHANGE, 'Farm flavor mutations are more strict and less invasive'),
    new Changelog(changelogType.CHANGE, 'Hide locked berries in trade window'),
    new Changelog(changelogType.FIXED, 'Quest not completing if restarted after being quit'),
    new Changelog(changelogType.FIXED, 'Farm mulches can now be applied multiple times per plot'),
    new Changelog(changelogType.FIXED, 'Oak items upgraded currency shows correct currency'),
    new Changelog(changelogType.FIXED, 'Berry hints updating correctly each day'),
    new Changelog(changelogType.FIXED, 'Fixed some lag'),

    // v0.6.3
    new ChangelogUpdate('v0.6.3', new Date(2020, 10, 13)),
    new Changelog(changelogType.CHANGE, 'Show Berry hints in BerryDex'),
    new Changelog(changelogType.FIXED, 'Farm mulch should work correctly now'),
    new Changelog(changelogType.FIXED, 'Update Pokémon native regions'),
    new Changelog(changelogType.FIXED, 'Proteins used not based on Battle Item multiplier'),

    // v0.6.1
    new ChangelogUpdate('v0.6.1', new Date(2020, 10, 13)),
    new Changelog(changelogType.NEW, 'More Farm statistics'),
    new Changelog(changelogType.NEW, 'Added Protein trade to Sinnoh Berry Master'),
    new Changelog(changelogType.NEW, 'Added multiple button to Mulch in Farm'),
    new Changelog(changelogType.FIXED, 'Fix Pokémon not appearing in Battle Frontier'),
    new Changelog(changelogType.FIXED, 'Evolution Stones not working'),

    // v0.6.0
    new ChangelogUpdate('v0.6.0 - Farming', new Date(2020, 10, 13)),
    new Changelog(changelogType.NEW, 'Complete Farm overhaul'),
    new Changelog(changelogType.NEW, 'Hotkeys added for oak items modal (O to open, number keys to toggle items)'),
    new Changelog(changelogType.NEW, 'Hotkeys added for Pokéball selector modal (P + number to open, number keys to toggle items)'),
    new Changelog(changelogType.NEW, 'More NPCs added around the regions'),
    new Changelog(changelogType.NEW, 'Other Deoxys forms obtainable in the Battle Frontier'),
    new Changelog(changelogType.NEW, 'Protein item now has a use, buy from Pokémon League, use in Hatchery'),
    new Changelog(changelogType.NEW, 'Free quest refreshes'),
    new Changelog(changelogType.NEW, 'Hatchery filters are now saved upon reload'),
    new Changelog(changelogType.CHANGE, 'Damage output modified, dual types nerfed, single types buffed'),
    new Changelog(changelogType.CHANGE, 'Unlock Kanto route 22 earlier in the game'),
    new Changelog(changelogType.CHANGE, 'Show currently locked Dungeon Bosses'),
    new Changelog(changelogType.CHANGE, 'Modified Sinnoh route difficulty'),
    new Changelog(changelogType.CHANGE, 'Display time played as a readable value'),
    new Changelog(changelogType.CHANGE, 'Quests list not auto refreshed on new day or level up'),
    new Changelog(changelogType.CHANGE, 'Update Masterball image'),
    new Changelog(changelogType.FIXED, 'All eggs will auto hatch when steps reached if Pokémon still in the queue'),
    new Changelog(changelogType.FIXED, 'Backup save data corrected'),
    new Changelog(changelogType.FIXED, 'Pokémon List resorted when new Pokémon obtained'),
    new Changelog(changelogType.FIXED, 'Attack display error'),
    new Changelog(changelogType.FIXED, 'Acheivements re-filter once acheivement completed'),
    new Changelog(changelogType.FIXED, 'Swapped Kanto routes 7 and 8'),
    new Changelog(changelogType.FIXED, 'Reduce svg image sizes, fix some lag'),
    new Changelog(changelogType.FIXED, 'Reduce screen movement on mobile battle view'),

    // v0.5.8
    new ChangelogUpdate('v0.5.8', new Date(2020, 10, 1)),
    new Changelog(changelogType.NEW, 'Queue functionality added to Hatchery'),
    new Changelog(changelogType.NEW, 'Can add Pokémon to custom Categories, and sort/filter by those'),
    new Changelog(changelogType.NEW, 'Safari Zone Pokémon can now appear as overworld sprites'),
    new Changelog(changelogType.NEW, 'Completed Quest and Achievements will show in the Log Book'),
    new Changelog(changelogType.NEW, 'See Pokémon Attack after calculations by hovering Pokémon Attack value'),
    new Changelog(changelogType.NEW, 'Add sparkle to shiny overworld sprites for Dynamic Background and Safari Zone'),
    new Changelog(changelogType.NEW, 'Can sort Pokémon by Times Hatched'),
    new Changelog(changelogType.CHANGE, 'Boost Dungeon Tokens gained slightly'),
    new Changelog(changelogType.CHANGE, 'Updated images, Use svg images for Currency and Pokéballs'),
    new Changelog(changelogType.CHANGE, 'Evolution Stones will show a caught indicator in shops'),
    new Changelog(changelogType.CHANGE, 'Display date in changelog when updates occured'),
    new Changelog(changelogType.CHANGE, 'Update Gyms Pokémon and defeated text'),
    new Changelog(changelogType.CHANGE, 'Update Kanto Pokémon encounters to be based on Pokémon Yellow version'),
    new Changelog(changelogType.CHANGE, 'Updated layout of Pokémon List'),
    new Changelog(changelogType.CHANGE, 'Show event Pokémon in the Pokédex'),
    new Changelog(changelogType.CHANGE, 'Can no longer upgrade shard effectiveness where there is no usage'),
    new Changelog(changelogType.CHANGE, 'Roaming Pokémon chance of appearing is now based on route difficulty'),
    new Changelog(changelogType.CHANGE, 'Doubled the chance of encountering uncaught Pokémon in the Safari Zone'),
    new Changelog(changelogType.CHANGE, 'Display Pokéball amount in selector modal'),
    new Changelog(changelogType.FIXED, 'Can no longer start a new Pokémon League battle if modal open'),
    new Changelog(changelogType.FIXED, 'Shop cost will no longer go above 100× the base cost'),
    new Changelog(changelogType.FIXED, 'Underground hammer will display red box when on edge tiles'),
    new Changelog(changelogType.FIXED, 'Mine should no longer soft lock players'),
    new Changelog(changelogType.FIXED, 'Alternate Form Pokémon statistics shown correctly'),
    new Changelog(changelogType.FIXED, 'When hatching shop eggs, the Pokémon level will no longer be reset'),
    new Changelog(changelogType.FIXED, 'Underground daily trades statistic will increment correctly when doing multiple trades'),
    new Changelog(changelogType.FIXED, 'Minor display and text fixes'),

    // v0.5.7
    new ChangelogUpdate('v0.5.7', new Date(2020, 9, 13)),
    new Changelog(changelogType.NEW, 'Added setting for Hatchery egg ready to hatch animations'),
    new Changelog(changelogType.NEW, 'More NPCs in towns around Johto and Hoenn'),
    new Changelog(changelogType.NEW, 'Types displayed in Pokémon statistics modal'),
    new Changelog(changelogType.NEW, 'Underground Bomb is now upgradable'),
    new Changelog(changelogType.NEW, 'Buttons added to achievement modal to jump to first and last pages'),
    new Changelog(changelogType.NEW, 'Number keys (1-9) can now be used to start Pokémon League battles'),
    new Changelog(changelogType.CHANGE, 'Pokéball selector made smaller, now makes use of a modal'),
    new Changelog(changelogType.CHANGE, 'Add some spacing to Damage Calculator'),
    new Changelog(changelogType.CHANGE, 'Hatchery eggs will display in a row of 4 when module is in the middle columnn'),
    new Changelog(changelogType.CHANGE, 'Always show total levels in Oak Item tooltips'),
    new Changelog(changelogType.CHANGE, 'Updated images for shop Pokémon'),
    new Changelog(changelogType.CHANGE, 'Farm images made sharper'),
    new Changelog(changelogType.FIXED, 'Dungeons with a large amount of Pokémon will no longer hide the start button'),
    new Changelog(changelogType.FIXED, 'Updated Hatchery sort display'),
    new Changelog(changelogType.FIXED, 'Notification sounds normalized'),
    new Changelog(changelogType.FIXED, 'Sprout images displayed in Farm'),
    new Changelog(changelogType.FIXED, 'Achievement modal pages should now show the correct numbers'),
    new Changelog(changelogType.FIXED, 'Mine data contained in save data'),
    new Changelog(changelogType.FIXED, 'Saves should no longer have issues downloading'),

    // v0.5.6
    new ChangelogUpdate('v0.5.6', new Date(2020, 9, 6)),
    new Changelog(changelogType.NEW, 'Added Damage Calculator to Start Menu'),
    new Changelog(changelogType.NEW, 'Background settings Night and Dynamic added'),
    new Changelog(changelogType.NEW, 'Walking in the Safari Zone will now add steps to your eggs'),
    new Changelog(changelogType.NEW, 'Achievements added for reaching maximum level on oak items'),
    new Changelog(changelogType.NEW, 'Added Achievement Tracker module'),
    new Changelog(changelogType.NEW, 'Added region filter to Pokédex'),
    new Changelog(changelogType.NEW, 'Added sort dropdown to the Hatchery'),
    new Changelog(changelogType.NEW, 'Added setting for shop value increment amount'),
    new Changelog(changelogType.NEW, 'Introduction to some gameplay elements added for new players'),
    new Changelog(changelogType.NEW, 'Eggs will wobble when they are ready to hatch'),
    new Changelog(changelogType.NEW, 'Start Menu contains a link to the Wiki'),
    new Changelog(changelogType.CHANGE, 'Can hide the Pokémon filter in the Hatchery'),
    new Changelog(changelogType.CHANGE, 'Energy use disabled once you complete a layer in Underground until refreshed'),
    new Changelog(changelogType.CHANGE, 'Added player icon in Dungeons'),
    new Changelog(changelogType.CHANGE, 'Can see your list of eggs and fossils even if you cannot breed them'),
    new Changelog(changelogType.CHANGE, 'Unobtained Pokémon will show as white on dark themes'),
    new Changelog(changelogType.FIXED, 'Underground will no longer contain multiple deals with the same items'),
    new Changelog(changelogType.FIXED, 'Shop prices should no longer overflow when too large'),
    new Changelog(changelogType.FIXED, 'Discord usernames should no longer affect saves'),

    // v0.5.5
    new ChangelogUpdate('v0.5.5', new Date(2020, 9, 3)),
    new Changelog(changelogType.NEW, 'Achievements can now be filtered'),
    new Changelog(changelogType.NEW, 'Can sort Underground items by clicking on table titles'),
    new Changelog(changelogType.NEW, 'NPCs now in towns, will provide dialog that will help the player complete their Pokédex'),
    new Changelog(changelogType.NEW, 'More notification settings have been added'),
    new Changelog(changelogType.CHANGE, 'Increase shiny chance when using an evolution item'),
    new Changelog(changelogType.CHANGE, 'Increase shiny chance for dungeon Pokémon'),
    new Changelog(changelogType.CHANGE, 'More shops added to towns'),
    new Changelog(changelogType.CHANGE, 'More Pokémon added to typed eggs'),
    new Changelog(changelogType.CHANGE, 'Electrike is now exclusive to eggs'),
    new Changelog(changelogType.CHANGE, '"Complete the Kanto Pokédex!" achievement now requires all 151 Kanto Pokémon'),
    new Changelog(changelogType.CHANGE, 'Regirock, Regice and Registeel no longer Roaming, now in Sealed Chamber dungeon'),
    new Changelog(changelogType.CHANGE, 'Kyogre and Groudon will only appear in their dungeon after defeating the Hoenn Elite 4'),
    new Changelog(changelogType.CHANGE, 'If you encounter a new Pokémon that is also shiny, the higher tier ball will be selected'),
    new Changelog(changelogType.CHANGE, 'Battle item effect timers now display upto 99 hours'),
    new Changelog(changelogType.CHANGE, 'Phione now obtained by breeding Manaphy'),
    new Changelog(changelogType.FIXED, 'Quest list should only auto refresh if all quest are claimed or it is a new day'),
    new Changelog(changelogType.FIXED, 'Gym Pokémon can no longer be captured by players'),
    new Changelog(changelogType.FIXED, 'Reduce some lag caused by hatchery filters'),
    new Changelog(changelogType.FIXED, 'Mystery egg can now hatch Pokémon from the Dragon Egg pool'),
    new Changelog(changelogType.FIXED, 'Travelling to the next Region now requires all of that regions Pokémon (excluding different forms)'),

    // v0.5.4
    new ChangelogUpdate('v0.5.4', new Date(2020, 8, 28)),
    new Changelog(changelogType.NEW, 'More stores and items added in Johto, Hoenn and Sinnoh'),
    new Changelog(changelogType.NEW, 'Added notifications for the Farm'),
    new Changelog(changelogType.NEW, 'Can now sort Pokémon list by Breeding Efficiency'),
    new Changelog(changelogType.NEW, 'Can now sort Pokémon list by Egg Steps'),
    new Changelog(changelogType.NEW, 'New Rotom forms available'),
    new Changelog(changelogType.NEW, 'Added ability to use multiple battle items in 1 click'),
    new Changelog(changelogType.NEW, 'Shards types can now be collapsed'),
    new Changelog(changelogType.CHANGE, 'Game should now load in older versions of Firefox'),
    new Changelog(changelogType.CHANGE, 'Mesprit and Cresselia are now roaming in Sinnoh'),
    new Changelog(changelogType.FIXED, 'Updated Burmy (plant) shop image'),
    new Changelog(changelogType.FIXED, 'Safari Zone modal should no longer be able to close without clicking the intended buttons'),
    new Changelog(changelogType.FIXED, 'Updated Shoal Cave entry cost'),
    new Changelog(changelogType.FIXED, 'Hatchery should no longer cause lag when hatching'),
    new Changelog(changelogType.FIXED, 'Old Quests will no longer give a notification when completed once they are refreshed'),

    // v0.5.3
    new ChangelogUpdate('v0.5.3', new Date(2020, 8, 21)),
    new Changelog(changelogType.NEW, 'Can filter Daycare Pokémon by name (regex supported)'),
    new Changelog(changelogType.NEW, 'Select which information is displayed under each Pokémon in the Daycare'),
    new Changelog(changelogType.NEW, 'Possible to start with a Pikachu if no starter Pokémon selected enough times'),
    new Changelog(changelogType.CHANGE, 'Some Roaming Pokémon will only appear after certain requirements have been met'),
    new Changelog(changelogType.CHANGE, 'Some Dungeon Pokémon will only appear after certain requirements have been met'),
    new Changelog(changelogType.FIXED, 'Flower Paradise dungeon HP corrected'),
    new Changelog(changelogType.FIXED, 'Route 40 should no longer unlock before reaching it'),
    new Changelog(changelogType.FIXED, 'Reduce some checks firing too often'),
    new Changelog(changelogType.FIXED, 'Game controls will be ignored if focused on an input element'),
    new Changelog(changelogType.FIXED, 'Backgrounds should no longer overflow in breeding modal'),

    // v0.5.2
    new ChangelogUpdate('v0.5.2', new Date(2020, 8, 10)),
    new Changelog(changelogType.NEW, 'Underground quest line created'),
    new Changelog(changelogType.NEW, 'More statistics added'),
    new Changelog(changelogType.NEW, 'Some minor Discord integration'),
    new Changelog(changelogType.CHANGE, 'Attack achievement no longer based on current region'),
    new Changelog(changelogType.CHANGE, 'Modified the way game ticks are handled'),
    new Changelog(changelogType.FIXED, 'Fixed breeding filter displayed options being reset after hatchery filled up'),

    // v0.5.1
    new ChangelogUpdate('v0.5.1', new Date(2020, 7, 31)),
    new Changelog(changelogType.NEW, 'Added a notification for when the game has an update available'),
    new Changelog(changelogType.NEW, 'Add Croagunk to Route 212'),
    new Changelog(changelogType.CHANGE, 'Move Hippopotas from Route 210 → Route 214'),
    new Changelog(changelogType.CHANGE, 'Updated Fight Area requirements'),
    new Changelog(changelogType.CHANGE, 'Buffed Erika Victreebel'),
    new Changelog(changelogType.FIXED, 'Unobtainable items will no longer remain in the Underground'),
    new Changelog(changelogType.FIXED, 'Pacifidlog town shop now available'),
    new Changelog(changelogType.FIXED, 'Hide alternate forms from Pokédex that have not yet been caught'),
    new Changelog(changelogType.FIXED, 'Shaymin (sky) form types corrected'),

    // v0.5.0 - Sinnoh
    new ChangelogUpdate('v0.5.0 - Sinnoh', new Date(2020, 7, 28)),
    new Changelog(changelogType.NEW, 'The Sinnoh region is now available'),
    new Changelog(changelogType.NEW, 'New evolution stones'),
    new Changelog(changelogType.NEW, 'Dungeon based evolutions'),
    new Changelog(changelogType.NEW, 'Time based evolutions'),
    new Changelog(changelogType.NEW, '2 new fossils added to the Underground'),
    new Changelog(changelogType.NEW, 'Pokémon alternate forms can now be obtained'),
    new Changelog(changelogType.CHANGE, 'Decrease attack reduction in newer regions'),
    new Changelog(changelogType.CHANGE, 'All Happiness/Friendship evolutions now make use of the Soothe Bell'),
    new Changelog(changelogType.CHANGE, 'Added base exp per quest completed'),
    new Changelog(changelogType.CHANGE, 'Updated the order Routes, Dungeons and Gyms need to be completed in the Kanto region'),
    new Changelog(changelogType.FIXED, 'Gyms should award correct amount of Egg steps now'),
    new Changelog(changelogType.REMOVED, 'Removed Time Stone'),
    new Changelog(changelogType.REMOVED, 'Removed hold evolution items from the Underground'),

    // v0.4.20
    new ChangelogUpdate('v0.4.20 - Battle Frontier', new Date(2020, 7, 18)),
    new Changelog(changelogType.NEW, 'Added the Battle Frontier in the Hoenn region'),
    new Changelog(changelogType.CHANGE, 'Buffed Dungeon Token gain in higher regions'),
    new Changelog(changelogType.CHANGE, 'Updated the order Routes, Dungeons and Gyms need to be completed in the Johto region'),
    new Changelog(changelogType.CHANGE, 'Updated the order Routes, Dungeons and Gyms need to be completed in the Kanto region'),
    new Changelog(changelogType.FIXED, 'Questline progress restored correctly'),

    // v0.4.19
    new ChangelogUpdate('v0.4.19', new Date(2020, 7, 15)),
    new Changelog(changelogType.NEW, 'Filters added to the Day Care'),
    new Changelog(changelogType.NEW, 'Achievements available for all regions'),
    new Changelog(changelogType.CHANGE, 'Buffed bonus for the Cell Battery'),
    new Changelog(changelogType.CHANGE, 'Sounds will now play if enabled even if the notification is disabled'),

    // v0.4.18
    new ChangelogUpdate('v0.4.18 - Underground', new Date(2020, 7, 10)),
    new Changelog(changelogType.NEW, 'Added Prospect ability to the Underground to see which types of items are in the current layer'),
    new Changelog(changelogType.NEW, 'Added Bomb ability to the Underground which will mine random tiles for you'),
    new Changelog(changelogType.NEW, 'Added ability to Skip layers in the Underground'),
    new Changelog(changelogType.NEW, 'Added ability to sell/trade multiple items at once in the Underground'),
    new Changelog(changelogType.NEW, 'Added volume control for notification sounds'),
    new Changelog(changelogType.NEW, 'Some Pokémon now have a chance to drop rare items upon defeat'),
    new Changelog(changelogType.NEW, 'Added Pokédex filter for Pokémon that drop rare items'),
    new Changelog(changelogType.NEW, 'Added Deoxys quest line'),
    new Changelog(changelogType.CHANGE, 'Deoxys no longer roaming'),
    new Changelog(changelogType.CHANGE, 'Separate Day Care modal into individual tabs for Pokémon, Eggs and Fossils'),
    new Changelog(changelogType.CHANGE, 'Update modal displays'),
    new Changelog(changelogType.FIXED, 'Event Pokémon no longer displayed in Pokédex'),
    new Changelog(changelogType.FIXED, 'Reduce memory usage in Underground'),

    // v0.4.17
    new ChangelogUpdate('v0.4.17', new Date(2020, 7, 6)),
    new Changelog(changelogType.NEW, 'Update maps'),
    new Changelog(changelogType.NEW, 'Add notification settings'),
    new Changelog(changelogType.NEW, 'Add more notification sounds and settings'),
    new Changelog(changelogType.NEW, 'Can now filter the Pokédex by pure type Pokémon by selecting None for the second type'),
    new Changelog(changelogType.NEW, 'Added statistic for Hatched Shiny Pokémon'),
    new Changelog(changelogType.NEW, 'Caught indicator on eggs showing if you have obtained all the Pokémon available in that egg type'),
    new Changelog(changelogType.CHANGE, 'Move some dungeons to be standalone'),
    new Changelog(changelogType.FIXED, 'Safari Zone should no longer lock up'),
    new Changelog(changelogType.FIXED, 'Event Pokémon can now evolve'),
    new Changelog(changelogType.FIXED, 'Helix fossil now displays correctly when mining in the Underground'),

    // v0.4.16
    new ChangelogUpdate('v0.4.16', new Date(2020, 6, 30)),
    new Changelog(changelogType.NEW, 'Added sounds for specific events'),
    new Changelog(changelogType.NEW, 'Added more settings'),
    new Changelog(changelogType.NEW, 'New maps'),
    new Changelog(changelogType.CHANGE, 'Updated settings menu'),
    new Changelog(changelogType.CHANGE, 'Shops will now only show the balance of currencies used there'),
    new Changelog(changelogType.CHANGE, 'Gyms and Dungeons in the Johto and Hoenn regions have been buffed'),

    // v0.4.15
    new ChangelogUpdate('v0.4.15', new Date(2020, 6, 27)),
    new Changelog(changelogType.NEW, 'Eggs now have multiple different styles'),
    new Changelog(changelogType.CHANGE, 'xExp is now the Lucky Egg'),
    new Changelog(changelogType.CHANGE, 'Updated Currency, Item, Berry, Egg and Fossil images'),
    new Changelog(changelogType.CHANGE, 'Day Care is now unlocked once you defeat Route 5'),
    new Changelog(changelogType.CHANGE, 'Fossils will now show in the Hatchery'),
    new Changelog(changelogType.CHANGE, 'Update Farm layout for smaller displays'),
    new Changelog(changelogType.CHANGE, 'Update Safari Zone cost'),
    new Changelog(changelogType.CHANGE, 'Underground now shows the 3 x 3 area which will be mined when using the hammer'),
    new Changelog(changelogType.FIXED, 'Underground total items should now be correct'),

    // v0.4.14
    new ChangelogUpdate('v0.4.14', new Date(2020, 6, 22)),
    new Changelog(changelogType.NEW, 'Added Dratini to Route 45'),
    new Changelog(changelogType.NEW, 'Underground should now work better on smaller screens'),
    new Changelog(changelogType.CHANGE, 'Enlarge buttons in Shortcut menu, Safari Zone'),
    new Changelog(changelogType.CHANGE, 'Make Shop items fit better'),
    new Changelog(changelogType.CHANGE, 'Breeding display takes up less space on smaller screens now'),
    new Changelog(changelogType.CHANGE, 'Add confirmation when refreshing quest list'),
    new Changelog(changelogType.FIXED, 'Update Oak items tooltip when upgraded'),
    new Changelog(changelogType.FIXED, 'Auto refresh Daily Deals when upgrade purchased'),

    // v0.4.13
    new ChangelogUpdate('v0.4.13', new Date(2020, 6, 20)),
    new Changelog(changelogType.NEW, 'Added shortcut module'),
    new Changelog(changelogType.NEW, 'Added Poké Mart to shortcuts module'),
    new Changelog(changelogType.CHANGE, 'Updated Masterball pricing'),
    new Changelog(changelogType.CHANGE, 'Allow the game to continue running while Day Care is open'),
    new Changelog(changelogType.CHANGE, 'Allow the game to continue running while Underground is open'),
    new Changelog(changelogType.CHANGE, 'Don\'t send the player back to Route 11 when leaving the Underground'),
    new Changelog(changelogType.CHANGE, 'Allow the game to continue running while Farm is open'),
    new Changelog(changelogType.CHANGE, 'Don\'t send the player back to Route 14 when leaving the Farm'),
    new Changelog(changelogType.CHANGE, 'Added button to open Dock for cities located nearby'),
    new Changelog(changelogType.CHANGE, 'Moved shiny icon further into the corner in the Day Care view, to make it easier to spot already shiny Pokémon'),
    new Changelog(changelogType.CHANGE, 'Dungeon size scales depending on region'),

    // v0.4.12
    new ChangelogUpdate('v0.4.12', new Date(2020, 6, 18)),
    new Changelog(changelogType.NEW, 'Modules can now be sorted/arranged any way you like, just drag and drop'),
    new Changelog(changelogType.NEW, 'Added confirmation when quiting a quest'),
    new Changelog(changelogType.CHANGE, 'Updated dungeon token cost in Hoenn dungeons'),
    new Changelog(changelogType.CHANGE, 'Updated the gym fight view'),
    new Changelog(changelogType.CHANGE, 'Updated some messages shown when you cannot access a location yet'),
    new Changelog(changelogType.FIXED, 'Some battle background images were not showing, they should now appear correctly'),
    new Changelog(changelogType.FIXED, 'Town Map will now be fully hidden when it is supposed to be'),

    // v0.4.11
    new ChangelogUpdate('v0.4.11', new Date(2020, 6, 16)),
    new Changelog(changelogType.NEW, 'Towns will show as orange if you have not yet completed the gym'),
    new Changelog(changelogType.NEW, 'Map is able to be hidden now'),
    new Changelog(changelogType.NEW, 'Added mobile support to the Safari Zone'),
    new Changelog(changelogType.CHANGE, 'The Cell Battery Oak Item will now gain points each time you find an item'),
    new Changelog(changelogType.CHANGE, 'Updated the layout of the Shard modal'),
    new Changelog(changelogType.CHANGE, 'Updated the layout of the Safari Zone'),
    new Changelog(changelogType.FIXED, 'Stone evolutions will now only show the Pokéball if all possible evolutions have been caught'),

    // v0.4.10
    new ChangelogUpdate('v0.4.10 - Minor update', new Date(2020, 6, 15)),
    new Changelog(changelogType.NEW, 'Added preload progress indicator'),
    new Changelog(changelogType.NEW, 'Game will still load if not all the images preload correctly'),

    // v0.4.9
    new ChangelogUpdate('v0.4.9', new Date(2020, 6, 14)),
    new Changelog(changelogType.NEW, 'Added option to disable found berries notifications'),
    new Changelog(changelogType.NEW, 'Added different background images when battling Pokémon depending on route/dungeon'),
    new Changelog(changelogType.CHANGE, 'Updated Bootstrap, TypeScript and other dependencies, please report any problems you may notice'),
    new Changelog(changelogType.CHANGE, 'Limit maximum Quest Points for Dungeon and Gym quests'),
    new Changelog(changelogType.CHANGE, 'Updated quest list layout'),
    new Changelog(changelogType.CHANGE, 'Format numbers in shop and Pokéball selector'),
    new Changelog(changelogType.FIXED, 'Dungeons should now award Dungeon Tokens when catching a Pokémon'),
    new Changelog(changelogType.FIXED, 'Badge names should display correctly now'),

    // v0.4.8
    new ChangelogUpdate('v0.4.8', new Date(2020, 6, 12)),
    new Changelog(changelogType.NEW, 'More events'),
    new Changelog(changelogType.NEW, 'Added caught status indicator to Safari Zone entrance'),
    new Changelog(changelogType.NEW, 'Added caught status indicator to Dungeons'),
    new Changelog(changelogType.CHANGE, 'Show Oak Item details on hover on main screen'),
    new Changelog(changelogType.CHANGE, 'Updated Oak Items modal to show current experience on hover'),
    new Changelog(changelogType.CHANGE, 'Animate town and dungeon background images'),
    new Changelog(changelogType.CHANGE, 'Updated battle views of routes and dungeons'),
    new Changelog(changelogType.FIXED, 'Event notifications showing way before event start'),
    new Changelog(changelogType.FIXED, 'Reduce lag when hatching Pokémon'),

    // v0.4.7
    new ChangelogUpdate('v0.4.7 - Layout', new Date(2020, 6, 9)),
    new Changelog(changelogType.NEW, 'Added option to sort Pokémon list by base attack'),
    new Changelog(changelogType.CHANGE, 'Added information and confirmation check before traveling to next available region'),
    new Changelog(changelogType.CHANGE, 'Updated the Oak Items layout'),
    new Changelog(changelogType.CHANGE, 'Updated layout of Towns and Dungeons'),
    new Changelog(changelogType.CHANGE, 'Updated the Hoenn map'),
    new Changelog(changelogType.CHANGE, 'Show the amount of Pokémon visible in Pokédex with filters active'),
    new Changelog(changelogType.FIXED, 'Event Pokémon no longer count towards achievements or being able to travel to next region'),
    new Changelog(changelogType.FIXED, 'Mt. Chimney dungeon is now more powerful'),

    // v0.4.6
    new ChangelogUpdate('v0.4.6 - Bug fixes', new Date(2020, 6, 7)),
    new Changelog(changelogType.NEW, 'Old save can be backed up when the game updates incase anything goes wrong<br/><i>You can disable auto download in the settings</i>'),
    new Changelog(changelogType.NEW, 'Add events modal'),
    new Changelog(changelogType.CHANGE, 'Safari now uses a Safari Ball'),
    new Changelog(changelogType.CHANGE, 'Added ability to track event Pokémon statistics'),
    new Changelog(changelogType.CHANGE, 'Update Discord link'),
    new Changelog(changelogType.FIXED, 'Pokéball should appear in dungeons again'),
    new Changelog(changelogType.FIXED, 'Fix Eeveelutions'),

    // v0.4.5
    new ChangelogUpdate('v0.4.5 - Special events', new Date(2020, 6, 5)),
    new Changelog(changelogType.EVENT, 'Flying Pikachu Event'),
    new Changelog(changelogType.NEW, 'Special events can now appear in game'),
    new Changelog(changelogType.CHANGE, 'Modified the look of the dock'),
    new Changelog(changelogType.CHANGE, 'Always add caught Shiny Pokémon to the Log Book'),
    new Changelog(changelogType.CHANGE, 'Added close button on the top right of more modals'),
    new Changelog(changelogType.FIXED, 'Dungeon layout should be shuffled again'),
    new Changelog(changelogType.FIXED, 'Hopefully fixed some values becoming NaN'),

    // v0.4.4
    new ChangelogUpdate('v0.4.4 - Statistics 2.0', new Date(2020, 6, 4)),
    new Changelog(changelogType.NEW, 'Add some new game codes'),
    new Changelog(changelogType.NEW, 'Statistics can now be viewed from the Start Menu'),
    new Changelog(changelogType.NEW, 'Pokémon statistics can be viewed by clicking a Pokémon in the Pokédex'),
    new Changelog(changelogType.CHANGE, 'Update some game codes'),
    new Changelog(changelogType.REMOVED, 'Remove old game codes'),
    new Changelog(changelogType.FIXED, 'Can no longer breed fossils from regions you have not reached yet'),
    new Changelog(changelogType.FIXED, 'Added missing notifications for stone evolution Pokémon'),

    // v0.4.3
    new ChangelogUpdate('v0.4.3', new Date(2020, 6, 3)),
    new Changelog(changelogType.NEW, 'Add setting to disable currency animations'),
    new Changelog(changelogType.CHANGE, 'Increase some notifications display time'),
    new Changelog(changelogType.CHANGE, 'Decreased price multiplier'),
    new Changelog(changelogType.CHANGE, 'Modified Pokémon list reverse checkbox to show arrows instead'),
    new Changelog(changelogType.CHANGE, 'Updated changelog layout'),
    new Changelog(changelogType.FIXED, 'Fix LilyCove City naming and image'),
    new Changelog(changelogType.FIXED, 'Tidy up Key items, Evolution stones selector'),
    new Changelog(changelogType.FIXED, 'Sketchy theme checkboxes and close icons should display correctly now'),

    // v0.4.2
    new ChangelogUpdate('v0.4.2', new Date(2020, 6, 3)),
    new Changelog(changelogType.FIXED, 'Fixed some Key items not being given when supposed to'),

    // v0.4.1
    new ChangelogUpdate('v0.4.1 - More fixes', new Date(2020, 6, 3)),
    new Changelog(changelogType.NEW, 'More items added to underground'),
    new Changelog(changelogType.CHANGE, 'All Hoenn Pokémon should be obtainable now'),
    new Changelog(changelogType.FIXED, 'Pokédex filtering should be working again'),
    new Changelog(changelogType.FIXED, 'Some items showing _ in their name in notifications'),

    // v0.4.0
    new ChangelogUpdate('v0.4.0 - Statistics update', new Date(2020, 6, 2)),
    new Changelog(changelogType.NEW, 'Current save data should be compatible with future versions!'),
    new Changelog(changelogType.NEW, 'More statistics have been added'),
    new Changelog(changelogType.CHANGE, 'Updated the way statistics are stored'),
    new Changelog(changelogType.CHANGE, 'Updated notifications'),
    new Changelog(changelogType.FIXED, 'Fix some missing Hoenn Pokémon'),
    new Changelog(changelogType.FIXED, 'Fix some missing images'),

    // v0.3.1
    new ChangelogUpdate('v0.3.1 - Bug catcher', new Date(2020, 6, 1)),
    new Changelog(changelogType.CHANGE, 'Eevee will now evolve into Espeon or Umbreon depending on the time of day (when using Time stone)'),
    new Changelog(changelogType.FIXED, 'Can no longer evolve Magmar and Electabuzz before you are allowed'),
    new Changelog(changelogType.FIXED, 'Fix breeding steps gained for newer regions'),
    new Changelog(changelogType.FIXED, 'Fix roaming encounters for newer regions'),
    new Changelog(changelogType.FIXED, 'Fix route rewards for newer regions'),

    // v0.3.0
    new ChangelogUpdate('v0.3.0 - Hoenn Update', new Date(2020, 5, 30)),
    new Changelog(changelogType.NEW, 'Add initial Hoenn region'),
    new Changelog(changelogType.CHANGE, 'Shiny Pokémon now increase click damage at a 50% rate compared to normal Pokémon'),
    new Changelog(changelogType.CHANGE, 'Allow better control of which type of ball to use when capturing a Pokémon'),

    // v0.2.1
    new ChangelogUpdate('v0.2.1', new Date(2020, 0, 13)),
    new Changelog(changelogType.REMOVED, 'Remove Hoenn dungeons for now to avoid triggering errors'),
    new Changelog(changelogType.FIXED, 'Other berries will now be tasked in Quests'),

    // v0.2.0
    new ChangelogUpdate('v0.2.0 - Redeemable codes', new Date(2020, 0, 12)),
    new Changelog(changelogType.NEW, 'Add redeemable codes to get a quick boost. You can enter them under the Save tab'),
    new Changelog(changelogType.FIXED, 'Gyms no longer reset 1 second in'),

    // v0.1.0
    new ChangelogUpdate('v0.1.0 - Farming refactor', new Date(2020, 0, 12)),
    new Changelog(changelogType.CHANGE, 'Farming plots are a bit more expensive'),
    new Changelog(changelogType.CHANGE, 'Wailmer pail unlocks at 3 Cheri berries instead of 5'),
    new Changelog(changelogType.FIXED, 'Tooltips no longer overstay their welcome on the Farm'),

    // v0.0.5
    new ChangelogUpdate('v0.0.5', new Date(2020, 0, 9)),
    new Changelog(changelogType.NEW, 'Can now use spacebar to start Gym/Dungeon'),
    new Changelog(changelogType.FIXED, 'Stones now work with multiple evolutions'),
    new Changelog(changelogType.FIXED, 'Pokémon will no longer evolve into evolutions you have already obtained'),
    new Changelog(changelogType.FIXED, 'Can obtain Pokémon from future generations by re-breeding'),
    new Changelog(changelogType.FIXED, 'Devolutions are obtained when breeding evolved forms'),
    new Changelog(changelogType.NEW, 'Add setting to toggle egg percentage/step count'),
    new Changelog(changelogType.CHANGE, 'Total shiny Pokémon caught no longer adds to your click attack'),
    new Changelog(changelogType.CHANGE, 'Halve xp needed to upgrade Oak items'),
    new Changelog(changelogType.FIXED, 'BattleItems now buy correctly'),
    new Changelog(changelogType.CHANGE, 'Increase dungeon tokens received when catching Pokémon'),
    new Changelog(changelogType.CHANGE, 'Going to the breeder will no longer send you to route 5'),
    new Changelog(changelogType.CHANGE, 'You will now start the game with 25 Pokéballs'),
    new Changelog(changelogType.CHANGE, 'Tutorial quest buy Pokéballs amount reduced'),
    new Changelog(changelogType.FIXED, 'Selecting "max" in store will no longer freeze the game for key items'),

    // v0.0.4 - 01-01-2020
    new ChangelogUpdate('v0.0.4', new Date(2019, 11, 22)),
    new Changelog(changelogType.NEW, 'Show Pokéball image by caught Pokémon in the Pokédex'),
    new Changelog(changelogType.CHANGE, 'Show the reason you cannot access a location'),
    new Changelog(changelogType.CHANGE, 'Total shiny Pokémon caught now add to your total click attack'),
    new Changelog(changelogType.FIXED, 'Display floored dungeon tokens amount'),

    // v0.0.3
    new ChangelogUpdate('v0.0.3', new Date(2019, 11, 17)),
    new Changelog(changelogType.NEW, 'Can now progress in multiple quest at a time <i>(amount based on Quest Level)</i>'),
    new Changelog(changelogType.NEW, 'Side cards can now be collapsed for more space'),
    new Changelog(changelogType.CHANGE, 'Move battle item container'),
    new Changelog(changelogType.CHANGE, 'Update how achievement percentages are shown'),
    new Changelog(changelogType.CHANGE, 'Update hatch/catch notification message'),
    new Changelog(changelogType.FIXED, 'Show the hatchery "list" button once Johto unlocked without page refresh'),
    new Changelog(changelogType.FIXED, 'Plates from underground should now sell for their correct value'),

    // v0.0.2
    new ChangelogUpdate('v0.0.2', new Date(2019, 11, 16)),
    new Changelog(changelogType.NEW, 'Added changelog'),
    new Changelog(changelogType.CHANGE, 'Show battle item names and descriptions'),
    new Changelog(changelogType.FIXED, 'Item magnet now works in dungeons'),
    new Changelog(changelogType.FIXED, 'Battle items no longer always active'),

    // v0.0.1
    new ChangelogUpdate('v0.0.1', new Date(2019, 11, 16)),
    new Changelog(changelogType.NEW, 'Add battle items'),
];

export default ChangelogItems;
