enum BadgeEnums {
    'None',
    // Kanto
    'Boulder',
    'Cascade',
    'Thunder',
    'Rainbow',
    'Soul',
    'Marsh',
    'Volcano',
    'Earth',
    'Elite_Lorelei',
    'Elite_Bruno',
    'Elite_Agatha',
    'Elite_Lance',
    'Elite_KantoChampion',
    // Johto
    'Zephyr',
    'Hive',
    'Plain',
    'Fog',
    'Storm',
    'Mineral',
    'Glacier',
    'Rising',
    'Elite_Will',
    'Elite_Koga',
    'Elite_Bruno2',
    'Elite_Karen',
    'Elite_JohtoChampion',
    // Hoenn
    'Stone',
    'Knuckle',
    'Dynamo',
    'Heat',
    'Balance',
    'Feather',
    'Mind',
    'Rain',
    'Elite_Sidney',
    'Elite_Phoebe',
    'Elite_Glacia',
    'Elite_Drake',
    'Elite_HoennChampion',
    // Orange league
    'Coral-Eye',
    'Sea_Ruby',
    'Spike_Shell',
    'Jade_Star',
    'Elite_OrangeChampion',
    // Orre
    'Elite_F_Disk',
    'Elite_L_Disk',
    'Elite_R_Disk',
    'Elite_U_Disk',
    'Elite_ColosseumLovrina',
    'Elite_ColosseumSnattle',
    'Elite_ColosseumGorigan',
    'Elite_ColosseumArdos',
    'Elite_ColosseumEldes',
    // Sinnoh
    'Coal',
    'Forest',
    'Relic',
    'Cobble',
    'Fen',
    'Mine',
    'Icicle',
    'Beacon',
    'Elite_Aaron',
    'Elite_Bertha',
    'Elite_Flint',
    'Elite_Lucian',
    'Elite_SinnohChampion',
    // Unova
    'Basic',
    'Toxic',
    'Insect',
    'Bolt',
    'Quake',
    'Jet',
    'Legend',
    'Wave',
    'Elite_Shauntal',
    'Elite_Marshal',
    'Elite_Grimsley',
    'Elite_Caitlin',
    'Elite_UnovaChampion',
    // Kalos
    'Bug',
    'Cliff',
    'Rumble',
    'Plant',
    'Voltage',
    'Fairy',
    'Psychic',
    'Iceberg',
    'Elite_Malva',
    'Elite_Siebold',
    'Elite_Wikstrom',
    'Elite_Drasna',
    'Elite_KalosChampion',
    // Alola
    // TODO: these are unordered and some may be missing
    'Melemele_Stamp',
    'Akala_Stamp',
    'Ula_Ula_Stamp',
    'Poni_Stamp',
    'Elite_Olivia',
    'Elite_Acerola',
    'Elite_Molayne',
    'Elite_Kahili',
    'Champion_Stamp',
    // Magikarp Jump
    'Friend_League',
    'Quick_League',
    'Heavy_League',
    'Great_League',
    'Fast_League',
    'Luxury_League',
    'Heal_League',
    'Ultra_League',
    'E4_League',
    'Master_League',
    // Galar
    'Galar_Grass',
    'Galar_Water',
    'Galar_Fire',
    'Galar_Fighting',
    'Galar_Ghost',
    'Galar_Fairy',
    'Galar_Rock',
    'Galar_Ice',
    'Galar_Dark',
    'Galar_Dragon',
    'Elite_Marnie',
    'Elite_Bede',
    'Elite_Hop',
    'Elite_GalarChampion',
    // Armor
    'Elite_ArmorPoison',
    'Elite_ArmorPsychic',
    'Elite_ArmorMatron',
    'Elite_ArmorChampion',
    // Crown
    'Elite_CrownChampion',
    // Hisui
    'Noble_Kleavor',
    'Noble_Lilligant',
    'Noble_Arcanine',
    'Noble_Electrode',
    'Noble_Avalugg',
    'Azure',
    //Paldea Victory Road
    'Bug_Gym',
    'Grass_Gym',
    'Electric_Gym',
    'Water_Gym',
    'Normal_Gym',
    'Ghost_Gym',
    'Psychic_Gym',
    'Ice_Gym',
    'Elite_Rika',
    'Elite_Poppy',
    'Elite_Larry',
    'Elite_Hassel',
    'Elite_PaldeaChampion',
    'Elite_Nemona',
    // Starfall Street
    'Dark_Star',
    'Fire_Star',
    'Poison_Star',
    'Fairy_Star',
    'Fighting_Star',
    'Elite_Clavell',
    'Elite_Penny',
    // Path of Legends
    'Rock_Titan',
    'Flying_Titan',
    'Steel_Titan',
    'Ground_Titan',
    'Dragon_Titan',
    'Elite_Arven',
    // The Way Home
    'Scarlet',
    'Violet',
}

export default BadgeEnums;
