enum BadgeEnums {
    'None',
    // Kanto
    'Boulder',
    'Cascade',
    'Thunder',
    'Rainbow',
    'Soul',
    'Marsh',
    'Volcano',
    'Earth',
    'Elite_Lorelei',
    'Elite_Bruno',
    'Elite_Agatha',
    'Elite_Lance',
    'Elite_KantoChampion',
    // Johto
    'Zephyr',
    'Hive',
    'Plain',
    'Fog',
    'Storm',
    'Mineral',
    'Glacier',
    'Rising',
    'Elite_Will',
    'Elite_Koga',
    'Elite_Bruno2',
    'Elite_Karen',
    'Elite_JohtoChampion',
    // Hoenn
    'Stone',
    'Knuckle',
    'Dynamo',
    'Heat',
    'Balance',
    'Feather',
    'Mind',
    'Rain',
    'Elite_Sidney',
    'Elite_Phoebe',
    'Elite_Glacia',
    'Elite_Drake',
    'Elite_HoennChampion',
    // Orange league
    'Coral-Eye',
    'Sea_Ruby',
    'Spike_Shell',
    'Jade_Star',
    'Elite_OrangeChampion',
    // Sinnoh
    'Coal',
    'Forest',
    'Relic',
    'Cobble',
    'Fen',
    'Mine',
    'Icicle',
    'Beacon',
    'Elite_Aaron',
    'Elite_Bertha',
    'Elite_Flint',
    'Elite_Lucian',
    'Elite_SinnohChampion',
    // Unova
    'Basic',
    'Toxic',
    'Insect',
    'Bolt',
    'Quake',
    'Jet',
    'Legend',
    'Wave',
    'Elite_Shauntal',
    'Elite_Marshal',
    'Elite_Grimsley',
    'Elite_Caitlin',
    'Elite_UnovaChampion',
    // Kalos
    'Bug',
    'Cliff',
    'Rumble',
    'Plant',
    'Voltage',
    'Fairy',
    'Psychic',
    'Iceberg',
    'Elite_Malva',
    'Elite_Siebold',
    'Elite_Wikstrom',
    'Elite_Drasna',
    'Elite_KalosChampion',
    // Alola
    // TODO: these are unordered and some may be missing
    'NormaliumZ',
    'FightiniumZ',
    'WateriumZ',
    'FiriumZ',
    'GrassiumZ',
    'RockiumZ',
    'ElectriumZ',
    'GhostiumZ',
    'DarkiniumZ',
    'DragoniumZ',
    'FairiumZ',
    'GroundiumZ',
    'Elite_Olivia',
    'Elite_Acerola',
    'Elite_Molayne',
    'Elite_Kahili',
    'Elite_AlolaChampion',
    // Magikarp Jump
    'Friend_League',
    'Quick_League',
    'Heavy_League',
    'Great_League',
    'Fast_League',
    'Luxury_League',
    'Heal_League',
    'Ultra_League',
    'E4_League',
    'Master_League',
    // Galar
    'Galar_Grass',
    'Galar_Water',
    'Galar_Fire',
    'Galar_Fighting',
    'Galar_Ghost',
    'Galar_Fairy',
    'Galar_Rock',
    'Galar_Ice',
    'Galar_Dark',
    'Galar_Dragon',
    'Elite_Marnie',
    'Elite_Bede',
    'Elite_Hop',
    'Elite_GalarChampion',
    // Armor
    'Elite_ArmorPoison',
    'Elite_ArmorPsychic',
    'Elite_ArmorMatron',
    'Elite_ArmorChampion',
    // Crown
    'Elite_CrownChampion',
}

export default BadgeEnums;
