enum KeyItemType {
    'Teachy_tv' = 0,
    'Coin_case',
    'Pokeball_bag',
    'Town_map',
    'Dungeon_ticket',
    'Super_rod',
    'Fishing_rod',
    'HM03_surf',
    'TM02_headbutt',
    'Go_goggles',
    'HM08_dive',
    'Holo_caster',
    'Mystery_egg',
    'Safari_ticket',
    'Wailmer_pail',
    'Explorer_kit',
    'Eon_ticket',
    'Event_calendar',
    'Gem_case',
    'DNA_splicers',
    'Reins_of_unity',
    'Pokerus_virus',
    'Z-Power_Ring',
}

export default KeyItemType;
