enum RibbonEnums {
    'None',
    // Champ Ribbons (placeholders, so we don't need to update in case we want to use them)
    'Champion',
    'Legend',
    'Hoenn Champion',
    'Sinnoh Champion',
    'Unova Champion',
    'Kalos Champion',
    'Alola Champion',
    'Galar Champion',
    'Pioneer',
    'Paldea Champion',
    'Spoilers',
    // Hoenn
    'Normal Cool',
    'Normal Beautiful',
    'Normal Cute',
    'Normal Smart',
    'Normal Tough',
    'Super Cool',
    'Super Beautiful',
    'Super Cute',
    'Super Smart',
    'Super Tough',
    'Hyper Cool',
    'Hyper Beautiful',
    'Hyper Cute',
    'Hyper Smart',
    'Hyper Tough',
    'Master Cool',
    'Master Beautiful',
    'Master Cute',
    'Master Smart',
    'Master Tough',
    // Sinnoh
    'Super Normal Cool',
    'Super Normal Beautiful',
    'Super Normal Cute',
    'Super Normal Smart',
    'Super Normal Tough',
    'Super Great Cool',
    'Super Great Beautiful',
    'Super Great Cute',
    'Super Great Smart',
    'Super Great Tough',
    'Super Ultra Cool',
    'Super Ultra Beautiful',
    'Super Ultra Cute',
    'Super Ultra Smart',
    'Super Ultra Tough',
    'Super Master Cool',
    'Super Master Beautiful',
    'Super Master Cute',
    'Super Master Smart',
    'Super Master Tough',
    // Spectacular
    'Spectacular Cool',
    'Spectacular Beautiful',
    'Spectacular Cute',
    'Spectacular Smart',
    'Spectacular Tough',
    'Spectacular Star',
    // Brilliant Shining
    'Brilliant Shining Star',
}

export default RibbonEnums;
