enum RibbonEnums {
    'None',
    // Champ Ribbons (placeholders, so we don't need to update in case we want to use them)
    'Champion',
    'Legend',
    'Hoenn Champion',
    'Sinnoh Champion',
    'Unova Champion',
    'Kalos Champion',
    'Alola Champion',
    'Galar Champion',
    'Pioneer',
    'Paldea Champion',
    'Spoilers',
    // Hoenn
    'Cool',
    'Beauty',
    'Cute',
    'Smart',
    'Tough',
    'Cool Super',
    'Beauty Super',
    'Cute Super',
    'Smart Super',
    'Tough Super',
    'Cool Hyper',
    'Beauty Hyper',
    'Cute Hyper',
    'Smart Hyper',
    'Tough Hyper',
    'Cool Master',
    'Beauty Master',
    'Cute Master',
    'Smart Master',
    'Tough Master',
    // Sinnoh
    'Super Cool',
    'Super Beauty',
    'Super Cute',
    'Super Smart',
    'Super Tough',
    'Super Cool Great',
    'Super Beauty Great',
    'Super Cute Great',
    'Super Smart Great',
    'Super Tough Great',
    'Super Cool Ultra',
    'Super Beauty Ultra',
    'Super Cute Ultra',
    'Super Smart Ultra',
    'Super Tough Ultra',
    'Super Cool Master',
    'Super Beauty Master',
    'Super Cute Master',
    'Super Smart Master',
    'Super Tough Master',
    // Spectacular
    'Coolness Master',
    'Beautifulness Master',
    'Cuteness Master',
    'Cleverness Master',
    'Toughness Master',
    'Contest Star',
    // Brilliant and Shining
    'Twinkling Star',
}

export default RibbonEnums;
