import { Pattern } from '../UndergroundBattery';

export const batteryPatternDracoMeteor: Pattern = [
    [
        { coordinate:{ x:11, y:4 }, depth: 4 },
        { coordinate:{ x:10, y:5 }, depth: 4 },
        { coordinate:{ x:12, y:5 }, depth: 4 },
        { coordinate:{ x:11, y:6 }, depth: 4 },
    ],
    null,
    null,
    [
        { coordinate:{ x:10, y:4 }, depth: 3 },
        { coordinate:{ x:12, y:4 }, depth: 3 },
        { coordinate:{ x:11, y:5 }, depth: 5 },
        { coordinate:{ x:10, y:6 }, depth: 3 },
        { coordinate:{ x:12, y:6 }, depth: 3 },
    ],
    null,
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:1, y:10 }, depth: 5 },
    ],
    [
        { coordinate:{ x:1, y:9 }, depth: 4 },
        { coordinate:{ x:0, y:10 }, depth: 4 },
        { coordinate:{ x:2, y:10 }, depth: 4 },
        { coordinate:{ x:1, y:11 }, depth: 4 },
    ],
    null,
    null,
    [
        { coordinate:{ x:0, y:9 }, depth: 3 },
        { coordinate:{ x:2, y:9 }, depth: 3 },
        { coordinate:{ x:0, y:11 }, depth: 3 },
        { coordinate:{ x:2, y:11 }, depth: 3 },
    ],
    null,
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:17, y:9 }, depth: 5 },
    ],
    [
        { coordinate:{ x:17, y:8 }, depth: 4 },
        { coordinate:{ x:16, y:9 }, depth: 4 },
        { coordinate:{ x:18, y:9 }, depth: 4 },
        { coordinate:{ x:17, y:10 }, depth: 4 },
    ],
    null,
    null,
    [
        { coordinate:{ x:16, y:8 }, depth: 3 },
        { coordinate:{ x:18, y:8 }, depth: 3 },
        { coordinate:{ x:16, y:10 }, depth: 3 },
        { coordinate:{ x:18, y:10 }, depth: 3 },
    ],
    null,
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:8, y:1 }, depth: 5 },
    ],
    [
        { coordinate:{ x:8, y:0 }, depth: 4 },
        { coordinate:{ x:7, y:1 }, depth: 4 },
        { coordinate:{ x:9, y:1 }, depth: 4 },
        { coordinate:{ x:8, y:2 }, depth: 4 },
    ],
    null,
    null,
    [
        { coordinate:{ x:7, y:0 }, depth: 3 },
        { coordinate:{ x:9, y:0 }, depth: 3 },
        { coordinate:{ x:7, y:2 }, depth: 3 },
        { coordinate:{ x:9, y:2 }, depth: 3 },
    ],
    null,
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:17, y:1 }, depth: 5 },
    ],
    [
        { coordinate:{ x:17, y:0 }, depth: 4 },
        { coordinate:{ x:16, y:1 }, depth: 4 },
        { coordinate:{ x:18, y:1 }, depth: 4 },
        { coordinate:{ x:17, y:2 }, depth: 4 },
    ],
    null,
    null,
    [
        { coordinate:{ x:16, y:0 }, depth: 3 },
        { coordinate:{ x:18, y:0 }, depth: 3 },
        { coordinate:{ x:16, y:2 }, depth: 3 },
        { coordinate:{ x:18, y:2 }, depth: 3 },
    ],
    null,
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:6, y:10 }, depth: 5 },
    ],
    [
        { coordinate:{ x:6, y:9 }, depth: 4 },
        { coordinate:{ x:5, y:10 }, depth: 4 },
        { coordinate:{ x:7, y:10 }, depth: 4 },
        { coordinate:{ x:6, y:11 }, depth: 4 },
    ],
    null,
    null,
    [
        { coordinate:{ x:5, y:9 }, depth: 3 },
        { coordinate:{ x:7, y:9 }, depth: 3 },
        { coordinate:{ x:5, y:11 }, depth: 3 },
        { coordinate:{ x:7, y:11 }, depth: 3 },
    ],
    null,
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:0, y:0 }, depth: 5 },
    ],
    [
        { coordinate:{ x:1, y:0 }, depth: 4 },
        { coordinate:{ x:0, y:1 }, depth: 4 },
    ],
    null,
    null,
    [
        { coordinate:{ x:1, y:1 }, depth: 3 },
    ],
    null,
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:23, y:4 }, depth: 5 },
    ],
    [
        { coordinate:{ x:23, y:3 }, depth: 4 },
        { coordinate:{ x:22, y:4 }, depth: 4 },
        { coordinate:{ x:24, y:4 }, depth: 4 },
        { coordinate:{ x:23, y:5 }, depth: 4 },
    ],
    null,
    null,
    [
        { coordinate:{ x:22, y:3 }, depth: 3 },
        { coordinate:{ x:24, y:3 }, depth: 3 },
        { coordinate:{ x:22, y:5 }, depth: 3 },
        { coordinate:{ x:24, y:5 }, depth: 3 },
    ],
    null,
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:22, y:10 }, depth: 5 },
    ],
    [
        { coordinate:{ x:22, y:9 }, depth: 4 },
        { coordinate:{ x:21, y:10 }, depth: 4 },
        { coordinate:{ x:23, y:10 }, depth: 4 },
        { coordinate:{ x:22, y:11 }, depth: 4 },
    ],
    null,
    null,
    [
        { coordinate:{ x:21, y:9 }, depth: 3 },
        { coordinate:{ x:23, y:9 }, depth: 3 },
        { coordinate:{ x:21, y:11 }, depth: 3 },
        { coordinate:{ x:23, y:11 }, depth: 3 },
    ],
    null,
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:3, y:4 }, depth: 5 },
    ],
    [
        { coordinate:{ x:3, y:3 }, depth: 4 },
        { coordinate:{ x:2, y:4 }, depth: 4 },
        { coordinate:{ x:4, y:4 }, depth: 4 },
        { coordinate:{ x:3, y:5 }, depth: 4 },
    ],
    null,
    null,
    [
        { coordinate:{ x:2, y:3 }, depth: 3 },
        { coordinate:{ x:4, y:3 }, depth: 3 },
        { coordinate:{ x:2, y:5 }, depth: 3 },
        { coordinate:{ x:4, y:5 }, depth: 3 },
    ],
    null,
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:18, y:5 }, depth: 5 },
    ],
    [
        { coordinate:{ x:18, y:4 }, depth: 4 },
        { coordinate:{ x:17, y:5 }, depth: 4 },
        { coordinate:{ x:19, y:5 }, depth: 4 },
        { coordinate:{ x:18, y:6 }, depth: 4 },
    ],
    null,
    null,
    [
        { coordinate:{ x:17, y:4 }, depth: 3 },
        { coordinate:{ x:19, y:4 }, depth: 3 },
        { coordinate:{ x:17, y:6 }, depth: 3 },
        { coordinate:{ x:19, y:6 }, depth: 3 },
    ],
    null,
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:13, y:11 }, depth: 5 },
    ],
    [
        { coordinate:{ x:13, y:10 }, depth: 4 },
        { coordinate:{ x:12, y:11 }, depth: 4 },
        { coordinate:{ x:14, y:11 }, depth: 4 },
    ],
    [
        { coordinate:{ x:12, y:10 }, depth: 3 },
        { coordinate:{ x:14, y:10 }, depth: 3 },
    ],
];
