import { Pattern } from '../UndergroundBattery';

export const batteryPatternEruption: Pattern = [
    [
        { coordinate:{ x:1, y:1 }, depth: 4 },
    ],
    [
        { coordinate:{ x:1, y:0 }, depth: 2 },
        { coordinate:{ x:0, y:1 }, depth: 2 },
        { coordinate:{ x:2, y:1 }, depth: 2 },
        { coordinate:{ x:1, y:2 }, depth: 2 },
    ],
    [
        { coordinate:{ x:0, y:0 }, depth: 1 },
        { coordinate:{ x:2, y:0 }, depth: 1 },
        { coordinate:{ x:3, y:1 }, depth: 1 },
        { coordinate:{ x:0, y:2 }, depth: 1 },
        { coordinate:{ x:2, y:2 }, depth: 1 },
        { coordinate:{ x:1, y:3 }, depth: 1 },
    ],
    null,
    null,
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:7, y:10 }, depth: 4 },
    ],
    [
        { coordinate:{ x:7, y:9 }, depth: 2 },
        { coordinate:{ x:6, y:10 }, depth: 2 },
        { coordinate:{ x:8, y:10 }, depth: 2 },
        { coordinate:{ x:7, y:11 }, depth: 2 },
    ],
    [
        { coordinate:{ x:7, y:8 }, depth: 1 },
        { coordinate:{ x:6, y:9 }, depth: 1 },
        { coordinate:{ x:8, y:9 }, depth: 1 },
        { coordinate:{ x:5, y:10 }, depth: 1 },
        { coordinate:{ x:9, y:10 }, depth: 1 },
        { coordinate:{ x:6, y:11 }, depth: 1 },
        { coordinate:{ x:8, y:11 }, depth: 1 },
    ],
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:21, y:3 }, depth: 4 },
    ],
    [
        { coordinate:{ x:21, y:2 }, depth: 2 },
        { coordinate:{ x:20, y:3 }, depth: 2 },
        { coordinate:{ x:22, y:3 }, depth: 2 },
        { coordinate:{ x:21, y:4 }, depth: 2 },
    ],
    [
        { coordinate:{ x:21, y:1 }, depth: 1 },
        { coordinate:{ x:20, y:2 }, depth: 1 },
        { coordinate:{ x:22, y:2 }, depth: 1 },
        { coordinate:{ x:19, y:3 }, depth: 1 },
        { coordinate:{ x:23, y:3 }, depth: 1 },
        { coordinate:{ x:20, y:4 }, depth: 1 },
        { coordinate:{ x:22, y:4 }, depth: 1 },
        { coordinate:{ x:21, y:5 }, depth: 1 },
    ],
    null,
    [
        { coordinate:{ x:9, y:0 }, depth: 1 },
    ],
    null,
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:15, y:7 }, depth: 4 },
    ],
    [
        { coordinate:{ x:15, y:6 }, depth: 2 },
        { coordinate:{ x:14, y:7 }, depth: 2 },
        { coordinate:{ x:16, y:7 }, depth: 2 },
        { coordinate:{ x:15, y:8 }, depth: 2 },
    ],
    [
        { coordinate:{ x:15, y:5 }, depth: 1 },
        { coordinate:{ x:14, y:6 }, depth: 1 },
        { coordinate:{ x:16, y:6 }, depth: 1 },
        { coordinate:{ x:13, y:7 }, depth: 1 },
        { coordinate:{ x:17, y:7 }, depth: 1 },
        { coordinate:{ x:14, y:8 }, depth: 1 },
        { coordinate:{ x:16, y:8 }, depth: 1 },
        { coordinate:{ x:15, y:9 }, depth: 1 },
    ],
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:9, y:2 }, depth: 4 },
    ],
    [
        { coordinate:{ x:9, y:1 }, depth: 2 },
        { coordinate:{ x:8, y:2 }, depth: 2 },
        { coordinate:{ x:10, y:2 }, depth: 2 },
        { coordinate:{ x:9, y:3 }, depth: 2 },
    ],
    [
        { coordinate:{ x:8, y:1 }, depth: 1 },
        { coordinate:{ x:10, y:1 }, depth: 1 },
        { coordinate:{ x:7, y:2 }, depth: 1 },
        { coordinate:{ x:11, y:2 }, depth: 1 },
        { coordinate:{ x:8, y:3 }, depth: 1 },
        { coordinate:{ x:10, y:3 }, depth: 1 },
        { coordinate:{ x:9, y:4 }, depth: 1 },
    ],
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:22, y:10 }, depth: 4 },
    ],
    [
        { coordinate:{ x:22, y:9 }, depth: 2 },
        { coordinate:{ x:21, y:10 }, depth: 2 },
        { coordinate:{ x:23, y:10 }, depth: 2 },
        { coordinate:{ x:22, y:11 }, depth: 2 },
    ],
    [
        { coordinate:{ x:22, y:8 }, depth: 1 },
        { coordinate:{ x:21, y:9 }, depth: 1 },
        { coordinate:{ x:23, y:9 }, depth: 1 },
        { coordinate:{ x:20, y:10 }, depth: 1 },
        { coordinate:{ x:24, y:10 }, depth: 1 },
        { coordinate:{ x:21, y:11 }, depth: 1 },
        { coordinate:{ x:23, y:11 }, depth: 1 },
    ],
];
