import { Pattern } from '../UndergroundBattery';

export const batteryPatternFleurCannon: Pattern = [
    [
        { coordinate:{ x:12, y:4 }, depth: 5 },
        { coordinate:{ x:13, y:4 }, depth: 5 },
        { coordinate:{ x:14, y:4 }, depth: 5 },
        { coordinate:{ x:15, y:4 }, depth: 5 },
        { coordinate:{ x:11, y:5 }, depth: 5 },
        { coordinate:{ x:15, y:5 }, depth: 5 },
        { coordinate:{ x:11, y:6 }, depth: 5 },
        { coordinate:{ x:15, y:6 }, depth: 5 },
        { coordinate:{ x:11, y:7 }, depth: 5 },
        { coordinate:{ x:15, y:7 }, depth: 5 },
        { coordinate:{ x:12, y:8 }, depth: 5 },
        { coordinate:{ x:13, y:8 }, depth: 5 },
        { coordinate:{ x:14, y:8 }, depth: 5 },
    ],
    [
        { coordinate:{ x:13, y:3 }, depth: 5 },
        { coordinate:{ x:10, y:5 }, depth: 5 },
        { coordinate:{ x:16, y:5 }, depth: 5 },
        { coordinate:{ x:11, y:9 }, depth: 5 },
        { coordinate:{ x:15, y:9 }, depth: 5 },
    ],
    [
        { coordinate:{ x:13, y:2 }, depth: 5 },
        { coordinate:{ x:11, y:3 }, depth: 5 },
        { coordinate:{ x:16, y:3 }, depth: 5 },
        { coordinate:{ x:9, y:5 }, depth: 5 },
        { coordinate:{ x:17, y:5 }, depth: 5 },
        { coordinate:{ x:10, y:7 }, depth: 5 },
        { coordinate:{ x:16, y:7 }, depth: 5 },
        { coordinate:{ x:13, y:9 }, depth: 5 },
        { coordinate:{ x:10, y:10 }, depth: 5 },
        { coordinate:{ x:16, y:10 }, depth: 5 },
    ],
    [
        { coordinate:{ x:14, y:1 }, depth: 5 },
        { coordinate:{ x:7, y:3 }, depth: 5 },
        { coordinate:{ x:8, y:4 }, depth: 5 },
        { coordinate:{ x:18, y:5 }, depth: 5 },
        { coordinate:{ x:9, y:10 }, depth: 5 },
        { coordinate:{ x:15, y:11 }, depth: 5 },
    ],
    [
        { coordinate:{ x:15, y:0 }, depth: 5 },
        { coordinate:{ x:7, y:2 }, depth: 5 },
        { coordinate:{ x:10, y:3 }, depth: 5 },
        { coordinate:{ x:19, y:6 }, depth: 5 },
        { coordinate:{ x:9, y:7 }, depth: 5 },
        { coordinate:{ x:17, y:7 }, depth: 5 },
        { coordinate:{ x:8, y:10 }, depth: 5 },
        { coordinate:{ x:13, y:10 }, depth: 5 },
    ],
    [
        { coordinate:{ x:16, y:0 }, depth: 5 },
        { coordinate:{ x:8, y:1 }, depth: 5 },
        { coordinate:{ x:20, y:7 }, depth: 5 },
        { coordinate:{ x:7, y:9 }, depth: 5 },
    ],
    [
        { coordinate:{ x:9, y:0 }, depth: 5 },
        { coordinate:{ x:17, y:0 }, depth: 5 },
        { coordinate:{ x:6, y:8 }, depth: 5 },
        { coordinate:{ x:20, y:8 }, depth: 5 },
    ],
    [
        { coordinate:{ x:10, y:0 }, depth: 5 },
        { coordinate:{ x:18, y:1 }, depth: 5 },
        { coordinate:{ x:6, y:7 }, depth: 5 },
        { coordinate:{ x:19, y:9 }, depth: 5 },
        { coordinate:{ x:11, y:11 }, depth: 5 },
    ],
    [
        { coordinate:{ x:11, y:0 }, depth: 5 },
        { coordinate:{ x:19, y:2 }, depth: 5 },
        { coordinate:{ x:6, y:6 }, depth: 5 },
        { coordinate:{ x:18, y:10 }, depth: 5 },
    ],
    [
        { coordinate:{ x:12, y:1 }, depth: 5 },
        { coordinate:{ x:19, y:3 }, depth: 5 },
        { coordinate:{ x:7, y:5 }, depth: 5 },
        { coordinate:{ x:17, y:10 }, depth: 5 },
    ],
    [
        { coordinate:{ x:8, y:5 }, depth: 5 },
    ],
    [
        { coordinate:{ x:18, y:4 }, depth: 5 },
    ],
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:16, y:6 }, depth: 3 },
        { coordinate:{ x:17, y:6 }, depth: 3 },
        { coordinate:{ x:15, y:8 }, depth: 3 },
        { coordinate:{ x:16, y:8 }, depth: 3 },
    ],
    null,
    [
        { coordinate:{ x:18, y:6 }, depth: 3 },
        { coordinate:{ x:18, y:7 }, depth: 3 },
        { coordinate:{ x:17, y:8 }, depth: 3 },
        { coordinate:{ x:16, y:9 }, depth: 3 },
    ],
    null,
    [
        { coordinate:{ x:19, y:7 }, depth: 3 },
        { coordinate:{ x:18, y:8 }, depth: 3 },
        { coordinate:{ x:19, y:8 }, depth: 3 },
        { coordinate:{ x:17, y:9 }, depth: 3 },
        { coordinate:{ x:18, y:9 }, depth: 3 },
    ],
    null,
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:12, y:9 }, depth: 3 },
        { coordinate:{ x:14, y:9 }, depth: 3 },
    ],
    null,
    [
        { coordinate:{ x:12, y:10 }, depth: 3 },
        { coordinate:{ x:14, y:10 }, depth: 3 },
    ],
    null,
    [
        { coordinate:{ x:11, y:10 }, depth: 3 },
        { coordinate:{ x:15, y:10 }, depth: 3 },
        { coordinate:{ x:12, y:11 }, depth: 3 },
        { coordinate:{ x:13, y:11 }, depth: 3 },
        { coordinate:{ x:14, y:11 }, depth: 3 },
    ],
    null,
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:10, y:6 }, depth: 3 },
        { coordinate:{ x:10, y:8 }, depth: 3 },
        { coordinate:{ x:11, y:8 }, depth: 3 },
    ],
    null,
    [
        { coordinate:{ x:9, y:6 }, depth: 3 },
        { coordinate:{ x:8, y:7 }, depth: 3 },
        { coordinate:{ x:9, y:8 }, depth: 3 },
        { coordinate:{ x:10, y:9 }, depth: 3 },
    ],
    null,
    [
        { coordinate:{ x:7, y:6 }, depth: 3 },
        { coordinate:{ x:8, y:6 }, depth: 3 },
        { coordinate:{ x:7, y:7 }, depth: 3 },
        { coordinate:{ x:7, y:8 }, depth: 3 },
        { coordinate:{ x:8, y:8 }, depth: 3 },
        { coordinate:{ x:8, y:9 }, depth: 3 },
        { coordinate:{ x:9, y:9 }, depth: 3 },
    ],
    null,
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:12, y:3 }, depth: 3 },
        { coordinate:{ x:11, y:4 }, depth: 3 },
    ],
    null,
    [
        { coordinate:{ x:12, y:2 }, depth: 3 },
        { coordinate:{ x:10, y:4 }, depth: 3 },
    ],
    null,
    [
        { coordinate:{ x:11, y:2 }, depth: 3 },
        { coordinate:{ x:9, y:4 }, depth: 3 },
    ],
    null,
    [
        { coordinate:{ x:10, y:2 }, depth: 3 },
        { coordinate:{ x:9, y:3 }, depth: 3 },
    ],
    null,
    [
        { coordinate:{ x:9, y:1 }, depth: 3 },
        { coordinate:{ x:10, y:1 }, depth: 3 },
        { coordinate:{ x:11, y:1 }, depth: 3 },
        { coordinate:{ x:8, y:2 }, depth: 3 },
        { coordinate:{ x:9, y:2 }, depth: 3 },
        { coordinate:{ x:8, y:3 }, depth: 3 },
    ],
    null,
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:14, y:3 }, depth: 3 },
        { coordinate:{ x:15, y:3 }, depth: 3 },
        { coordinate:{ x:16, y:4 }, depth: 3 },
    ],
    null,
    null,
    [
        { coordinate:{ x:15, y:2 }, depth: 3 },
        { coordinate:{ x:16, y:2 }, depth: 3 },
        { coordinate:{ x:17, y:3 }, depth: 3 },
    ],
    null,
    null,
    null,
    [
        { coordinate:{ x:15, y:1 }, depth: 3 },
        { coordinate:{ x:16, y:1 }, depth: 3 },
        { coordinate:{ x:17, y:1 }, depth: 3 },
        { coordinate:{ x:14, y:2 }, depth: 3 },
        { coordinate:{ x:17, y:2 }, depth: 3 },
        { coordinate:{ x:18, y:2 }, depth: 3 },
        { coordinate:{ x:18, y:3 }, depth: 3 },
        { coordinate:{ x:17, y:4 }, depth: 3 },
    ],
    null,
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:12, y:5 }, depth: 2 },
        { coordinate:{ x:13, y:5 }, depth: 2 },
        { coordinate:{ x:14, y:5 }, depth: 2 },
        { coordinate:{ x:12, y:6 }, depth: 2 },
        { coordinate:{ x:14, y:6 }, depth: 2 },
        { coordinate:{ x:12, y:7 }, depth: 2 },
        { coordinate:{ x:13, y:7 }, depth: 2 },
        { coordinate:{ x:14, y:7 }, depth: 2 },
    ],
    null,
    [
        { coordinate:{ x:13, y:6 }, depth: 1 },
    ],
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:20, y:2 }, depth: 2 },
        { coordinate:{ x:20, y:3 }, depth: 2 },
        { coordinate:{ x:4, y:4 }, depth: 2 },
        { coordinate:{ x:19, y:4 }, depth: 2 },
        { coordinate:{ x:5, y:5 }, depth: 2 },
        { coordinate:{ x:19, y:5 }, depth: 2 },
        { coordinate:{ x:5, y:6 }, depth: 2 },
        { coordinate:{ x:5, y:7 }, depth: 2 },
    ],
    null,
    null,
    [
        { coordinate:{ x:21, y:2 }, depth: 2 },
        { coordinate:{ x:22, y:2 }, depth: 2 },
        { coordinate:{ x:23, y:2 }, depth: 2 },
        { coordinate:{ x:21, y:3 }, depth: 2 },
        { coordinate:{ x:1, y:4 }, depth: 2 },
        { coordinate:{ x:2, y:4 }, depth: 2 },
        { coordinate:{ x:3, y:4 }, depth: 2 },
        { coordinate:{ x:20, y:4 }, depth: 2 },
        { coordinate:{ x:3, y:5 }, depth: 2 },
        { coordinate:{ x:4, y:5 }, depth: 2 },
        { coordinate:{ x:4, y:6 }, depth: 2 },
    ],
    null,
    null,
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:22, y:3 }, depth: 1 },
        { coordinate:{ x:21, y:4 }, depth: 1 },
        { coordinate:{ x:2, y:5 }, depth: 1 },
        { coordinate:{ x:20, y:5 }, depth: 1 },
        { coordinate:{ x:3, y:6 }, depth: 1 },
        { coordinate:{ x:4, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:24, y:2 }, depth: 1 },
        { coordinate:{ x:23, y:3 }, depth: 1 },
        { coordinate:{ x:0, y:4 }, depth: 1 },
        { coordinate:{ x:22, y:4 }, depth: 1 },
        { coordinate:{ x:1, y:5 }, depth: 1 },
        { coordinate:{ x:21, y:5 }, depth: 1 },
        { coordinate:{ x:2, y:6 }, depth: 1 },
        { coordinate:{ x:3, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:23, y:4 }, depth: 1 },
        { coordinate:{ x:22, y:5 }, depth: 1 },
        { coordinate:{ x:1, y:6 }, depth: 1 },
        { coordinate:{ x:2, y:7 }, depth: 1 },
    ],
];
