import { Pattern } from '../UndergroundBattery';

export const batteryPatternHydroCannon: Pattern = [
    [
        { coordinate:{ x:0, y:10 }, depth: 1 },
        { coordinate:{ x:0, y:11 }, depth: 1 },
        { coordinate:{ x:1, y:11 }, depth: 1 },
        { coordinate:{ x:2, y:11 }, depth: 1 },
    ],
    [
        { coordinate:{ x:1, y:10 }, depth: 1 },
        { coordinate:{ x:2, y:10 }, depth: 1 },
        { coordinate:{ x:3, y:11 }, depth: 1 },
    ],
    [
        { coordinate:{ x:2, y:9 }, depth: 1 },
        { coordinate:{ x:3, y:10 }, depth: 1 },
        { coordinate:{ x:4, y:10 }, depth: 1 },
    ],
    [
        { coordinate:{ x:3, y:9 }, depth: 1 },
        { coordinate:{ x:5, y:10 }, depth: 1 },
    ],
    [
        { coordinate:{ x:4, y:9 }, depth: 1 },
        { coordinate:{ x:5, y:9 }, depth: 1 },
        { coordinate:{ x:6, y:10 }, depth: 1 },
    ],
    [
        { coordinate:{ x:5, y:8 }, depth: 1 },
        { coordinate:{ x:6, y:9 }, depth: 1 },
        { coordinate:{ x:7, y:9 }, depth: 1 },
    ],
    [
        { coordinate:{ x:6, y:8 }, depth: 1 },
        { coordinate:{ x:8, y:9 }, depth: 1 },
    ],
    [
        { coordinate:{ x:7, y:8 }, depth: 1 },
        { coordinate:{ x:8, y:8 }, depth: 1 },
        { coordinate:{ x:9, y:9 }, depth: 1 },
    ],
    [
        { coordinate:{ x:8, y:7 }, depth: 1 },
        { coordinate:{ x:9, y:8 }, depth: 1 },
        { coordinate:{ x:10, y:8 }, depth: 1 },
    ],
    [
        { coordinate:{ x:9, y:7 }, depth: 1 },
        { coordinate:{ x:11, y:8 }, depth: 1 },
    ],
    [
        { coordinate:{ x:10, y:7 }, depth: 1 },
        { coordinate:{ x:11, y:7 }, depth: 1 },
        { coordinate:{ x:12, y:8 }, depth: 1 },
    ],
    [
        { coordinate:{ x:11, y:6 }, depth: 1 },
        { coordinate:{ x:12, y:7 }, depth: 1 },
        { coordinate:{ x:13, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:12, y:6 }, depth: 1 },
        { coordinate:{ x:14, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:13, y:6 }, depth: 1 },
        { coordinate:{ x:14, y:6 }, depth: 1 },
        { coordinate:{ x:15, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:14, y:5 }, depth: 1 },
        { coordinate:{ x:15, y:6 }, depth: 1 },
        { coordinate:{ x:16, y:6 }, depth: 1 },
    ],
    [
        { coordinate:{ x:15, y:5 }, depth: 1 },
        { coordinate:{ x:17, y:6 }, depth: 1 },
    ],
    [
        { coordinate:{ x:16, y:5 }, depth: 1 },
        { coordinate:{ x:17, y:5 }, depth: 1 },
        { coordinate:{ x:18, y:6 }, depth: 1 },
    ],
    [
        { coordinate:{ x:17, y:4 }, depth: 1 },
        { coordinate:{ x:18, y:5 }, depth: 1 },
    ],
    [
        { coordinate:{ x:18, y:2 }, depth: 3 },
        { coordinate:{ x:19, y:2 }, depth: 3 },
        { coordinate:{ x:20, y:2 }, depth: 3 },
        { coordinate:{ x:18, y:3 }, depth: 3 },
        { coordinate:{ x:19, y:3 }, depth: 3 },
        { coordinate:{ x:20, y:3 }, depth: 3 },
        { coordinate:{ x:18, y:4 }, depth: 3 },
        { coordinate:{ x:19, y:4 }, depth: 3 },
        { coordinate:{ x:20, y:4 }, depth: 3 },
    ],
    [
        { coordinate:{ x:19, y:1 }, depth: 2 },
        { coordinate:{ x:17, y:3 }, depth: 2 },
        { coordinate:{ x:21, y:3 }, depth: 2 },
        { coordinate:{ x:19, y:5 }, depth: 2 },
    ],
    [
        { coordinate:{ x:18, y:1 }, depth: 1 },
        { coordinate:{ x:20, y:1 }, depth: 1 },
        { coordinate:{ x:17, y:2 }, depth: 1 },
        { coordinate:{ x:21, y:2 }, depth: 1 },
        { coordinate:{ x:21, y:4 }, depth: 1 },
        { coordinate:{ x:20, y:5 }, depth: 1 },
    ],
    [
        { coordinate:{ x:17, y:0 }, depth: 1 },
        { coordinate:{ x:21, y:0 }, depth: 1 },
        { coordinate:{ x:16, y:1 }, depth: 1 },
        { coordinate:{ x:22, y:1 }, depth: 1 },
        { coordinate:{ x:22, y:5 }, depth: 1 },
        { coordinate:{ x:21, y:6 }, depth: 1 },
    ],
    [
        { coordinate:{ x:15, y:0 }, depth: 1 },
        { coordinate:{ x:23, y:0 }, depth: 1 },
        { coordinate:{ x:23, y:6 }, depth: 1 },
        { coordinate:{ x:16, y:7 }, depth: 1 },
        { coordinate:{ x:22, y:7 }, depth: 1 },
    ],
    null,
    [
        { coordinate:{ x:19, y:0 }, depth: 1 },
        { coordinate:{ x:16, y:3 }, depth: 1 },
        { coordinate:{ x:22, y:3 }, depth: 1 },
        { coordinate:{ x:19, y:6 }, depth: 1 },
    ],
    [
        { coordinate:{ x:15, y:3 }, depth: 1 },
        { coordinate:{ x:23, y:3 }, depth: 1 },
        { coordinate:{ x:19, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:14, y:3 }, depth: 1 },
        { coordinate:{ x:24, y:3 }, depth: 1 },
        { coordinate:{ x:19, y:8 }, depth: 1 },
    ],
    null,
    [
        { coordinate:{ x:18, y:0 }, depth: 1 },
        { coordinate:{ x:20, y:0 }, depth: 1 },
        { coordinate:{ x:16, y:2 }, depth: 1 },
        { coordinate:{ x:22, y:2 }, depth: 1 },
        { coordinate:{ x:16, y:4 }, depth: 1 },
        { coordinate:{ x:22, y:4 }, depth: 1 },
        { coordinate:{ x:20, y:6 }, depth: 1 },
    ],
    [
        { coordinate:{ x:15, y:2 }, depth: 1 },
        { coordinate:{ x:23, y:2 }, depth: 1 },
        { coordinate:{ x:15, y:4 }, depth: 1 },
        { coordinate:{ x:23, y:4 }, depth: 1 },
        { coordinate:{ x:18, y:7 }, depth: 1 },
        { coordinate:{ x:20, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:14, y:2 }, depth: 1 },
        { coordinate:{ x:24, y:2 }, depth: 1 },
        { coordinate:{ x:14, y:4 }, depth: 1 },
        { coordinate:{ x:24, y:4 }, depth: 1 },
        { coordinate:{ x:18, y:8 }, depth: 1 },
        { coordinate:{ x:20, y:8 }, depth: 1 },
    ],
    null,
    [
        { coordinate:{ x:17, y:1 }, depth: 1 },
        { coordinate:{ x:21, y:1 }, depth: 1 },
        { coordinate:{ x:21, y:5 }, depth: 1 },
    ],
    [
        { coordinate:{ x:16, y:0 }, depth: 1 },
        { coordinate:{ x:22, y:0 }, depth: 1 },
        { coordinate:{ x:15, y:1 }, depth: 1 },
        { coordinate:{ x:23, y:1 }, depth: 1 },
        { coordinate:{ x:23, y:5 }, depth: 1 },
        { coordinate:{ x:22, y:6 }, depth: 1 },
        { coordinate:{ x:17, y:7 }, depth: 1 },
        { coordinate:{ x:21, y:7 }, depth: 1 },
    ],
];
