import { Pattern } from '../UndergroundBattery';

export const batteryPatternHyperBeam: Pattern = [
    null,
    [
        { coordinate:{ x:0, y:4 }, depth: 5 },
        { coordinate:{ x:0, y:5 }, depth: 5 },
        { coordinate:{ x:1, y:5 }, depth: 5 },
        { coordinate:{ x:0, y:6 }, depth: 5 },
        { coordinate:{ x:1, y:6 }, depth: 5 },
        { coordinate:{ x:0, y:7 }, depth: 5 },
    ],
    null,
    null,
    null,
    [
        { coordinate:{ x:1, y:4 }, depth: 5 },
        { coordinate:{ x:2, y:4 }, depth: 5 },
        { coordinate:{ x:2, y:5 }, depth: 5 },
        { coordinate:{ x:3, y:5 }, depth: 5 },
        { coordinate:{ x:2, y:6 }, depth: 5 },
        { coordinate:{ x:3, y:6 }, depth: 5 },
        { coordinate:{ x:1, y:7 }, depth: 5 },
        { coordinate:{ x:2, y:7 }, depth: 5 },
    ],
    null,
    null,
    null,
    [
        { coordinate:{ x:3, y:4 }, depth: 5 },
        { coordinate:{ x:4, y:4 }, depth: 5 },
        { coordinate:{ x:5, y:4 }, depth: 5 },
        { coordinate:{ x:4, y:5 }, depth: 5 },
        { coordinate:{ x:5, y:5 }, depth: 5 },
        { coordinate:{ x:6, y:5 }, depth: 5 },
        { coordinate:{ x:4, y:6 }, depth: 5 },
        { coordinate:{ x:5, y:6 }, depth: 5 },
        { coordinate:{ x:6, y:6 }, depth: 5 },
        { coordinate:{ x:3, y:7 }, depth: 5 },
        { coordinate:{ x:4, y:7 }, depth: 5 },
        { coordinate:{ x:5, y:7 }, depth: 5 },
    ],
    null,
    null,
    [
        { coordinate:{ x:6, y:4 }, depth: 5 },
        { coordinate:{ x:7, y:4 }, depth: 5 },
        { coordinate:{ x:8, y:4 }, depth: 5 },
        { coordinate:{ x:7, y:5 }, depth: 5 },
        { coordinate:{ x:8, y:5 }, depth: 5 },
        { coordinate:{ x:9, y:5 }, depth: 5 },
        { coordinate:{ x:7, y:6 }, depth: 5 },
        { coordinate:{ x:8, y:6 }, depth: 5 },
        { coordinate:{ x:9, y:6 }, depth: 5 },
        { coordinate:{ x:6, y:7 }, depth: 5 },
        { coordinate:{ x:7, y:7 }, depth: 5 },
        { coordinate:{ x:8, y:7 }, depth: 5 },
    ],
    null,
    null,
    [
        { coordinate:{ x:9, y:4 }, depth: 5 },
        { coordinate:{ x:10, y:4 }, depth: 5 },
        { coordinate:{ x:11, y:4 }, depth: 5 },
        { coordinate:{ x:12, y:4 }, depth: 5 },
        { coordinate:{ x:10, y:5 }, depth: 5 },
        { coordinate:{ x:11, y:5 }, depth: 5 },
        { coordinate:{ x:12, y:5 }, depth: 5 },
        { coordinate:{ x:13, y:5 }, depth: 5 },
        { coordinate:{ x:10, y:6 }, depth: 5 },
        { coordinate:{ x:11, y:6 }, depth: 5 },
        { coordinate:{ x:12, y:6 }, depth: 5 },
        { coordinate:{ x:13, y:6 }, depth: 5 },
        { coordinate:{ x:9, y:7 }, depth: 5 },
        { coordinate:{ x:10, y:7 }, depth: 5 },
        { coordinate:{ x:11, y:7 }, depth: 5 },
        { coordinate:{ x:12, y:7 }, depth: 5 },
    ],
    null,
    [
        { coordinate:{ x:13, y:4 }, depth: 5 },
        { coordinate:{ x:14, y:4 }, depth: 5 },
        { coordinate:{ x:15, y:4 }, depth: 5 },
        { coordinate:{ x:16, y:4 }, depth: 5 },
        { coordinate:{ x:14, y:5 }, depth: 5 },
        { coordinate:{ x:15, y:5 }, depth: 5 },
        { coordinate:{ x:16, y:5 }, depth: 5 },
        { coordinate:{ x:17, y:5 }, depth: 5 },
        { coordinate:{ x:14, y:6 }, depth: 5 },
        { coordinate:{ x:15, y:6 }, depth: 5 },
        { coordinate:{ x:16, y:6 }, depth: 5 },
        { coordinate:{ x:17, y:6 }, depth: 5 },
        { coordinate:{ x:13, y:7 }, depth: 5 },
        { coordinate:{ x:14, y:7 }, depth: 5 },
        { coordinate:{ x:15, y:7 }, depth: 5 },
        { coordinate:{ x:16, y:7 }, depth: 5 },
    ],
    null,
    [
        { coordinate:{ x:17, y:4 }, depth: 5 },
        { coordinate:{ x:18, y:4 }, depth: 5 },
        { coordinate:{ x:19, y:4 }, depth: 5 },
        { coordinate:{ x:20, y:4 }, depth: 5 },
        { coordinate:{ x:21, y:4 }, depth: 5 },
        { coordinate:{ x:18, y:5 }, depth: 5 },
        { coordinate:{ x:19, y:5 }, depth: 5 },
        { coordinate:{ x:20, y:5 }, depth: 5 },
        { coordinate:{ x:21, y:5 }, depth: 5 },
        { coordinate:{ x:22, y:5 }, depth: 5 },
        { coordinate:{ x:18, y:6 }, depth: 5 },
        { coordinate:{ x:19, y:6 }, depth: 5 },
        { coordinate:{ x:20, y:6 }, depth: 5 },
        { coordinate:{ x:21, y:6 }, depth: 5 },
        { coordinate:{ x:22, y:6 }, depth: 5 },
        { coordinate:{ x:17, y:7 }, depth: 5 },
        { coordinate:{ x:18, y:7 }, depth: 5 },
        { coordinate:{ x:19, y:7 }, depth: 5 },
        { coordinate:{ x:20, y:7 }, depth: 5 },
        { coordinate:{ x:21, y:7 }, depth: 5 },
    ],
    [
        { coordinate:{ x:22, y:4 }, depth: 5 },
        { coordinate:{ x:23, y:4 }, depth: 5 },
        { coordinate:{ x:24, y:4 }, depth: 5 },
        { coordinate:{ x:23, y:5 }, depth: 5 },
        { coordinate:{ x:24, y:5 }, depth: 5 },
        { coordinate:{ x:23, y:6 }, depth: 5 },
        { coordinate:{ x:24, y:6 }, depth: 5 },
        { coordinate:{ x:22, y:7 }, depth: 5 },
        { coordinate:{ x:23, y:7 }, depth: 5 },
        { coordinate:{ x:24, y:7 }, depth: 5 },
    ],
];
