import { Pattern } from '../UndergroundBattery';

export const batteryPatternPokeball: Pattern = [
    [
        { coordinate:{ x:7, y:0 }, depth: 5 },
        { coordinate:{ x:8, y:0 }, depth: 5 },
        { coordinate:{ x:9, y:0 }, depth: 5 },
        { coordinate:{ x:14, y:0 }, depth: 5 },
        { coordinate:{ x:15, y:0 }, depth: 5 },
        { coordinate:{ x:16, y:0 }, depth: 5 },
        { coordinate:{ x:6, y:1 }, depth: 5 },
        { coordinate:{ x:7, y:1 }, depth: 5 },
        { coordinate:{ x:16, y:1 }, depth: 5 },
        { coordinate:{ x:17, y:1 }, depth: 5 },
        { coordinate:{ x:6, y:2 }, depth: 5 },
        { coordinate:{ x:17, y:2 }, depth: 5 },
        { coordinate:{ x:5, y:3 }, depth: 5 },
        { coordinate:{ x:6, y:3 }, depth: 5 },
        { coordinate:{ x:17, y:3 }, depth: 5 },
        { coordinate:{ x:18, y:3 }, depth: 5 },
        { coordinate:{ x:5, y:4 }, depth: 5 },
        { coordinate:{ x:18, y:4 }, depth: 5 },
        { coordinate:{ x:5, y:5 }, depth: 5 },
        { coordinate:{ x:18, y:5 }, depth: 5 },
        { coordinate:{ x:5, y:6 }, depth: 5 },
        { coordinate:{ x:18, y:6 }, depth: 5 },
        { coordinate:{ x:5, y:7 }, depth: 5 },
        { coordinate:{ x:18, y:7 }, depth: 5 },
        { coordinate:{ x:5, y:8 }, depth: 5 },
        { coordinate:{ x:6, y:8 }, depth: 5 },
        { coordinate:{ x:17, y:8 }, depth: 5 },
        { coordinate:{ x:18, y:8 }, depth: 5 },
        { coordinate:{ x:6, y:9 }, depth: 5 },
        { coordinate:{ x:17, y:9 }, depth: 5 },
        { coordinate:{ x:6, y:10 }, depth: 5 },
        { coordinate:{ x:7, y:10 }, depth: 5 },
        { coordinate:{ x:16, y:10 }, depth: 5 },
        { coordinate:{ x:17, y:10 }, depth: 5 },
        { coordinate:{ x:7, y:11 }, depth: 5 },
        { coordinate:{ x:8, y:11 }, depth: 5 },
        { coordinate:{ x:9, y:11 }, depth: 5 },
        { coordinate:{ x:14, y:11 }, depth: 5 },
        { coordinate:{ x:15, y:11 }, depth: 5 },
        { coordinate:{ x:16, y:11 }, depth: 5 },
    ],
    null,
    [
        { coordinate:{ x:11, y:0 }, depth: 1 },
        { coordinate:{ x:12, y:0 }, depth: 1 },
    ],
    [
        { coordinate:{ x:10, y:0 }, depth: 1 },
        { coordinate:{ x:13, y:0 }, depth: 1 },
    ],
    [
        { coordinate:{ x:9, y:1 }, depth: 1 },
        { coordinate:{ x:14, y:1 }, depth: 1 },
    ],
    [
        { coordinate:{ x:8, y:1 }, depth: 1 },
        { coordinate:{ x:15, y:1 }, depth: 1 },
    ],
    [
        { coordinate:{ x:7, y:2 }, depth: 1 },
        { coordinate:{ x:16, y:2 }, depth: 1 },
    ],
    [
        { coordinate:{ x:7, y:3 }, depth: 1 },
        { coordinate:{ x:16, y:3 }, depth: 1 },
    ],
    [
        { coordinate:{ x:6, y:4 }, depth: 1 },
        { coordinate:{ x:17, y:4 }, depth: 1 },
    ],
    [
        { coordinate:{ x:6, y:5 }, depth: 1 },
        { coordinate:{ x:17, y:5 }, depth: 1 },
    ],
    [
        { coordinate:{ x:6, y:6 }, depth: 1 },
        { coordinate:{ x:17, y:6 }, depth: 1 },
    ],
    [
        { coordinate:{ x:6, y:7 }, depth: 1 },
        { coordinate:{ x:17, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:7, y:8 }, depth: 1 },
        { coordinate:{ x:16, y:8 }, depth: 1 },
    ],
    [
        { coordinate:{ x:7, y:9 }, depth: 1 },
        { coordinate:{ x:16, y:9 }, depth: 1 },
    ],
    [
        { coordinate:{ x:8, y:10 }, depth: 1 },
        { coordinate:{ x:15, y:10 }, depth: 1 },
    ],
    [
        { coordinate:{ x:9, y:10 }, depth: 1 },
        { coordinate:{ x:14, y:10 }, depth: 1 },
    ],
    [
        { coordinate:{ x:10, y:11 }, depth: 1 },
        { coordinate:{ x:13, y:11 }, depth: 1 },
    ],
    [
        { coordinate:{ x:11, y:11 }, depth: 1 },
        { coordinate:{ x:12, y:11 }, depth: 1 },
    ],
    [
        { coordinate:{ x:7, y:6 }, depth: 1 },
        { coordinate:{ x:16, y:6 }, depth: 1 },
    ],
    [
        { coordinate:{ x:8, y:7 }, depth: 1 },
        { coordinate:{ x:14, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:9, y:7 }, depth: 1 },
        { coordinate:{ x:15, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:10, y:6 }, depth: 1 },
        { coordinate:{ x:13, y:6 }, depth: 1 },
        { coordinate:{ x:10, y:7 }, depth: 1 },
        { coordinate:{ x:13, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:11, y:5 }, depth: 1 },
        { coordinate:{ x:12, y:5 }, depth: 1 },
        { coordinate:{ x:11, y:8 }, depth: 1 },
        { coordinate:{ x:12, y:8 }, depth: 1 },
    ],
    null,
    [
        { coordinate:{ x:7, y:7 }, depth: 5 },
    ],
    [
        { coordinate:{ x:8, y:8 }, depth: 5 },
        { coordinate:{ x:8, y:9 }, depth: 5 },
    ],
    [
        { coordinate:{ x:9, y:8 }, depth: 5 },
        { coordinate:{ x:9, y:9 }, depth: 5 },
    ],
    [
        { coordinate:{ x:10, y:8 }, depth: 5 },
        { coordinate:{ x:10, y:9 }, depth: 5 },
        { coordinate:{ x:10, y:10 }, depth: 5 },
    ],
    [
        { coordinate:{ x:11, y:9 }, depth: 5 },
        { coordinate:{ x:11, y:10 }, depth: 5 },
    ],
    [
        { coordinate:{ x:12, y:9 }, depth: 5 },
        { coordinate:{ x:12, y:10 }, depth: 5 },
        { coordinate:{ x:13, y:10 }, depth: 5 },
    ],
    [
        { coordinate:{ x:13, y:8 }, depth: 5 },
        { coordinate:{ x:13, y:9 }, depth: 5 },
    ],
    [
        { coordinate:{ x:14, y:8 }, depth: 5 },
        { coordinate:{ x:14, y:9 }, depth: 5 },
    ],
    [
        { coordinate:{ x:15, y:8 }, depth: 5 },
        { coordinate:{ x:15, y:9 }, depth: 5 },
    ],
    [
        { coordinate:{ x:16, y:7 }, depth: 5 },
    ],
    null,
    null,
    [
        { coordinate:{ x:16, y:5 }, depth: 2 },
        { coordinate:{ x:15, y:6 }, depth: 2 },
    ],
    [
        { coordinate:{ x:16, y:4 }, depth: 2 },
        { coordinate:{ x:15, y:5 }, depth: 2 },
        { coordinate:{ x:14, y:6 }, depth: 2 },
    ],
    [
        { coordinate:{ x:15, y:4 }, depth: 2 },
        { coordinate:{ x:14, y:5 }, depth: 2 },
    ],
    [
        { coordinate:{ x:15, y:3 }, depth: 2 },
        { coordinate:{ x:14, y:4 }, depth: 2 },
        { coordinate:{ x:13, y:5 }, depth: 2 },
    ],
    [
        { coordinate:{ x:15, y:2 }, depth: 2 },
        { coordinate:{ x:14, y:3 }, depth: 2 },
        { coordinate:{ x:13, y:4 }, depth: 2 },
    ],
    [
        { coordinate:{ x:14, y:2 }, depth: 2 },
        { coordinate:{ x:13, y:3 }, depth: 2 },
    ],
    [
        { coordinate:{ x:13, y:1 }, depth: 2 },
        { coordinate:{ x:13, y:2 }, depth: 2 },
        { coordinate:{ x:12, y:3 }, depth: 2 },
        { coordinate:{ x:12, y:4 }, depth: 2 },
    ],
    [
        { coordinate:{ x:12, y:1 }, depth: 2 },
        { coordinate:{ x:12, y:2 }, depth: 2 },
    ],
    [
        { coordinate:{ x:11, y:1 }, depth: 2 },
        { coordinate:{ x:11, y:2 }, depth: 2 },
        { coordinate:{ x:11, y:4 }, depth: 2 },
    ],
    [
        { coordinate:{ x:10, y:1 }, depth: 2 },
        { coordinate:{ x:9, y:2 }, depth: 2 },
    ],
    [
        { coordinate:{ x:8, y:2 }, depth: 2 },
    ],
    [
        { coordinate:{ x:8, y:3 }, depth: 2 },
        { coordinate:{ x:9, y:4 }, depth: 2 },
        { coordinate:{ x:10, y:5 }, depth: 2 },
    ],
    [
        { coordinate:{ x:7, y:4 }, depth: 2 },
        { coordinate:{ x:8, y:4 }, depth: 2 },
        { coordinate:{ x:9, y:5 }, depth: 2 },
    ],
    [
        { coordinate:{ x:7, y:5 }, depth: 2 },
        { coordinate:{ x:8, y:5 }, depth: 2 },
        { coordinate:{ x:8, y:6 }, depth: 2 },
        { coordinate:{ x:9, y:6 }, depth: 2 },
    ],
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:10, y:3 }, depth: 5 },
    ],
    null,
    [
        { coordinate:{ x:10, y:2 }, depth: 4 },
        { coordinate:{ x:9, y:3 }, depth: 4 },
        { coordinate:{ x:11, y:3 }, depth: 4 },
        { coordinate:{ x:10, y:4 }, depth: 4 },
    ],
    null,
    null,
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:11, y:6 }, depth: 5 },
    ],
    null,
    null,
    null,
    [
        { coordinate:{ x:12, y:6 }, depth: 5 },
        { coordinate:{ x:11, y:7 }, depth: 5 },
        { coordinate:{ x:12, y:7 }, depth: 5 },
    ],
];
