import { Pattern } from '../UndergroundBattery';

export const batteryPatternTenMillionVoltThunderbolt: Pattern = [
    [
        { coordinate:{ x:20, y:1 }, depth: 5 },
        { coordinate:{ x:21, y:1 }, depth: 5 },
        { coordinate:{ x:22, y:1 }, depth: 5 },
        { coordinate:{ x:20, y:2 }, depth: 5 },
        { coordinate:{ x:21, y:2 }, depth: 5 },
        { coordinate:{ x:22, y:2 }, depth: 5 },
        { coordinate:{ x:20, y:3 }, depth: 5 },
        { coordinate:{ x:21, y:3 }, depth: 5 },
        { coordinate:{ x:22, y:3 }, depth: 5 },
    ],
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:19, y:0 }, depth: 5 },
    ],
    [
        { coordinate:{ x:10, y:0 }, depth: 5 },
        { coordinate:{ x:11, y:0 }, depth: 5 },
        { coordinate:{ x:12, y:0 }, depth: 5 },
    ],
    [
        { coordinate:{ x:7, y:1 }, depth: 5 },
        { coordinate:{ x:8, y:1 }, depth: 5 },
        { coordinate:{ x:9, y:1 }, depth: 5 },
    ],
    [
        { coordinate:{ x:5, y:2 }, depth: 5 },
        { coordinate:{ x:6, y:2 }, depth: 5 },
        { coordinate:{ x:4, y:3 }, depth: 5 },
    ],
    [
        { coordinate:{ x:3, y:3 }, depth: 5 },
        { coordinate:{ x:2, y:4 }, depth: 5 },
        { coordinate:{ x:1, y:5 }, depth: 5 },
    ],
    [
        { coordinate:{ x:1, y:6 }, depth: 5 },
        { coordinate:{ x:0, y:7 }, depth: 5 },
    ],
    null,
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:23, y:4 }, depth: 5 },
        { coordinate:{ x:23, y:5 }, depth: 5 },
    ],
    [
        { coordinate:{ x:23, y:6 }, depth: 5 },
        { coordinate:{ x:23, y:7 }, depth: 5 },
    ],
    [
        { coordinate:{ x:24, y:8 }, depth: 5 },
        { coordinate:{ x:24, y:9 }, depth: 5 },
    ],
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    [
        { coordinate:{ x:17, y:1 }, depth: 5 },
        { coordinate:{ x:18, y:2 }, depth: 5 },
        { coordinate:{ x:19, y:2 }, depth: 5 },
    ],
    [
        { coordinate:{ x:15, y:1 }, depth: 5 },
        { coordinate:{ x:16, y:1 }, depth: 5 },
        { coordinate:{ x:14, y:2 }, depth: 5 },
    ],
    [
        { coordinate:{ x:12, y:2 }, depth: 5 },
        { coordinate:{ x:13, y:2 }, depth: 5 },
        { coordinate:{ x:11, y:3 }, depth: 5 },
    ],
    [
        { coordinate:{ x:10, y:3 }, depth: 5 },
        { coordinate:{ x:8, y:4 }, depth: 5 },
        { coordinate:{ x:9, y:4 }, depth: 5 },
    ],
    [
        { coordinate:{ x:7, y:5 }, depth: 5 },
        { coordinate:{ x:6, y:6 }, depth: 5 },
        { coordinate:{ x:5, y:7 }, depth: 5 },
    ],
    null,
    [
        { coordinate:{ x:23, y:1 }, depth: 5 },
    ],
    [
        { coordinate:{ x:24, y:0 }, depth: 5 },
    ],
    null,
    [
        { coordinate:{ x:18, y:4 }, depth: 5 },
        { coordinate:{ x:19, y:4 }, depth: 5 },
        { coordinate:{ x:17, y:5 }, depth: 5 },
    ],
    [
        { coordinate:{ x:16, y:5 }, depth: 5 },
        { coordinate:{ x:14, y:6 }, depth: 5 },
        { coordinate:{ x:15, y:6 }, depth: 5 },
    ],
    [
        { coordinate:{ x:13, y:6 }, depth: 5 },
        { coordinate:{ x:11, y:7 }, depth: 5 },
        { coordinate:{ x:12, y:7 }, depth: 5 },
    ],
    [
        { coordinate:{ x:9, y:8 }, depth: 5 },
        { coordinate:{ x:10, y:8 }, depth: 5 },
    ],
    null,
    null,
    null,
    [
        { coordinate:{ x:21, y:4 }, depth: 5 },
        { coordinate:{ x:21, y:5 }, depth: 5 },
        { coordinate:{ x:20, y:6 }, depth: 5 },
    ],
    [
        { coordinate:{ x:19, y:7 }, depth: 5 },
        { coordinate:{ x:18, y:8 }, depth: 5 },
        { coordinate:{ x:18, y:9 }, depth: 5 },
    ],
    [
        { coordinate:{ x:17, y:10 }, depth: 5 },
        { coordinate:{ x:16, y:11 }, depth: 5 },
    ],
];
