export const BASE_MINE_WIDTH = 25;
export const BASE_MINE_HEIGHT = 12;

export const BASE_MINIMUM_LAYER_DEPTH = 3;
export const BASE_EXTRA_LAYER_DEPTH = 2;

export const BASE_MINIMUM_ITEMS = 1;
export const BASE_MAXIMUM_ITEMS = 3;

export const GLOBAL_COOLDOWN_BASE = 15;
export const GLOBAL_COOLDOWN_REDUCTION_PER_LEVEL = 0.5;
export const GLOBAL_COOLDOWN_MINIMUM = 0.1;
export const TOOL_COOLDOWN_MINIMUM = 0.05;

export const DISCOVER_MINE_TIMEOUT_BASE = 60;
export const DISCOVER_MINE_TIMEOUT_REDUCTION_PER_LEVEL = 1.2;

export const SPECIAL_MINE_CHANCE = 1 / 25;

export const UNDERGROUND_EXPERIENCE_DIG_UP_ITEM = 25;
export const UNDERGROUND_EXPERIENCE_CLEAR_LAYER = 100;

export const SURVEY_RANGE_BASE = 9;
export const SURVEY_RANGE_REDUCTION_LEVELS = 15;

// HELPERS
export const MAX_HIRES = 1;

export const AUTO_SELL_BASE = 0.4;
export const AUTO_SELL_INCREASE_PER_LEVEL = 0.01;
export const AUTO_SELL_MAXIMUM = 0.9;

export const SMART_TOOL_CHANCE_BASE = 0.5;
export const SMART_TOOL_CHANCE_INCREASE_PER_LEVEL = 0.025;
export const SMART_TOOL_CHANCE_MAXIMUM = 1;

export const FAVORITE_MINE_CHANCE_BASE = 0.5;
export const FAVORITE_MINE_CHANCE_INCREASE_PER_LEVEL = 0.01;
export const FAVORITE_MINE_CHANCE_MAXIMUM = 1;

export const WORKCYCLE_TIMEOUT_BASE = 60;
export const WORKCYCLE_TIMEOUT_DECREASE_PER_LEVEL = 1;
export const WORKCYCLE_TIMEOUT_MINIMUM = 10;
