import { Coordinate } from './mine/Mine';
import { Observable } from 'knockout';
import GameHelper from '../GameHelper';
import {
    UNDERGROUND_BATTERY_COOLDOWN_SECONDS,
    UNDERGROUND_BATTERY_MAX_CHARGES, UNDERGROUND_EXPERIENCE_CLEAR_LAYER,
    UNDERGROUND_EXPERIENCE_DIG_UP_ITEM,
} from '../GameConstants';
import Rand from '../utilities/Rand';
import { UndergroundController } from './UndergroundController';
import Settings from '../settings';

type Pattern = Array<Array<{ coordinate: Coordinate, depth: number }>>;

export class UndergroundBattery {
    private _charges: Observable<number> = ko.observable(0);
    private _batteryCooldown: Observable<number> = ko.observable(0);

    private static _patterns: Array<Pattern> = [];

    private _dischargingPattern: Pattern | null = null;

    public static addPattern(id: string, tier: number, pattern: Pattern) {
        const totalDepthCleared: number = pattern.flatMap(value => value.flatMap(value1 => value1.depth)).reduce((previousValue, currentValue) => previousValue + currentValue, 0);
        this._patterns.push(pattern);

        // eslint-disable-next-line no-console
        console.log(`Adding '${id}', a tier ${tier} discharge, clearing ${totalDepthCleared} max total depth`);
    }

    public initialize() {

    }

    public update(delta: number) {
        if (this._batteryCooldown() > 0) {
            GameHelper.incrementObservable(this._batteryCooldown, -delta);
        }
    }

    public charge() {
        if (this._charges() >= UNDERGROUND_BATTERY_MAX_CHARGES) {
            return;
        }

        if (this._batteryCooldown() > 0) {
            return;
        }

        GameHelper.incrementObservable(this._charges, 1);
        this._batteryCooldown(UNDERGROUND_BATTERY_COOLDOWN_SECONDS);
    }

    public discharge() {
        // TODO : Check if I have enough charges to a discharge
        // TODO : Trigger effect
        // TODO : Subtract the required charges from the saved charges

        if (this._charges() < UNDERGROUND_BATTERY_MAX_CHARGES) {
            return;
        }

        this._dischargingPattern = JSON.parse(JSON.stringify(Rand.fromArray(UndergroundBattery._patterns)));
        this._charges(0);
        this.handleDischargingPattern();
    }

    private async handleDischargingPattern() {
        while (this._dischargingPattern?.length > 0) {
            const patternFrame = this._dischargingPattern.shift();

            const tilesMined = new Set<Coordinate>();

            patternFrame.forEach(patternEntry => {
                if (App.game.underground.mine.attemptBreakTile(patternEntry.coordinate, patternEntry.depth)) {
                    tilesMined.add(patternEntry.coordinate);
                }
            });

            const itemsFound = Array.from(tilesMined).map(coordinate => App.game.underground.mine.attemptFindItem(coordinate));
            itemsFound.forEach(value => {
                if (value) {
                    const { item, amount } = value;

                    UndergroundController.gainMineItem(item.id, amount);
                    UndergroundController.addPlayerUndergroundExp(UNDERGROUND_EXPERIENCE_DIG_UP_ITEM, true);

                    UndergroundController.notifyItemFound(item, amount);
                }
            });

            if (itemsFound.length > 0) {
                if (App.game.underground.mine.attemptCompleteLayer()) {
                    UndergroundController.addPlayerUndergroundExp(UNDERGROUND_EXPERIENCE_CLEAR_LAYER, true);

                    UndergroundController.notifyMineCompleted();

                    if (Settings.getSetting('autoRestartUndergroundMine').observableValue()) {
                        App.game.underground.generateMine(App.game.underground.autoSearchMineType);
                    }
                }
            }

            await new Promise(resolve => {
                setTimeout(resolve, 50);
            });
        }
    }

    get charges() {
        return this._charges();
    }

    get maxCharges() {
        return UNDERGROUND_BATTERY_MAX_CHARGES;
    }

    public fromJSON(save) {
        this._charges(save?.charges ?? 0);
        this._batteryCooldown(save?.batteryCooldown ?? 0);
    }

    public toJSON() {
        return {
            charges: this._charges(),
            batteryCooldown: this._batteryCooldown(),
        };
    }
}

UndergroundBattery.addPattern('eruption', 1, [
    [
        { coordinate:{ x:1, y:1 }, depth: 2 },
    ],
    [
        { coordinate:{ x:1, y:0 }, depth: 2 },
        { coordinate:{ x:0, y:1 }, depth: 2 },
        { coordinate:{ x:1, y:1 }, depth: 2 },
        { coordinate:{ x:2, y:1 }, depth: 2 },
        { coordinate:{ x:1, y:2 }, depth: 2 },
    ],
    [
        { coordinate:{ x:0, y:0 }, depth: 1 },
        { coordinate:{ x:1, y:0 }, depth: 1 },
        { coordinate:{ x:2, y:0 }, depth: 1 },
        { coordinate:{ x:0, y:1 }, depth: 1 },
        { coordinate:{ x:1, y:1 }, depth: 1 },
        { coordinate:{ x:2, y:1 }, depth: 1 },
        { coordinate:{ x:3, y:1 }, depth: 1 },
        { coordinate:{ x:0, y:2 }, depth: 1 },
        { coordinate:{ x:1, y:2 }, depth: 1 },
        { coordinate:{ x:2, y:2 }, depth: 1 },
        { coordinate:{ x:1, y:3 }, depth: 1 },
    ],
    [
        { coordinate:{ x:7, y:10 }, depth: 2 },
    ],
    [
        { coordinate:{ x:7, y:9 }, depth: 2 },
        { coordinate:{ x:6, y:10 }, depth: 2 },
        { coordinate:{ x:7, y:10 }, depth: 2 },
        { coordinate:{ x:8, y:10 }, depth: 2 },
        { coordinate:{ x:7, y:11 }, depth: 2 },
    ],
    [
        { coordinate:{ x:7, y:8 }, depth: 1 },
        { coordinate:{ x:6, y:9 }, depth: 1 },
        { coordinate:{ x:7, y:9 }, depth: 1 },
        { coordinate:{ x:8, y:9 }, depth: 1 },
        { coordinate:{ x:5, y:10 }, depth: 1 },
        { coordinate:{ x:6, y:10 }, depth: 1 },
        { coordinate:{ x:7, y:10 }, depth: 1 },
        { coordinate:{ x:8, y:10 }, depth: 1 },
        { coordinate:{ x:9, y:10 }, depth: 1 },
        { coordinate:{ x:6, y:11 }, depth: 1 },
        { coordinate:{ x:7, y:11 }, depth: 1 },
        { coordinate:{ x:8, y:11 }, depth: 1 },
    ],
    [
        { coordinate:{ x:21, y:3 }, depth: 2 },
    ],
    [
        { coordinate:{ x:21, y:2 }, depth: 2 },
        { coordinate:{ x:20, y:3 }, depth: 2 },
        { coordinate:{ x:21, y:3 }, depth: 2 },
        { coordinate:{ x:22, y:3 }, depth: 2 },
        { coordinate:{ x:21, y:4 }, depth: 2 },
    ],
    [
        { coordinate:{ x:21, y:1 }, depth: 1 },
        { coordinate:{ x:20, y:2 }, depth: 1 },
        { coordinate:{ x:21, y:2 }, depth: 1 },
        { coordinate:{ x:22, y:2 }, depth: 1 },
        { coordinate:{ x:19, y:3 }, depth: 1 },
        { coordinate:{ x:20, y:3 }, depth: 1 },
        { coordinate:{ x:21, y:3 }, depth: 1 },
        { coordinate:{ x:22, y:3 }, depth: 1 },
        { coordinate:{ x:23, y:3 }, depth: 1 },
        { coordinate:{ x:20, y:4 }, depth: 1 },
        { coordinate:{ x:21, y:4 }, depth: 1 },
        { coordinate:{ x:22, y:4 }, depth: 1 },
        { coordinate:{ x:21, y:5 }, depth: 1 },
    ],
    [
        { coordinate:{ x:15, y:7 }, depth: 2 },
    ],
    [
        { coordinate:{ x:15, y:6 }, depth: 2 },
        { coordinate:{ x:14, y:7 }, depth: 2 },
        { coordinate:{ x:15, y:7 }, depth: 2 },
        { coordinate:{ x:16, y:7 }, depth: 2 },
        { coordinate:{ x:15, y:8 }, depth: 2 },
    ],
    [
        { coordinate:{ x:15, y:5 }, depth: 1 },
        { coordinate:{ x:14, y:6 }, depth: 1 },
        { coordinate:{ x:15, y:6 }, depth: 1 },
        { coordinate:{ x:16, y:6 }, depth: 1 },
        { coordinate:{ x:13, y:7 }, depth: 1 },
        { coordinate:{ x:14, y:7 }, depth: 1 },
        { coordinate:{ x:15, y:7 }, depth: 1 },
        { coordinate:{ x:16, y:7 }, depth: 1 },
        { coordinate:{ x:17, y:7 }, depth: 1 },
        { coordinate:{ x:14, y:8 }, depth: 1 },
        { coordinate:{ x:15, y:8 }, depth: 1 },
        { coordinate:{ x:16, y:8 }, depth: 1 },
        { coordinate:{ x:15, y:9 }, depth: 1 },
    ],
    [
        { coordinate:{ x:9, y:2 }, depth: 2 },
    ],
    [
        { coordinate:{ x:9, y:1 }, depth: 2 },
        { coordinate:{ x:8, y:2 }, depth: 2 },
        { coordinate:{ x:9, y:2 }, depth: 2 },
        { coordinate:{ x:10, y:2 }, depth: 2 },
        { coordinate:{ x:9, y:3 }, depth: 2 },
    ],
    [
        { coordinate:{ x:9, y:0 }, depth: 1 },
        { coordinate:{ x:8, y:1 }, depth: 1 },
        { coordinate:{ x:9, y:1 }, depth: 1 },
        { coordinate:{ x:10, y:1 }, depth: 1 },
        { coordinate:{ x:7, y:2 }, depth: 1 },
        { coordinate:{ x:8, y:2 }, depth: 1 },
        { coordinate:{ x:9, y:2 }, depth: 1 },
        { coordinate:{ x:10, y:2 }, depth: 1 },
        { coordinate:{ x:11, y:2 }, depth: 1 },
        { coordinate:{ x:8, y:3 }, depth: 1 },
        { coordinate:{ x:9, y:3 }, depth: 1 },
        { coordinate:{ x:10, y:3 }, depth: 1 },
        { coordinate:{ x:9, y:4 }, depth: 1 },
    ],
    [
        { coordinate:{ x:22, y:10 }, depth: 2 },
    ],
    [
        { coordinate:{ x:22, y:9 }, depth: 2 },
        { coordinate:{ x:21, y:10 }, depth: 2 },
        { coordinate:{ x:22, y:10 }, depth: 2 },
        { coordinate:{ x:23, y:10 }, depth: 2 },
        { coordinate:{ x:22, y:11 }, depth: 2 },
    ],
    [
        { coordinate:{ x:22, y:8 }, depth: 1 },
        { coordinate:{ x:21, y:9 }, depth: 1 },
        { coordinate:{ x:22, y:9 }, depth: 1 },
        { coordinate:{ x:23, y:9 }, depth: 1 },
        { coordinate:{ x:20, y:10 }, depth: 1 },
        { coordinate:{ x:21, y:10 }, depth: 1 },
        { coordinate:{ x:22, y:10 }, depth: 1 },
        { coordinate:{ x:23, y:10 }, depth: 1 },
        { coordinate:{ x:24, y:10 }, depth: 1 },
        { coordinate:{ x:21, y:11 }, depth: 1 },
        { coordinate:{ x:22, y:11 }, depth: 1 },
        { coordinate:{ x:23, y:11 }, depth: 1 },
    ],
]);
UndergroundBattery.addPattern('hyperbearm', 5, [
    [
        { coordinate:{ x:0, y:5 }, depth: 1 },
        { coordinate:{ x:0, y:6 }, depth: 1 },
    ],
    [
        { coordinate:{ x:0, y:4 }, depth: 1 },
        { coordinate:{ x:0, y:5 }, depth: 1 },
        { coordinate:{ x:1, y:5 }, depth: 1 },
        { coordinate:{ x:0, y:6 }, depth: 1 },
        { coordinate:{ x:1, y:6 }, depth: 1 },
        { coordinate:{ x:0, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:0, y:4 }, depth: 1 },
        { coordinate:{ x:1, y:4 }, depth: 1 },
        { coordinate:{ x:0, y:5 }, depth: 1 },
        { coordinate:{ x:1, y:5 }, depth: 1 },
        { coordinate:{ x:2, y:5 }, depth: 1 },
        { coordinate:{ x:0, y:6 }, depth: 1 },
        { coordinate:{ x:1, y:6 }, depth: 1 },
        { coordinate:{ x:2, y:6 }, depth: 1 },
        { coordinate:{ x:0, y:7 }, depth: 1 },
        { coordinate:{ x:1, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:0, y:4 }, depth: 1 },
        { coordinate:{ x:1, y:4 }, depth: 1 },
        { coordinate:{ x:2, y:4 }, depth: 1 },
        { coordinate:{ x:0, y:5 }, depth: 1 },
        { coordinate:{ x:1, y:5 }, depth: 1 },
        { coordinate:{ x:2, y:5 }, depth: 1 },
        { coordinate:{ x:3, y:5 }, depth: 1 },
        { coordinate:{ x:0, y:6 }, depth: 1 },
        { coordinate:{ x:1, y:6 }, depth: 1 },
        { coordinate:{ x:2, y:6 }, depth: 1 },
        { coordinate:{ x:3, y:6 }, depth: 1 },
        { coordinate:{ x:0, y:7 }, depth: 1 },
        { coordinate:{ x:1, y:7 }, depth: 1 },
        { coordinate:{ x:2, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:0, y:4 }, depth: 1 },
        { coordinate:{ x:1, y:4 }, depth: 1 },
        { coordinate:{ x:2, y:4 }, depth: 1 },
        { coordinate:{ x:3, y:4 }, depth: 1 },
        { coordinate:{ x:0, y:5 }, depth: 1 },
        { coordinate:{ x:1, y:5 }, depth: 1 },
        { coordinate:{ x:2, y:5 }, depth: 1 },
        { coordinate:{ x:3, y:5 }, depth: 1 },
        { coordinate:{ x:4, y:5 }, depth: 1 },
        { coordinate:{ x:0, y:6 }, depth: 1 },
        { coordinate:{ x:1, y:6 }, depth: 1 },
        { coordinate:{ x:2, y:6 }, depth: 1 },
        { coordinate:{ x:3, y:6 }, depth: 1 },
        { coordinate:{ x:4, y:6 }, depth: 1 },
        { coordinate:{ x:0, y:7 }, depth: 1 },
        { coordinate:{ x:1, y:7 }, depth: 1 },
        { coordinate:{ x:2, y:7 }, depth: 1 },
        { coordinate:{ x:3, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:0, y:4 }, depth: 1 },
        { coordinate:{ x:1, y:4 }, depth: 1 },
        { coordinate:{ x:2, y:4 }, depth: 1 },
        { coordinate:{ x:3, y:4 }, depth: 1 },
        { coordinate:{ x:4, y:4 }, depth: 1 },
        { coordinate:{ x:1, y:5 }, depth: 1 },
        { coordinate:{ x:2, y:5 }, depth: 1 },
        { coordinate:{ x:3, y:5 }, depth: 1 },
        { coordinate:{ x:4, y:5 }, depth: 1 },
        { coordinate:{ x:5, y:5 }, depth: 1 },
        { coordinate:{ x:1, y:6 }, depth: 1 },
        { coordinate:{ x:2, y:6 }, depth: 1 },
        { coordinate:{ x:3, y:6 }, depth: 1 },
        { coordinate:{ x:4, y:6 }, depth: 1 },
        { coordinate:{ x:5, y:6 }, depth: 1 },
        { coordinate:{ x:0, y:7 }, depth: 1 },
        { coordinate:{ x:1, y:7 }, depth: 1 },
        { coordinate:{ x:2, y:7 }, depth: 1 },
        { coordinate:{ x:3, y:7 }, depth: 1 },
        { coordinate:{ x:4, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:1, y:4 }, depth: 1 },
        { coordinate:{ x:2, y:4 }, depth: 1 },
        { coordinate:{ x:3, y:4 }, depth: 1 },
        { coordinate:{ x:4, y:4 }, depth: 1 },
        { coordinate:{ x:5, y:4 }, depth: 1 },
        { coordinate:{ x:2, y:5 }, depth: 1 },
        { coordinate:{ x:3, y:5 }, depth: 1 },
        { coordinate:{ x:4, y:5 }, depth: 1 },
        { coordinate:{ x:5, y:5 }, depth: 1 },
        { coordinate:{ x:6, y:5 }, depth: 1 },
        { coordinate:{ x:2, y:6 }, depth: 1 },
        { coordinate:{ x:3, y:6 }, depth: 1 },
        { coordinate:{ x:4, y:6 }, depth: 1 },
        { coordinate:{ x:5, y:6 }, depth: 1 },
        { coordinate:{ x:6, y:6 }, depth: 1 },
        { coordinate:{ x:1, y:7 }, depth: 1 },
        { coordinate:{ x:2, y:7 }, depth: 1 },
        { coordinate:{ x:3, y:7 }, depth: 1 },
        { coordinate:{ x:4, y:7 }, depth: 1 },
        { coordinate:{ x:5, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:2, y:4 }, depth: 1 },
        { coordinate:{ x:3, y:4 }, depth: 1 },
        { coordinate:{ x:4, y:4 }, depth: 1 },
        { coordinate:{ x:5, y:4 }, depth: 1 },
        { coordinate:{ x:6, y:4 }, depth: 1 },
        { coordinate:{ x:3, y:5 }, depth: 1 },
        { coordinate:{ x:4, y:5 }, depth: 1 },
        { coordinate:{ x:5, y:5 }, depth: 1 },
        { coordinate:{ x:6, y:5 }, depth: 1 },
        { coordinate:{ x:7, y:5 }, depth: 1 },
        { coordinate:{ x:3, y:6 }, depth: 1 },
        { coordinate:{ x:4, y:6 }, depth: 1 },
        { coordinate:{ x:5, y:6 }, depth: 1 },
        { coordinate:{ x:6, y:6 }, depth: 1 },
        { coordinate:{ x:7, y:6 }, depth: 1 },
        { coordinate:{ x:2, y:7 }, depth: 1 },
        { coordinate:{ x:3, y:7 }, depth: 1 },
        { coordinate:{ x:4, y:7 }, depth: 1 },
        { coordinate:{ x:5, y:7 }, depth: 1 },
        { coordinate:{ x:6, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:3, y:4 }, depth: 1 },
        { coordinate:{ x:4, y:4 }, depth: 1 },
        { coordinate:{ x:5, y:4 }, depth: 1 },
        { coordinate:{ x:6, y:4 }, depth: 1 },
        { coordinate:{ x:7, y:4 }, depth: 1 },
        { coordinate:{ x:4, y:5 }, depth: 1 },
        { coordinate:{ x:5, y:5 }, depth: 1 },
        { coordinate:{ x:6, y:5 }, depth: 1 },
        { coordinate:{ x:7, y:5 }, depth: 1 },
        { coordinate:{ x:8, y:5 }, depth: 1 },
        { coordinate:{ x:4, y:6 }, depth: 1 },
        { coordinate:{ x:5, y:6 }, depth: 1 },
        { coordinate:{ x:6, y:6 }, depth: 1 },
        { coordinate:{ x:7, y:6 }, depth: 1 },
        { coordinate:{ x:8, y:6 }, depth: 1 },
        { coordinate:{ x:3, y:7 }, depth: 1 },
        { coordinate:{ x:4, y:7 }, depth: 1 },
        { coordinate:{ x:5, y:7 }, depth: 1 },
        { coordinate:{ x:6, y:7 }, depth: 1 },
        { coordinate:{ x:7, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:4, y:4 }, depth: 1 },
        { coordinate:{ x:5, y:4 }, depth: 1 },
        { coordinate:{ x:6, y:4 }, depth: 1 },
        { coordinate:{ x:7, y:4 }, depth: 1 },
        { coordinate:{ x:8, y:4 }, depth: 1 },
        { coordinate:{ x:5, y:5 }, depth: 1 },
        { coordinate:{ x:6, y:5 }, depth: 1 },
        { coordinate:{ x:7, y:5 }, depth: 1 },
        { coordinate:{ x:8, y:5 }, depth: 1 },
        { coordinate:{ x:9, y:5 }, depth: 1 },
        { coordinate:{ x:5, y:6 }, depth: 1 },
        { coordinate:{ x:6, y:6 }, depth: 1 },
        { coordinate:{ x:7, y:6 }, depth: 1 },
        { coordinate:{ x:8, y:6 }, depth: 1 },
        { coordinate:{ x:9, y:6 }, depth: 1 },
        { coordinate:{ x:4, y:7 }, depth: 1 },
        { coordinate:{ x:5, y:7 }, depth: 1 },
        { coordinate:{ x:6, y:7 }, depth: 1 },
        { coordinate:{ x:7, y:7 }, depth: 1 },
        { coordinate:{ x:8, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:5, y:4 }, depth: 1 },
        { coordinate:{ x:6, y:4 }, depth: 1 },
        { coordinate:{ x:7, y:4 }, depth: 1 },
        { coordinate:{ x:8, y:4 }, depth: 1 },
        { coordinate:{ x:9, y:4 }, depth: 1 },
        { coordinate:{ x:6, y:5 }, depth: 1 },
        { coordinate:{ x:7, y:5 }, depth: 1 },
        { coordinate:{ x:8, y:5 }, depth: 1 },
        { coordinate:{ x:9, y:5 }, depth: 1 },
        { coordinate:{ x:10, y:5 }, depth: 1 },
        { coordinate:{ x:6, y:6 }, depth: 1 },
        { coordinate:{ x:7, y:6 }, depth: 1 },
        { coordinate:{ x:8, y:6 }, depth: 1 },
        { coordinate:{ x:9, y:6 }, depth: 1 },
        { coordinate:{ x:10, y:6 }, depth: 1 },
        { coordinate:{ x:5, y:7 }, depth: 1 },
        { coordinate:{ x:6, y:7 }, depth: 1 },
        { coordinate:{ x:7, y:7 }, depth: 1 },
        { coordinate:{ x:8, y:7 }, depth: 1 },
        { coordinate:{ x:9, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:6, y:4 }, depth: 1 },
        { coordinate:{ x:7, y:4 }, depth: 1 },
        { coordinate:{ x:8, y:4 }, depth: 1 },
        { coordinate:{ x:9, y:4 }, depth: 1 },
        { coordinate:{ x:10, y:4 }, depth: 1 },
        { coordinate:{ x:7, y:5 }, depth: 1 },
        { coordinate:{ x:8, y:5 }, depth: 1 },
        { coordinate:{ x:9, y:5 }, depth: 1 },
        { coordinate:{ x:10, y:5 }, depth: 1 },
        { coordinate:{ x:11, y:5 }, depth: 1 },
        { coordinate:{ x:7, y:6 }, depth: 1 },
        { coordinate:{ x:8, y:6 }, depth: 1 },
        { coordinate:{ x:9, y:6 }, depth: 1 },
        { coordinate:{ x:10, y:6 }, depth: 1 },
        { coordinate:{ x:11, y:6 }, depth: 1 },
        { coordinate:{ x:6, y:7 }, depth: 1 },
        { coordinate:{ x:7, y:7 }, depth: 1 },
        { coordinate:{ x:8, y:7 }, depth: 1 },
        { coordinate:{ x:9, y:7 }, depth: 1 },
        { coordinate:{ x:10, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:7, y:4 }, depth: 1 },
        { coordinate:{ x:8, y:4 }, depth: 1 },
        { coordinate:{ x:9, y:4 }, depth: 1 },
        { coordinate:{ x:10, y:4 }, depth: 1 },
        { coordinate:{ x:11, y:4 }, depth: 1 },
        { coordinate:{ x:8, y:5 }, depth: 1 },
        { coordinate:{ x:9, y:5 }, depth: 1 },
        { coordinate:{ x:10, y:5 }, depth: 1 },
        { coordinate:{ x:11, y:5 }, depth: 1 },
        { coordinate:{ x:12, y:5 }, depth: 1 },
        { coordinate:{ x:8, y:6 }, depth: 1 },
        { coordinate:{ x:9, y:6 }, depth: 1 },
        { coordinate:{ x:10, y:6 }, depth: 1 },
        { coordinate:{ x:11, y:6 }, depth: 1 },
        { coordinate:{ x:12, y:6 }, depth: 1 },
        { coordinate:{ x:7, y:7 }, depth: 1 },
        { coordinate:{ x:8, y:7 }, depth: 1 },
        { coordinate:{ x:9, y:7 }, depth: 1 },
        { coordinate:{ x:10, y:7 }, depth: 1 },
        { coordinate:{ x:11, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:8, y:4 }, depth: 1 },
        { coordinate:{ x:9, y:4 }, depth: 1 },
        { coordinate:{ x:10, y:4 }, depth: 1 },
        { coordinate:{ x:11, y:4 }, depth: 1 },
        { coordinate:{ x:12, y:4 }, depth: 1 },
        { coordinate:{ x:9, y:5 }, depth: 1 },
        { coordinate:{ x:10, y:5 }, depth: 1 },
        { coordinate:{ x:11, y:5 }, depth: 1 },
        { coordinate:{ x:12, y:5 }, depth: 1 },
        { coordinate:{ x:13, y:5 }, depth: 1 },
        { coordinate:{ x:9, y:6 }, depth: 1 },
        { coordinate:{ x:10, y:6 }, depth: 1 },
        { coordinate:{ x:11, y:6 }, depth: 1 },
        { coordinate:{ x:12, y:6 }, depth: 1 },
        { coordinate:{ x:13, y:6 }, depth: 1 },
        { coordinate:{ x:8, y:7 }, depth: 1 },
        { coordinate:{ x:9, y:7 }, depth: 1 },
        { coordinate:{ x:10, y:7 }, depth: 1 },
        { coordinate:{ x:11, y:7 }, depth: 1 },
        { coordinate:{ x:12, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:9, y:4 }, depth: 1 },
        { coordinate:{ x:10, y:4 }, depth: 1 },
        { coordinate:{ x:11, y:4 }, depth: 1 },
        { coordinate:{ x:12, y:4 }, depth: 1 },
        { coordinate:{ x:13, y:4 }, depth: 1 },
        { coordinate:{ x:10, y:5 }, depth: 1 },
        { coordinate:{ x:11, y:5 }, depth: 1 },
        { coordinate:{ x:12, y:5 }, depth: 1 },
        { coordinate:{ x:13, y:5 }, depth: 1 },
        { coordinate:{ x:14, y:5 }, depth: 1 },
        { coordinate:{ x:10, y:6 }, depth: 1 },
        { coordinate:{ x:11, y:6 }, depth: 1 },
        { coordinate:{ x:12, y:6 }, depth: 1 },
        { coordinate:{ x:13, y:6 }, depth: 1 },
        { coordinate:{ x:14, y:6 }, depth: 1 },
        { coordinate:{ x:9, y:7 }, depth: 1 },
        { coordinate:{ x:10, y:7 }, depth: 1 },
        { coordinate:{ x:11, y:7 }, depth: 1 },
        { coordinate:{ x:12, y:7 }, depth: 1 },
        { coordinate:{ x:13, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:10, y:4 }, depth: 1 },
        { coordinate:{ x:11, y:4 }, depth: 1 },
        { coordinate:{ x:12, y:4 }, depth: 1 },
        { coordinate:{ x:13, y:4 }, depth: 1 },
        { coordinate:{ x:14, y:4 }, depth: 1 },
        { coordinate:{ x:11, y:5 }, depth: 1 },
        { coordinate:{ x:12, y:5 }, depth: 1 },
        { coordinate:{ x:13, y:5 }, depth: 1 },
        { coordinate:{ x:14, y:5 }, depth: 1 },
        { coordinate:{ x:15, y:5 }, depth: 1 },
        { coordinate:{ x:11, y:6 }, depth: 1 },
        { coordinate:{ x:12, y:6 }, depth: 1 },
        { coordinate:{ x:13, y:6 }, depth: 1 },
        { coordinate:{ x:14, y:6 }, depth: 1 },
        { coordinate:{ x:15, y:6 }, depth: 1 },
        { coordinate:{ x:10, y:7 }, depth: 1 },
        { coordinate:{ x:11, y:7 }, depth: 1 },
        { coordinate:{ x:12, y:7 }, depth: 1 },
        { coordinate:{ x:13, y:7 }, depth: 1 },
        { coordinate:{ x:14, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:11, y:4 }, depth: 1 },
        { coordinate:{ x:12, y:4 }, depth: 1 },
        { coordinate:{ x:13, y:4 }, depth: 1 },
        { coordinate:{ x:14, y:4 }, depth: 1 },
        { coordinate:{ x:15, y:4 }, depth: 1 },
        { coordinate:{ x:12, y:5 }, depth: 1 },
        { coordinate:{ x:13, y:5 }, depth: 1 },
        { coordinate:{ x:14, y:5 }, depth: 1 },
        { coordinate:{ x:15, y:5 }, depth: 1 },
        { coordinate:{ x:16, y:5 }, depth: 1 },
        { coordinate:{ x:12, y:6 }, depth: 1 },
        { coordinate:{ x:13, y:6 }, depth: 1 },
        { coordinate:{ x:14, y:6 }, depth: 1 },
        { coordinate:{ x:15, y:6 }, depth: 1 },
        { coordinate:{ x:16, y:6 }, depth: 1 },
        { coordinate:{ x:11, y:7 }, depth: 1 },
        { coordinate:{ x:12, y:7 }, depth: 1 },
        { coordinate:{ x:13, y:7 }, depth: 1 },
        { coordinate:{ x:14, y:7 }, depth: 1 },
        { coordinate:{ x:15, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:12, y:4 }, depth: 1 },
        { coordinate:{ x:13, y:4 }, depth: 1 },
        { coordinate:{ x:14, y:4 }, depth: 1 },
        { coordinate:{ x:15, y:4 }, depth: 1 },
        { coordinate:{ x:16, y:4 }, depth: 1 },
        { coordinate:{ x:13, y:5 }, depth: 1 },
        { coordinate:{ x:14, y:5 }, depth: 1 },
        { coordinate:{ x:15, y:5 }, depth: 1 },
        { coordinate:{ x:16, y:5 }, depth: 1 },
        { coordinate:{ x:17, y:5 }, depth: 1 },
        { coordinate:{ x:13, y:6 }, depth: 1 },
        { coordinate:{ x:14, y:6 }, depth: 1 },
        { coordinate:{ x:15, y:6 }, depth: 1 },
        { coordinate:{ x:16, y:6 }, depth: 1 },
        { coordinate:{ x:17, y:6 }, depth: 1 },
        { coordinate:{ x:12, y:7 }, depth: 1 },
        { coordinate:{ x:13, y:7 }, depth: 1 },
        { coordinate:{ x:14, y:7 }, depth: 1 },
        { coordinate:{ x:15, y:7 }, depth: 1 },
        { coordinate:{ x:16, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:13, y:4 }, depth: 1 },
        { coordinate:{ x:14, y:4 }, depth: 1 },
        { coordinate:{ x:15, y:4 }, depth: 1 },
        { coordinate:{ x:16, y:4 }, depth: 1 },
        { coordinate:{ x:17, y:4 }, depth: 1 },
        { coordinate:{ x:14, y:5 }, depth: 1 },
        { coordinate:{ x:15, y:5 }, depth: 1 },
        { coordinate:{ x:16, y:5 }, depth: 1 },
        { coordinate:{ x:17, y:5 }, depth: 1 },
        { coordinate:{ x:18, y:5 }, depth: 1 },
        { coordinate:{ x:14, y:6 }, depth: 1 },
        { coordinate:{ x:15, y:6 }, depth: 1 },
        { coordinate:{ x:16, y:6 }, depth: 1 },
        { coordinate:{ x:17, y:6 }, depth: 1 },
        { coordinate:{ x:18, y:6 }, depth: 1 },
        { coordinate:{ x:13, y:7 }, depth: 1 },
        { coordinate:{ x:14, y:7 }, depth: 1 },
        { coordinate:{ x:15, y:7 }, depth: 1 },
        { coordinate:{ x:16, y:7 }, depth: 1 },
        { coordinate:{ x:17, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:14, y:4 }, depth: 1 },
        { coordinate:{ x:15, y:4 }, depth: 1 },
        { coordinate:{ x:16, y:4 }, depth: 1 },
        { coordinate:{ x:17, y:4 }, depth: 1 },
        { coordinate:{ x:18, y:4 }, depth: 1 },
        { coordinate:{ x:15, y:5 }, depth: 1 },
        { coordinate:{ x:16, y:5 }, depth: 1 },
        { coordinate:{ x:17, y:5 }, depth: 1 },
        { coordinate:{ x:18, y:5 }, depth: 1 },
        { coordinate:{ x:19, y:5 }, depth: 1 },
        { coordinate:{ x:15, y:6 }, depth: 1 },
        { coordinate:{ x:16, y:6 }, depth: 1 },
        { coordinate:{ x:17, y:6 }, depth: 1 },
        { coordinate:{ x:18, y:6 }, depth: 1 },
        { coordinate:{ x:19, y:6 }, depth: 1 },
        { coordinate:{ x:14, y:7 }, depth: 1 },
        { coordinate:{ x:15, y:7 }, depth: 1 },
        { coordinate:{ x:16, y:7 }, depth: 1 },
        { coordinate:{ x:17, y:7 }, depth: 1 },
        { coordinate:{ x:18, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:15, y:4 }, depth: 1 },
        { coordinate:{ x:16, y:4 }, depth: 1 },
        { coordinate:{ x:17, y:4 }, depth: 1 },
        { coordinate:{ x:18, y:4 }, depth: 1 },
        { coordinate:{ x:19, y:4 }, depth: 1 },
        { coordinate:{ x:16, y:5 }, depth: 1 },
        { coordinate:{ x:17, y:5 }, depth: 1 },
        { coordinate:{ x:18, y:5 }, depth: 1 },
        { coordinate:{ x:19, y:5 }, depth: 1 },
        { coordinate:{ x:20, y:5 }, depth: 1 },
        { coordinate:{ x:16, y:6 }, depth: 1 },
        { coordinate:{ x:17, y:6 }, depth: 1 },
        { coordinate:{ x:18, y:6 }, depth: 1 },
        { coordinate:{ x:19, y:6 }, depth: 1 },
        { coordinate:{ x:20, y:6 }, depth: 1 },
        { coordinate:{ x:15, y:7 }, depth: 1 },
        { coordinate:{ x:16, y:7 }, depth: 1 },
        { coordinate:{ x:17, y:7 }, depth: 1 },
        { coordinate:{ x:18, y:7 }, depth: 1 },
        { coordinate:{ x:19, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:16, y:4 }, depth: 1 },
        { coordinate:{ x:17, y:4 }, depth: 1 },
        { coordinate:{ x:18, y:4 }, depth: 1 },
        { coordinate:{ x:19, y:4 }, depth: 1 },
        { coordinate:{ x:20, y:4 }, depth: 1 },
        { coordinate:{ x:17, y:5 }, depth: 1 },
        { coordinate:{ x:18, y:5 }, depth: 1 },
        { coordinate:{ x:19, y:5 }, depth: 1 },
        { coordinate:{ x:20, y:5 }, depth: 1 },
        { coordinate:{ x:21, y:5 }, depth: 1 },
        { coordinate:{ x:17, y:6 }, depth: 1 },
        { coordinate:{ x:18, y:6 }, depth: 1 },
        { coordinate:{ x:19, y:6 }, depth: 1 },
        { coordinate:{ x:20, y:6 }, depth: 1 },
        { coordinate:{ x:21, y:6 }, depth: 1 },
        { coordinate:{ x:16, y:7 }, depth: 1 },
        { coordinate:{ x:17, y:7 }, depth: 1 },
        { coordinate:{ x:18, y:7 }, depth: 1 },
        { coordinate:{ x:19, y:7 }, depth: 1 },
        { coordinate:{ x:20, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:17, y:4 }, depth: 1 },
        { coordinate:{ x:18, y:4 }, depth: 1 },
        { coordinate:{ x:19, y:4 }, depth: 1 },
        { coordinate:{ x:20, y:4 }, depth: 1 },
        { coordinate:{ x:21, y:4 }, depth: 1 },
        { coordinate:{ x:18, y:5 }, depth: 1 },
        { coordinate:{ x:19, y:5 }, depth: 1 },
        { coordinate:{ x:20, y:5 }, depth: 1 },
        { coordinate:{ x:21, y:5 }, depth: 1 },
        { coordinate:{ x:22, y:5 }, depth: 1 },
        { coordinate:{ x:18, y:6 }, depth: 1 },
        { coordinate:{ x:19, y:6 }, depth: 1 },
        { coordinate:{ x:20, y:6 }, depth: 1 },
        { coordinate:{ x:21, y:6 }, depth: 1 },
        { coordinate:{ x:22, y:6 }, depth: 1 },
        { coordinate:{ x:17, y:7 }, depth: 1 },
        { coordinate:{ x:18, y:7 }, depth: 1 },
        { coordinate:{ x:19, y:7 }, depth: 1 },
        { coordinate:{ x:20, y:7 }, depth: 1 },
        { coordinate:{ x:21, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:18, y:4 }, depth: 1 },
        { coordinate:{ x:19, y:4 }, depth: 1 },
        { coordinate:{ x:20, y:4 }, depth: 1 },
        { coordinate:{ x:21, y:4 }, depth: 1 },
        { coordinate:{ x:22, y:4 }, depth: 1 },
        { coordinate:{ x:19, y:5 }, depth: 1 },
        { coordinate:{ x:20, y:5 }, depth: 1 },
        { coordinate:{ x:21, y:5 }, depth: 1 },
        { coordinate:{ x:22, y:5 }, depth: 1 },
        { coordinate:{ x:23, y:5 }, depth: 1 },
        { coordinate:{ x:19, y:6 }, depth: 1 },
        { coordinate:{ x:20, y:6 }, depth: 1 },
        { coordinate:{ x:21, y:6 }, depth: 1 },
        { coordinate:{ x:22, y:6 }, depth: 1 },
        { coordinate:{ x:23, y:6 }, depth: 1 },
        { coordinate:{ x:18, y:7 }, depth: 1 },
        { coordinate:{ x:19, y:7 }, depth: 1 },
        { coordinate:{ x:20, y:7 }, depth: 1 },
        { coordinate:{ x:21, y:7 }, depth: 1 },
        { coordinate:{ x:22, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:19, y:4 }, depth: 1 },
        { coordinate:{ x:20, y:4 }, depth: 1 },
        { coordinate:{ x:21, y:4 }, depth: 1 },
        { coordinate:{ x:22, y:4 }, depth: 1 },
        { coordinate:{ x:23, y:4 }, depth: 1 },
        { coordinate:{ x:20, y:5 }, depth: 1 },
        { coordinate:{ x:21, y:5 }, depth: 1 },
        { coordinate:{ x:22, y:5 }, depth: 1 },
        { coordinate:{ x:23, y:5 }, depth: 1 },
        { coordinate:{ x:24, y:5 }, depth: 1 },
        { coordinate:{ x:20, y:6 }, depth: 1 },
        { coordinate:{ x:21, y:6 }, depth: 1 },
        { coordinate:{ x:22, y:6 }, depth: 1 },
        { coordinate:{ x:23, y:6 }, depth: 1 },
        { coordinate:{ x:24, y:6 }, depth: 1 },
        { coordinate:{ x:19, y:7 }, depth: 1 },
        { coordinate:{ x:20, y:7 }, depth: 1 },
        { coordinate:{ x:21, y:7 }, depth: 1 },
        { coordinate:{ x:22, y:7 }, depth: 1 },
        { coordinate:{ x:23, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:20, y:4 }, depth: 1 },
        { coordinate:{ x:21, y:4 }, depth: 1 },
        { coordinate:{ x:22, y:4 }, depth: 1 },
        { coordinate:{ x:23, y:4 }, depth: 1 },
        { coordinate:{ x:24, y:4 }, depth: 1 },
        { coordinate:{ x:21, y:5 }, depth: 1 },
        { coordinate:{ x:22, y:5 }, depth: 1 },
        { coordinate:{ x:23, y:5 }, depth: 1 },
        { coordinate:{ x:24, y:5 }, depth: 1 },
        { coordinate:{ x:21, y:6 }, depth: 1 },
        { coordinate:{ x:22, y:6 }, depth: 1 },
        { coordinate:{ x:23, y:6 }, depth: 1 },
        { coordinate:{ x:24, y:6 }, depth: 1 },
        { coordinate:{ x:20, y:7 }, depth: 1 },
        { coordinate:{ x:21, y:7 }, depth: 1 },
        { coordinate:{ x:22, y:7 }, depth: 1 },
        { coordinate:{ x:23, y:7 }, depth: 1 },
        { coordinate:{ x:24, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:21, y:4 }, depth: 1 },
        { coordinate:{ x:22, y:4 }, depth: 1 },
        { coordinate:{ x:23, y:4 }, depth: 1 },
        { coordinate:{ x:24, y:4 }, depth: 1 },
        { coordinate:{ x:22, y:5 }, depth: 1 },
        { coordinate:{ x:23, y:5 }, depth: 1 },
        { coordinate:{ x:24, y:5 }, depth: 1 },
        { coordinate:{ x:22, y:6 }, depth: 1 },
        { coordinate:{ x:23, y:6 }, depth: 1 },
        { coordinate:{ x:24, y:6 }, depth: 1 },
        { coordinate:{ x:21, y:7 }, depth: 1 },
        { coordinate:{ x:22, y:7 }, depth: 1 },
        { coordinate:{ x:23, y:7 }, depth: 1 },
        { coordinate:{ x:24, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:22, y:4 }, depth: 1 },
        { coordinate:{ x:23, y:4 }, depth: 1 },
        { coordinate:{ x:24, y:4 }, depth: 1 },
        { coordinate:{ x:23, y:5 }, depth: 1 },
        { coordinate:{ x:24, y:5 }, depth: 1 },
        { coordinate:{ x:23, y:6 }, depth: 1 },
        { coordinate:{ x:24, y:6 }, depth: 1 },
        { coordinate:{ x:22, y:7 }, depth: 1 },
        { coordinate:{ x:23, y:7 }, depth: 1 },
        { coordinate:{ x:24, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:23, y:4 }, depth: 1 },
        { coordinate:{ x:24, y:4 }, depth: 1 },
        { coordinate:{ x:24, y:5 }, depth: 1 },
        { coordinate:{ x:24, y:6 }, depth: 1 },
        { coordinate:{ x:23, y:7 }, depth: 1 },
        { coordinate:{ x:24, y:7 }, depth: 1 },
    ],
    [
        { coordinate:{ x:24, y:4 }, depth: 1 },
        { coordinate:{ x:24, y:7 }, depth: 1 },
    ],
]);
UndergroundBattery.addPattern('explosion', 5, [
    [
        { coordinate:{ x:11, y:3 }, depth:1 },
        { coordinate:{ x:12, y:3 }, depth:1 },
        { coordinate:{ x:10, y:4 }, depth:1 },
        { coordinate:{ x:11, y:4 }, depth:1 },
        { coordinate:{ x:12, y:4 }, depth:1 },
        { coordinate:{ x:13, y:4 }, depth:1 },
        { coordinate:{ x:9, y:5 }, depth:1 },
        { coordinate:{ x:10, y:5 }, depth:1 },
        { coordinate:{ x:11, y:5 }, depth:1 },
        { coordinate:{ x:12, y:5 }, depth:1 },
        { coordinate:{ x:13, y:5 }, depth:1 },
        { coordinate:{ x:14, y:5 }, depth:1 },
        { coordinate:{ x:9, y:6 }, depth:1 },
        { coordinate:{ x:10, y:6 }, depth:1 },
        { coordinate:{ x:11, y:6 }, depth:1 },
        { coordinate:{ x:12, y:6 }, depth:1 },
        { coordinate:{ x:13, y:6 }, depth:1 },
        { coordinate:{ x:14, y:6 }, depth:1 },
        { coordinate:{ x:10, y:7 }, depth:1 },
        { coordinate:{ x:11, y:7 }, depth:1 },
        { coordinate:{ x:12, y:7 }, depth:1 },
        { coordinate:{ x:13, y:7 }, depth:1 },
        { coordinate:{ x:11, y:8 }, depth:1 },
        { coordinate:{ x:12, y:8 }, depth:1 },
    ],
    [
        { coordinate:{ x:10, y:1 }, depth:1 },
        { coordinate:{ x:11, y:1 }, depth:1 },
        { coordinate:{ x:12, y:1 }, depth:1 },
        { coordinate:{ x:13, y:1 }, depth:1 },
        { coordinate:{ x:9, y:2 }, depth:1 },
        { coordinate:{ x:10, y:2 }, depth:1 },
        { coordinate:{ x:11, y:2 }, depth:1 },
        { coordinate:{ x:12, y:2 }, depth:1 },
        { coordinate:{ x:13, y:2 }, depth:1 },
        { coordinate:{ x:14, y:2 }, depth:1 },
        { coordinate:{ x:8, y:3 }, depth:1 },
        { coordinate:{ x:9, y:3 }, depth:1 },
        { coordinate:{ x:10, y:3 }, depth:1 },
        { coordinate:{ x:11, y:3 }, depth:1 },
        { coordinate:{ x:12, y:3 }, depth:1 },
        { coordinate:{ x:13, y:3 }, depth:1 },
        { coordinate:{ x:14, y:3 }, depth:1 },
        { coordinate:{ x:15, y:3 }, depth:1 },
        { coordinate:{ x:7, y:4 }, depth:1 },
        { coordinate:{ x:8, y:4 }, depth:1 },
        { coordinate:{ x:9, y:4 }, depth:1 },
        { coordinate:{ x:10, y:4 }, depth:1 },
        { coordinate:{ x:11, y:4 }, depth:1 },
        { coordinate:{ x:12, y:4 }, depth:1 },
        { coordinate:{ x:13, y:4 }, depth:1 },
        { coordinate:{ x:14, y:4 }, depth:1 },
        { coordinate:{ x:15, y:4 }, depth:1 },
        { coordinate:{ x:16, y:4 }, depth:1 },
        { coordinate:{ x:7, y:5 }, depth:1 },
        { coordinate:{ x:8, y:5 }, depth:1 },
        { coordinate:{ x:9, y:5 }, depth:1 },
        { coordinate:{ x:10, y:5 }, depth:1 },
        { coordinate:{ x:11, y:5 }, depth:1 },
        { coordinate:{ x:12, y:5 }, depth:1 },
        { coordinate:{ x:13, y:5 }, depth:1 },
        { coordinate:{ x:14, y:5 }, depth:1 },
        { coordinate:{ x:15, y:5 }, depth:1 },
        { coordinate:{ x:16, y:5 }, depth:1 },
        { coordinate:{ x:7, y:6 }, depth:1 },
        { coordinate:{ x:8, y:6 }, depth:1 },
        { coordinate:{ x:9, y:6 }, depth:1 },
        { coordinate:{ x:10, y:6 }, depth:1 },
        { coordinate:{ x:11, y:6 }, depth:1 },
        { coordinate:{ x:12, y:6 }, depth:1 },
        { coordinate:{ x:13, y:6 }, depth:1 },
        { coordinate:{ x:14, y:6 }, depth:1 },
        { coordinate:{ x:15, y:6 }, depth:1 },
        { coordinate:{ x:16, y:6 }, depth:1 },
        { coordinate:{ x:7, y:7 }, depth:1 },
        { coordinate:{ x:8, y:7 }, depth:1 },
        { coordinate:{ x:9, y:7 }, depth:1 },
        { coordinate:{ x:10, y:7 }, depth:1 },
        { coordinate:{ x:11, y:7 }, depth:1 },
        { coordinate:{ x:12, y:7 }, depth:1 },
        { coordinate:{ x:13, y:7 }, depth:1 },
        { coordinate:{ x:14, y:7 }, depth:1 },
        { coordinate:{ x:15, y:7 }, depth:1 },
        { coordinate:{ x:16, y:7 }, depth:1 },
        { coordinate:{ x:8, y:8 }, depth:1 },
        { coordinate:{ x:9, y:8 }, depth:1 },
        { coordinate:{ x:10, y:8 }, depth:1 },
        { coordinate:{ x:11, y:8 }, depth:1 },
        { coordinate:{ x:12, y:8 }, depth:1 },
        { coordinate:{ x:13, y:8 }, depth:1 },
        { coordinate:{ x:14, y:8 }, depth:1 },
        { coordinate:{ x:15, y:8 }, depth:1 },
        { coordinate:{ x:9, y:9 }, depth:1 },
        { coordinate:{ x:10, y:9 }, depth:1 },
        { coordinate:{ x:11, y:9 }, depth:1 },
        { coordinate:{ x:12, y:9 }, depth:1 },
        { coordinate:{ x:13, y:9 }, depth:1 },
        { coordinate:{ x:14, y:9 }, depth:1 },
        { coordinate:{ x:10, y:10 }, depth:1 },
        { coordinate:{ x:11, y:10 }, depth:1 },
        { coordinate:{ x:12, y:10 }, depth:1 },
        { coordinate:{ x:13, y:10 }, depth:1 },
    ],
    [
        { coordinate:{ x:10, y:0 }, depth:1 },
        { coordinate:{ x:11, y:0 }, depth:1 },
        { coordinate:{ x:12, y:0 }, depth:1 },
        { coordinate:{ x:13, y:0 }, depth:1 },
        { coordinate:{ x:8, y:1 }, depth:1 },
        { coordinate:{ x:9, y:1 }, depth:1 },
        { coordinate:{ x:10, y:1 }, depth:1 },
        { coordinate:{ x:11, y:1 }, depth:1 },
        { coordinate:{ x:12, y:1 }, depth:1 },
        { coordinate:{ x:13, y:1 }, depth:1 },
        { coordinate:{ x:14, y:1 }, depth:1 },
        { coordinate:{ x:15, y:1 }, depth:1 },
        { coordinate:{ x:7, y:2 }, depth:1 },
        { coordinate:{ x:8, y:2 }, depth:1 },
        { coordinate:{ x:9, y:2 }, depth:1 },
        { coordinate:{ x:10, y:2 }, depth:1 },
        { coordinate:{ x:11, y:2 }, depth:1 },
        { coordinate:{ x:12, y:2 }, depth:1 },
        { coordinate:{ x:13, y:2 }, depth:1 },
        { coordinate:{ x:14, y:2 }, depth:1 },
        { coordinate:{ x:15, y:2 }, depth:1 },
        { coordinate:{ x:16, y:2 }, depth:1 },
        { coordinate:{ x:7, y:3 }, depth:1 },
        { coordinate:{ x:8, y:3 }, depth:1 },
        { coordinate:{ x:9, y:3 }, depth:1 },
        { coordinate:{ x:10, y:3 }, depth:1 },
        { coordinate:{ x:11, y:3 }, depth:1 },
        { coordinate:{ x:12, y:3 }, depth:1 },
        { coordinate:{ x:13, y:3 }, depth:1 },
        { coordinate:{ x:14, y:3 }, depth:1 },
        { coordinate:{ x:15, y:3 }, depth:1 },
        { coordinate:{ x:16, y:3 }, depth:1 },
        { coordinate:{ x:6, y:4 }, depth:1 },
        { coordinate:{ x:7, y:4 }, depth:1 },
        { coordinate:{ x:8, y:4 }, depth:1 },
        { coordinate:{ x:9, y:4 }, depth:1 },
        { coordinate:{ x:10, y:4 }, depth:1 },
        { coordinate:{ x:11, y:4 }, depth:1 },
        { coordinate:{ x:12, y:4 }, depth:1 },
        { coordinate:{ x:13, y:4 }, depth:1 },
        { coordinate:{ x:14, y:4 }, depth:1 },
        { coordinate:{ x:15, y:4 }, depth:1 },
        { coordinate:{ x:16, y:4 }, depth:1 },
        { coordinate:{ x:17, y:4 }, depth:1 },
        { coordinate:{ x:6, y:5 }, depth:1 },
        { coordinate:{ x:7, y:5 }, depth:1 },
        { coordinate:{ x:8, y:5 }, depth:1 },
        { coordinate:{ x:9, y:5 }, depth:1 },
        { coordinate:{ x:10, y:5 }, depth:1 },
        { coordinate:{ x:11, y:5 }, depth:1 },
        { coordinate:{ x:12, y:5 }, depth:1 },
        { coordinate:{ x:13, y:5 }, depth:1 },
        { coordinate:{ x:14, y:5 }, depth:1 },
        { coordinate:{ x:15, y:5 }, depth:1 },
        { coordinate:{ x:16, y:5 }, depth:1 },
        { coordinate:{ x:17, y:5 }, depth:1 },
        { coordinate:{ x:6, y:6 }, depth:1 },
        { coordinate:{ x:7, y:6 }, depth:1 },
        { coordinate:{ x:8, y:6 }, depth:1 },
        { coordinate:{ x:9, y:6 }, depth:1 },
        { coordinate:{ x:10, y:6 }, depth:1 },
        { coordinate:{ x:11, y:6 }, depth:1 },
        { coordinate:{ x:12, y:6 }, depth:1 },
        { coordinate:{ x:13, y:6 }, depth:1 },
        { coordinate:{ x:14, y:6 }, depth:1 },
        { coordinate:{ x:15, y:6 }, depth:1 },
        { coordinate:{ x:16, y:6 }, depth:1 },
        { coordinate:{ x:17, y:6 }, depth:1 },
        { coordinate:{ x:6, y:7 }, depth:1 },
        { coordinate:{ x:7, y:7 }, depth:1 },
        { coordinate:{ x:8, y:7 }, depth:1 },
        { coordinate:{ x:9, y:7 }, depth:1 },
        { coordinate:{ x:10, y:7 }, depth:1 },
        { coordinate:{ x:11, y:7 }, depth:1 },
        { coordinate:{ x:12, y:7 }, depth:1 },
        { coordinate:{ x:13, y:7 }, depth:1 },
        { coordinate:{ x:14, y:7 }, depth:1 },
        { coordinate:{ x:15, y:7 }, depth:1 },
        { coordinate:{ x:16, y:7 }, depth:1 },
        { coordinate:{ x:17, y:7 }, depth:1 },
        { coordinate:{ x:7, y:8 }, depth:1 },
        { coordinate:{ x:8, y:8 }, depth:1 },
        { coordinate:{ x:9, y:8 }, depth:1 },
        { coordinate:{ x:10, y:8 }, depth:1 },
        { coordinate:{ x:11, y:8 }, depth:1 },
        { coordinate:{ x:12, y:8 }, depth:1 },
        { coordinate:{ x:13, y:8 }, depth:1 },
        { coordinate:{ x:14, y:8 }, depth:1 },
        { coordinate:{ x:15, y:8 }, depth:1 },
        { coordinate:{ x:16, y:8 }, depth:1 },
        { coordinate:{ x:7, y:9 }, depth:1 },
        { coordinate:{ x:8, y:9 }, depth:1 },
        { coordinate:{ x:9, y:9 }, depth:1 },
        { coordinate:{ x:10, y:9 }, depth:1 },
        { coordinate:{ x:11, y:9 }, depth:1 },
        { coordinate:{ x:12, y:9 }, depth:1 },
        { coordinate:{ x:13, y:9 }, depth:1 },
        { coordinate:{ x:14, y:9 }, depth:1 },
        { coordinate:{ x:15, y:9 }, depth:1 },
        { coordinate:{ x:16, y:9 }, depth:1 },
        { coordinate:{ x:8, y:10 }, depth:1 },
        { coordinate:{ x:9, y:10 }, depth:1 },
        { coordinate:{ x:10, y:10 }, depth:1 },
        { coordinate:{ x:11, y:10 }, depth:1 },
        { coordinate:{ x:12, y:10 }, depth:1 },
        { coordinate:{ x:13, y:10 }, depth:1 },
        { coordinate:{ x:14, y:10 }, depth:1 },
        { coordinate:{ x:15, y:10 }, depth:1 },
        { coordinate:{ x:10, y:11 }, depth:1 },
        { coordinate:{ x:11, y:11 }, depth:1 },
        { coordinate:{ x:12, y:11 }, depth:1 },
        { coordinate:{ x:13, y:11 }, depth:1 },
    ],
    [
        { coordinate:{ x:8, y:0 }, depth:1 },
        { coordinate:{ x:9, y:0 }, depth:1 },
        { coordinate:{ x:10, y:0 }, depth:1 },
        { coordinate:{ x:11, y:0 }, depth:1 },
        { coordinate:{ x:12, y:0 }, depth:1 },
        { coordinate:{ x:13, y:0 }, depth:1 },
        { coordinate:{ x:14, y:0 }, depth:1 },
        { coordinate:{ x:15, y:0 }, depth:1 },
        { coordinate:{ x:7, y:1 }, depth:1 },
        { coordinate:{ x:8, y:1 }, depth:1 },
        { coordinate:{ x:9, y:1 }, depth:1 },
        { coordinate:{ x:10, y:1 }, depth:1 },
        { coordinate:{ x:11, y:1 }, depth:1 },
        { coordinate:{ x:12, y:1 }, depth:1 },
        { coordinate:{ x:13, y:1 }, depth:1 },
        { coordinate:{ x:14, y:1 }, depth:1 },
        { coordinate:{ x:15, y:1 }, depth:1 },
        { coordinate:{ x:16, y:1 }, depth:1 },
        { coordinate:{ x:6, y:2 }, depth:1 },
        { coordinate:{ x:7, y:2 }, depth:1 },
        { coordinate:{ x:8, y:2 }, depth:1 },
        { coordinate:{ x:9, y:2 }, depth:1 },
        { coordinate:{ x:10, y:2 }, depth:1 },
        { coordinate:{ x:11, y:2 }, depth:1 },
        { coordinate:{ x:12, y:2 }, depth:1 },
        { coordinate:{ x:13, y:2 }, depth:1 },
        { coordinate:{ x:14, y:2 }, depth:1 },
        { coordinate:{ x:15, y:2 }, depth:1 },
        { coordinate:{ x:16, y:2 }, depth:1 },
        { coordinate:{ x:17, y:2 }, depth:1 },
        { coordinate:{ x:6, y:3 }, depth:1 },
        { coordinate:{ x:7, y:3 }, depth:1 },
        { coordinate:{ x:8, y:3 }, depth:1 },
        { coordinate:{ x:9, y:3 }, depth:1 },
        { coordinate:{ x:10, y:3 }, depth:1 },
        { coordinate:{ x:11, y:3 }, depth:1 },
        { coordinate:{ x:12, y:3 }, depth:1 },
        { coordinate:{ x:13, y:3 }, depth:1 },
        { coordinate:{ x:14, y:3 }, depth:1 },
        { coordinate:{ x:15, y:3 }, depth:1 },
        { coordinate:{ x:16, y:3 }, depth:1 },
        { coordinate:{ x:17, y:3 }, depth:1 },
        { coordinate:{ x:5, y:4 }, depth:1 },
        { coordinate:{ x:6, y:4 }, depth:1 },
        { coordinate:{ x:7, y:4 }, depth:1 },
        { coordinate:{ x:8, y:4 }, depth:1 },
        { coordinate:{ x:9, y:4 }, depth:1 },
        { coordinate:{ x:10, y:4 }, depth:1 },
        { coordinate:{ x:11, y:4 }, depth:1 },
        { coordinate:{ x:12, y:4 }, depth:1 },
        { coordinate:{ x:13, y:4 }, depth:1 },
        { coordinate:{ x:14, y:4 }, depth:1 },
        { coordinate:{ x:15, y:4 }, depth:1 },
        { coordinate:{ x:16, y:4 }, depth:1 },
        { coordinate:{ x:17, y:4 }, depth:1 },
        { coordinate:{ x:18, y:4 }, depth:1 },
        { coordinate:{ x:5, y:5 }, depth:1 },
        { coordinate:{ x:6, y:5 }, depth:1 },
        { coordinate:{ x:7, y:5 }, depth:1 },
        { coordinate:{ x:8, y:5 }, depth:1 },
        { coordinate:{ x:9, y:5 }, depth:1 },
        { coordinate:{ x:10, y:5 }, depth:1 },
        { coordinate:{ x:11, y:5 }, depth:1 },
        { coordinate:{ x:12, y:5 }, depth:1 },
        { coordinate:{ x:13, y:5 }, depth:1 },
        { coordinate:{ x:14, y:5 }, depth:1 },
        { coordinate:{ x:15, y:5 }, depth:1 },
        { coordinate:{ x:16, y:5 }, depth:1 },
        { coordinate:{ x:17, y:5 }, depth:1 },
        { coordinate:{ x:18, y:5 }, depth:1 },
        { coordinate:{ x:5, y:6 }, depth:1 },
        { coordinate:{ x:6, y:6 }, depth:1 },
        { coordinate:{ x:7, y:6 }, depth:1 },
        { coordinate:{ x:8, y:6 }, depth:1 },
        { coordinate:{ x:9, y:6 }, depth:1 },
        { coordinate:{ x:10, y:6 }, depth:1 },
        { coordinate:{ x:11, y:6 }, depth:1 },
        { coordinate:{ x:12, y:6 }, depth:1 },
        { coordinate:{ x:13, y:6 }, depth:1 },
        { coordinate:{ x:14, y:6 }, depth:1 },
        { coordinate:{ x:15, y:6 }, depth:1 },
        { coordinate:{ x:16, y:6 }, depth:1 },
        { coordinate:{ x:17, y:6 }, depth:1 },
        { coordinate:{ x:18, y:6 }, depth:1 },
        { coordinate:{ x:5, y:7 }, depth:1 },
        { coordinate:{ x:6, y:7 }, depth:1 },
        { coordinate:{ x:7, y:7 }, depth:1 },
        { coordinate:{ x:8, y:7 }, depth:1 },
        { coordinate:{ x:9, y:7 }, depth:1 },
        { coordinate:{ x:10, y:7 }, depth:1 },
        { coordinate:{ x:11, y:7 }, depth:1 },
        { coordinate:{ x:12, y:7 }, depth:1 },
        { coordinate:{ x:13, y:7 }, depth:1 },
        { coordinate:{ x:14, y:7 }, depth:1 },
        { coordinate:{ x:15, y:7 }, depth:1 },
        { coordinate:{ x:16, y:7 }, depth:1 },
        { coordinate:{ x:17, y:7 }, depth:1 },
        { coordinate:{ x:18, y:7 }, depth:1 },
        { coordinate:{ x:6, y:8 }, depth:1 },
        { coordinate:{ x:7, y:8 }, depth:1 },
        { coordinate:{ x:8, y:8 }, depth:1 },
        { coordinate:{ x:9, y:8 }, depth:1 },
        { coordinate:{ x:10, y:8 }, depth:1 },
        { coordinate:{ x:11, y:8 }, depth:1 },
        { coordinate:{ x:12, y:8 }, depth:1 },
        { coordinate:{ x:13, y:8 }, depth:1 },
        { coordinate:{ x:14, y:8 }, depth:1 },
        { coordinate:{ x:15, y:8 }, depth:1 },
        { coordinate:{ x:16, y:8 }, depth:1 },
        { coordinate:{ x:17, y:8 }, depth:1 },
        { coordinate:{ x:6, y:9 }, depth:1 },
        { coordinate:{ x:7, y:9 }, depth:1 },
        { coordinate:{ x:8, y:9 }, depth:1 },
        { coordinate:{ x:9, y:9 }, depth:1 },
        { coordinate:{ x:10, y:9 }, depth:1 },
        { coordinate:{ x:11, y:9 }, depth:1 },
        { coordinate:{ x:12, y:9 }, depth:1 },
        { coordinate:{ x:13, y:9 }, depth:1 },
        { coordinate:{ x:14, y:9 }, depth:1 },
        { coordinate:{ x:15, y:9 }, depth:1 },
        { coordinate:{ x:16, y:9 }, depth:1 },
        { coordinate:{ x:17, y:9 }, depth:1 },
        { coordinate:{ x:7, y:10 }, depth:1 },
        { coordinate:{ x:8, y:10 }, depth:1 },
        { coordinate:{ x:9, y:10 }, depth:1 },
        { coordinate:{ x:10, y:10 }, depth:1 },
        { coordinate:{ x:11, y:10 }, depth:1 },
        { coordinate:{ x:12, y:10 }, depth:1 },
        { coordinate:{ x:13, y:10 }, depth:1 },
        { coordinate:{ x:14, y:10 }, depth:1 },
        { coordinate:{ x:15, y:10 }, depth:1 },
        { coordinate:{ x:16, y:10 }, depth:1 },
        { coordinate:{ x:8, y:11 }, depth:1 },
        { coordinate:{ x:9, y:11 }, depth:1 },
        { coordinate:{ x:10, y:11 }, depth:1 },
        { coordinate:{ x:11, y:11 }, depth:1 },
        { coordinate:{ x:12, y:11 }, depth:1 },
        { coordinate:{ x:13, y:11 }, depth:1 },
        { coordinate:{ x:14, y:11 }, depth:1 },
        { coordinate:{ x:15, y:11 }, depth:1 },
    ],
    [
        { coordinate:{ x:6, y:0 }, depth:1 },
        { coordinate:{ x:7, y:0 }, depth:1 },
        { coordinate:{ x:8, y:0 }, depth:1 },
        { coordinate:{ x:9, y:0 }, depth:1 },
        { coordinate:{ x:10, y:0 }, depth:1 },
        { coordinate:{ x:11, y:0 }, depth:1 },
        { coordinate:{ x:12, y:0 }, depth:1 },
        { coordinate:{ x:13, y:0 }, depth:1 },
        { coordinate:{ x:14, y:0 }, depth:1 },
        { coordinate:{ x:15, y:0 }, depth:1 },
        { coordinate:{ x:16, y:0 }, depth:1 },
        { coordinate:{ x:17, y:0 }, depth:1 },
        { coordinate:{ x:5, y:1 }, depth:1 },
        { coordinate:{ x:6, y:1 }, depth:1 },
        { coordinate:{ x:7, y:1 }, depth:1 },
        { coordinate:{ x:8, y:1 }, depth:1 },
        { coordinate:{ x:9, y:1 }, depth:1 },
        { coordinate:{ x:10, y:1 }, depth:1 },
        { coordinate:{ x:11, y:1 }, depth:1 },
        { coordinate:{ x:12, y:1 }, depth:1 },
        { coordinate:{ x:13, y:1 }, depth:1 },
        { coordinate:{ x:14, y:1 }, depth:1 },
        { coordinate:{ x:15, y:1 }, depth:1 },
        { coordinate:{ x:16, y:1 }, depth:1 },
        { coordinate:{ x:17, y:1 }, depth:1 },
        { coordinate:{ x:18, y:1 }, depth:1 },
        { coordinate:{ x:5, y:2 }, depth:1 },
        { coordinate:{ x:6, y:2 }, depth:1 },
        { coordinate:{ x:7, y:2 }, depth:1 },
        { coordinate:{ x:8, y:2 }, depth:1 },
        { coordinate:{ x:9, y:2 }, depth:1 },
        { coordinate:{ x:10, y:2 }, depth:1 },
        { coordinate:{ x:11, y:2 }, depth:1 },
        { coordinate:{ x:12, y:2 }, depth:1 },
        { coordinate:{ x:13, y:2 }, depth:1 },
        { coordinate:{ x:14, y:2 }, depth:1 },
        { coordinate:{ x:15, y:2 }, depth:1 },
        { coordinate:{ x:16, y:2 }, depth:1 },
        { coordinate:{ x:17, y:2 }, depth:1 },
        { coordinate:{ x:18, y:2 }, depth:1 },
        { coordinate:{ x:4, y:3 }, depth:1 },
        { coordinate:{ x:5, y:3 }, depth:1 },
        { coordinate:{ x:6, y:3 }, depth:1 },
        { coordinate:{ x:7, y:3 }, depth:1 },
        { coordinate:{ x:8, y:3 }, depth:1 },
        { coordinate:{ x:9, y:3 }, depth:1 },
        { coordinate:{ x:10, y:3 }, depth:1 },
        { coordinate:{ x:11, y:3 }, depth:1 },
        { coordinate:{ x:12, y:3 }, depth:1 },
        { coordinate:{ x:13, y:3 }, depth:1 },
        { coordinate:{ x:14, y:3 }, depth:1 },
        { coordinate:{ x:15, y:3 }, depth:1 },
        { coordinate:{ x:16, y:3 }, depth:1 },
        { coordinate:{ x:17, y:3 }, depth:1 },
        { coordinate:{ x:18, y:3 }, depth:1 },
        { coordinate:{ x:19, y:3 }, depth:1 },
        { coordinate:{ x:4, y:4 }, depth:1 },
        { coordinate:{ x:5, y:4 }, depth:1 },
        { coordinate:{ x:6, y:4 }, depth:1 },
        { coordinate:{ x:7, y:4 }, depth:1 },
        { coordinate:{ x:8, y:4 }, depth:1 },
        { coordinate:{ x:9, y:4 }, depth:1 },
        { coordinate:{ x:10, y:4 }, depth:1 },
        { coordinate:{ x:11, y:4 }, depth:1 },
        { coordinate:{ x:12, y:4 }, depth:1 },
        { coordinate:{ x:13, y:4 }, depth:1 },
        { coordinate:{ x:14, y:4 }, depth:1 },
        { coordinate:{ x:15, y:4 }, depth:1 },
        { coordinate:{ x:16, y:4 }, depth:1 },
        { coordinate:{ x:17, y:4 }, depth:1 },
        { coordinate:{ x:18, y:4 }, depth:1 },
        { coordinate:{ x:19, y:4 }, depth:1 },
        { coordinate:{ x:4, y:5 }, depth:1 },
        { coordinate:{ x:5, y:5 }, depth:1 },
        { coordinate:{ x:6, y:5 }, depth:1 },
        { coordinate:{ x:7, y:5 }, depth:1 },
        { coordinate:{ x:8, y:5 }, depth:1 },
        { coordinate:{ x:9, y:5 }, depth:1 },
        { coordinate:{ x:10, y:5 }, depth:1 },
        { coordinate:{ x:11, y:5 }, depth:1 },
        { coordinate:{ x:12, y:5 }, depth:1 },
        { coordinate:{ x:13, y:5 }, depth:1 },
        { coordinate:{ x:14, y:5 }, depth:1 },
        { coordinate:{ x:15, y:5 }, depth:1 },
        { coordinate:{ x:16, y:5 }, depth:1 },
        { coordinate:{ x:17, y:5 }, depth:1 },
        { coordinate:{ x:18, y:5 }, depth:1 },
        { coordinate:{ x:19, y:5 }, depth:1 },
        { coordinate:{ x:4, y:6 }, depth:1 },
        { coordinate:{ x:5, y:6 }, depth:1 },
        { coordinate:{ x:6, y:6 }, depth:1 },
        { coordinate:{ x:7, y:6 }, depth:1 },
        { coordinate:{ x:8, y:6 }, depth:1 },
        { coordinate:{ x:9, y:6 }, depth:1 },
        { coordinate:{ x:10, y:6 }, depth:1 },
        { coordinate:{ x:11, y:6 }, depth:1 },
        { coordinate:{ x:12, y:6 }, depth:1 },
        { coordinate:{ x:13, y:6 }, depth:1 },
        { coordinate:{ x:14, y:6 }, depth:1 },
        { coordinate:{ x:15, y:6 }, depth:1 },
        { coordinate:{ x:16, y:6 }, depth:1 },
        { coordinate:{ x:17, y:6 }, depth:1 },
        { coordinate:{ x:18, y:6 }, depth:1 },
        { coordinate:{ x:19, y:6 }, depth:1 },
        { coordinate:{ x:4, y:7 }, depth:1 },
        { coordinate:{ x:5, y:7 }, depth:1 },
        { coordinate:{ x:6, y:7 }, depth:1 },
        { coordinate:{ x:7, y:7 }, depth:1 },
        { coordinate:{ x:8, y:7 }, depth:1 },
        { coordinate:{ x:9, y:7 }, depth:1 },
        { coordinate:{ x:10, y:7 }, depth:1 },
        { coordinate:{ x:11, y:7 }, depth:1 },
        { coordinate:{ x:12, y:7 }, depth:1 },
        { coordinate:{ x:13, y:7 }, depth:1 },
        { coordinate:{ x:14, y:7 }, depth:1 },
        { coordinate:{ x:15, y:7 }, depth:1 },
        { coordinate:{ x:16, y:7 }, depth:1 },
        { coordinate:{ x:17, y:7 }, depth:1 },
        { coordinate:{ x:18, y:7 }, depth:1 },
        { coordinate:{ x:19, y:7 }, depth:1 },
        { coordinate:{ x:4, y:8 }, depth:1 },
        { coordinate:{ x:5, y:8 }, depth:1 },
        { coordinate:{ x:6, y:8 }, depth:1 },
        { coordinate:{ x:7, y:8 }, depth:1 },
        { coordinate:{ x:8, y:8 }, depth:1 },
        { coordinate:{ x:9, y:8 }, depth:1 },
        { coordinate:{ x:10, y:8 }, depth:1 },
        { coordinate:{ x:11, y:8 }, depth:1 },
        { coordinate:{ x:12, y:8 }, depth:1 },
        { coordinate:{ x:13, y:8 }, depth:1 },
        { coordinate:{ x:14, y:8 }, depth:1 },
        { coordinate:{ x:15, y:8 }, depth:1 },
        { coordinate:{ x:16, y:8 }, depth:1 },
        { coordinate:{ x:17, y:8 }, depth:1 },
        { coordinate:{ x:18, y:8 }, depth:1 },
        { coordinate:{ x:19, y:8 }, depth:1 },
        { coordinate:{ x:5, y:9 }, depth:1 },
        { coordinate:{ x:6, y:9 }, depth:1 },
        { coordinate:{ x:7, y:9 }, depth:1 },
        { coordinate:{ x:8, y:9 }, depth:1 },
        { coordinate:{ x:9, y:9 }, depth:1 },
        { coordinate:{ x:10, y:9 }, depth:1 },
        { coordinate:{ x:11, y:9 }, depth:1 },
        { coordinate:{ x:12, y:9 }, depth:1 },
        { coordinate:{ x:13, y:9 }, depth:1 },
        { coordinate:{ x:14, y:9 }, depth:1 },
        { coordinate:{ x:15, y:9 }, depth:1 },
        { coordinate:{ x:16, y:9 }, depth:1 },
        { coordinate:{ x:17, y:9 }, depth:1 },
        { coordinate:{ x:18, y:9 }, depth:1 },
        { coordinate:{ x:5, y:10 }, depth:1 },
        { coordinate:{ x:6, y:10 }, depth:1 },
        { coordinate:{ x:7, y:10 }, depth:1 },
        { coordinate:{ x:8, y:10 }, depth:1 },
        { coordinate:{ x:9, y:10 }, depth:1 },
        { coordinate:{ x:10, y:10 }, depth:1 },
        { coordinate:{ x:11, y:10 }, depth:1 },
        { coordinate:{ x:12, y:10 }, depth:1 },
        { coordinate:{ x:13, y:10 }, depth:1 },
        { coordinate:{ x:14, y:10 }, depth:1 },
        { coordinate:{ x:15, y:10 }, depth:1 },
        { coordinate:{ x:16, y:10 }, depth:1 },
        { coordinate:{ x:17, y:10 }, depth:1 },
        { coordinate:{ x:18, y:10 }, depth:1 },
        { coordinate:{ x:6, y:11 }, depth:1 },
        { coordinate:{ x:7, y:11 }, depth:1 },
        { coordinate:{ x:8, y:11 }, depth:1 },
        { coordinate:{ x:9, y:11 }, depth:1 },
        { coordinate:{ x:10, y:11 }, depth:1 },
        { coordinate:{ x:11, y:11 }, depth:1 },
        { coordinate:{ x:12, y:11 }, depth:1 },
        { coordinate:{ x:13, y:11 }, depth:1 },
        { coordinate:{ x:14, y:11 }, depth:1 },
        { coordinate:{ x:15, y:11 }, depth:1 },
        { coordinate:{ x:16, y:11 }, depth:1 },
        { coordinate:{ x:17, y:11 }, depth:1 },
    ],
]);
