import AuraType from '../enums/AuraType';
import BerryColor from '../enums/BerryColor';
import BerryFirmness from '../enums/BerryFirmness';
import BerryType from '../enums/BerryType';
import Aura from './Aura';
import Berry from './Berry';

export const BerryList: Berry[] = [

    //#region Berry Data

    //#region First Generation
    new Berry(
        BerryType.Cheri,
        [5, 10, 20, 30, 60],
        2,
        0.5,
        5,
        1,
        [10, 0, 0, 0, 0],
        25,
        BerryColor.Red,
        2,
        BerryFirmness.Soft,
        ['This bright red Berry is very spicy and has a provocative flavor. It blooms with delicate, pretty flowers.'],
    ),

    new Berry(
        BerryType.Chesto,
        [5, 15, 25, 40, 80],
        3,
        0.5,
        6,
        2,
        [0, 10, 0, 0, 0],
        25,
        BerryColor.Purple,
        8,
        BerryFirmness.Super_Hard,
        ['This Berry\'s thick skin and fruit are very tough and dry-tasting. However, every bit of it can be eaten.'],
    ),

    new Berry(
        BerryType.Pecha,
        [10, 35, 50, 60, 120],
        4,
        0.5,
        7,
        3,
        [0, 0, 10, 0, 0],
        25,
        BerryColor.Pink,
        4,
        BerryFirmness.Very_Soft,
        ['Because of its hollow inside pocket, there isn\'t a lot to eat. What can be eaten is very sweet and delicious.'],
    ),

    new Berry(
        BerryType.Rawst,
        [15, 30, 45, 80, 160],
        5,
        0.5,
        8,
        4,
        [0, 0, 0, 10, 0],
        25,
        BerryColor.Green,
        3.2,
        BerryFirmness.Hard,
        ['If the leaves grow longer and curlier than average, this Berry will have a somewhat-bitter taste.'],
    ),

    new Berry(
        BerryType.Aspear,
        [10, 40, 60, 120, 240],
        6,
        0.5,
        9,
        5,
        [0, 0, 0, 0, 10],
        25,
        BerryColor.Yellow,
        5,
        BerryFirmness.Super_Hard,
        ['This Berry\'s peel is hard, but the flesh inside is very juicy. It is distinguished by its bracing sourness.'],
    ),

    new Berry(
        BerryType.Leppa,
        [100, 120, 140, 240, 480],
        7,
        0.5,
        10,
        6,
        [10, 0, 10, 10, 10],
        20,
        BerryColor.Red,
        2.8,
        BerryFirmness.Very_Hard,
        ['It takes longer to grow than Berries such as Cheri. The smaller Berries taste better.'],
    ),

    new Berry(
        BerryType.Oran,
        [120, 180, 240, 300, 600],
        8,
        0.5,
        20,
        7,
        [10, 10, 0, 10, 10],
        20,
        BerryColor.Blue,
        3.5,
        BerryFirmness.Super_Hard,
        ['Nature\'s gifts came together as one in this Berry. It has a wondrous mix of flavors that spread in the mouth.'],
    ),

    new Berry(
        BerryType.Sitrus,
        [150, 300, 450, 600, 1200],
        9,
        0.5,
        30,
        8,
        [0, 10, 10, 10, 10],
        20,
        BerryColor.Yellow,
        9.5,
        BerryFirmness.Very_Hard,
        ['Sitrus came from the same family as Oran. It is larger and smoother-tasting than Oran.'],
    ),
    //#endregion

    //#region Second Generation
    new Berry(
        BerryType.Persim,
        [20, 40, 50, 90, 180],
        5,
        0.4,
        10,
        2,
        [10, 10, 10, 0, 10],
        20,
        BerryColor.Pink,
        4.7,
        BerryFirmness.Hard,
        ['The more this Berry absorbs energy from sunlight, the more vividly colorful it grows.'],
    ),

    new Berry(
        BerryType.Razz,
        [100, 150, 200, 250, 500],
        7,
        0.4,
        15,
        2,
        [10, 10, 0, 0, 0],
        20,
        BerryColor.Red,
        12,
        BerryFirmness.Very_Hard,
        ['A small hint of spiciness lingers in the red granules surrounding this Berry. Their centers have a dry taste.'],
    ),

    new Berry(
        BerryType.Bluk,
        [200, 250, 300, 330, 660],
        9,
        0.4,
        20,
        2,
        [0, 10, 10, 0, 0],
        20,
        BerryColor.Purple,
        10.8,
        BerryFirmness.Soft,
        ['Though this small, delicately-skinned Berry is blue in color, it dyes the mouth black when eaten.'],
    ),

    new Berry(
        BerryType.Nanab,
        [25, 30, 35, 250, 500],
        11,
        0.4,
        25,
        2,
        [0, 0, 10, 10, 0],
        20,
        BerryColor.Pink,
        7.7,
        BerryFirmness.Very_Hard,
        ['Bitter, but with a trace of sweetness, the Nanab Berry was the seventh to be discovered in the world.'],
    ),

    new Berry(
        BerryType.Wepear,
        [150, 350, 375, 400, 800],
        12,
        0.4,
        30,
        2,
        [0, 0, 0, 10, 10],
        20,
        BerryColor.Green,
        7.4,
        BerryFirmness.Super_Hard,
        ['The potent mix of bitter and sour in this Berry seems to promote digestion. The flower is white and beautiful.'],
    ),

    new Berry(
        BerryType.Pinap,
        [30, 60, 180, 240, 480],
        13,
        0.4,
        35,
        2,
        [10, 0, 0, 0, 10],
        20,
        BerryColor.Yellow,
        8,
        BerryFirmness.Hard,
        ['It is said that when the sour skin is peeled, this spicy Berry can be crushed to make medicine.'],
    ),

    new Berry(
        BerryType.Figy,
        [40, 160, 230, 350, 700],
        14,
        0.3,
        40,
        3,
        [15, 0, 0, 0, 0],
        25,
        BerryColor.Red,
        10,
        BerryFirmness.Soft,
        ['This Berry is oddly shaped, appearing as if someone took a bite out of it. It is packed full of spicy substances.'],
    ),

    new Berry(
        BerryType.Wiki,
        [40, 190, 210, 360, 720],
        15,
        0.3,
        45,
        3,
        [0, 15, 0, 0, 0],
        25,
        BerryColor.Purple,
        11.5,
        BerryFirmness.Hard,
        ['It is said that this Berry grew lumps to help Pokémon grip it, allowing propagation farther afield.'],
    ),

    new Berry(
        BerryType.Mago,
        [40, 180, 240, 370, 740],
        16,
        0.3,
        50,
        3,
        [0, 0, 15, 0, 0],
        25,
        BerryColor.Pink,
        12.6,
        BerryFirmness.Hard,
        ['This Berry progressively curves as it grows. The curvier the Berry, the sweeter and tastier.'],
    ),

    new Berry(
        BerryType.Aguav,
        [40, 170, 220, 350, 700],
        17,
        0.3,
        55,
        3,
        [0, 0, 0, 15, 0],
        25,
        BerryColor.Green,
        6.4,
        BerryFirmness.Super_Hard,
        ['This Berry turns bitter toward the stem. The dainty flower it grows from doesn\'t absorb much sunlight.'],
    ),

    new Berry(
        BerryType.Iapapa,
        [40, 200, 230, 380, 760],
        18,
        0.3,
        60,
        3,
        [0, 0, 0, 0, 15],
        25,
        BerryColor.Yellow,
        22.3,
        BerryFirmness.Soft,
        ['This Berry is very big and sour. The juiciness of the pulp accentuates the sourness.'],
    ),

    new Berry(
        BerryType.Lum,
        [3000, 3200, 3400, 3600, 43200],
        1,
        0,
        540,
        3,
        [10, 10, 10, 10, 0],
        25,
        BerryColor.Green,
        3.4,
        BerryFirmness.Super_Hard,
        [
            'This Berry\'s gradual process of storing nutrients beneficial to Pokémon health causes it to mature slowly.',
            'This Berry multiplies the effect of Berry plants around it.',
        ],
        new Aura(AuraType.Boost, [1.01, 1.02, 1.03]),
    ),
    //#endregion

    //#region Third Generation
    new Berry(
        BerryType.Pomeg,
        [200, 1200, 4000, 5400, 10800],
        20,
        0.2,
        500,
        10,
        [10, 0, 10, 10, 0],
        20,
        BerryColor.Red,
        13.5,
        BerryFirmness.Very_Hard,
        ['When this sweetly spicy Berry\'s thick skin is peeled, many pieces of the fruit spill out.'],
    ),

    new Berry(
        BerryType.Kelpsy,
        [240, 2000, 3400, 6000, 12000],
        21,
        0.2,
        525,
        10,
        [0, 10, 0, 10, 10],
        20,
        BerryColor.Blue,
        15,
        BerryFirmness.Hard,
        ['This Berry can be eaten as is or boiled to obtain an extract that adds a dash of flavor to food.'],
    ),

    new Berry(
        BerryType.Qualot,
        [230, 1000, 2500, 4800, 9600],
        22,
        0.2,
        550,
        10,
        [10, 0, 10, 0, 10],
        20,
        BerryColor.Pink,
        11,
        BerryFirmness.Hard,
        ['Even in places of constant rain and high humidity, this Berry\'s plant grows healthy and strong.'],
    ),

    new Berry(
        BerryType.Hondew,
        [1000, 2000, 5000, 10800, 21600],
        23,
        0.2,
        2000,
        10,
        [10, 10, 0, 10, 0],
        20,
        BerryColor.Green,
        16.2,
        BerryFirmness.Hard,
        ['This somewhat-rare Berry projects an image of luxury, so it is favored as a gift item.'],
    ),

    new Berry(
        BerryType.Grepa,
        [300, 3400, 5600, 7200, 14400],
        24,
        0.2,
        600,
        10,
        [0, 10, 10, 0, 10],
        20,
        BerryColor.Yellow,
        14.9,
        BerryFirmness.Soft,
        ['One bite of this very tender Berry fills the mouth with its sweet and tangy flavor.'],
    ),

    new Berry(
        BerryType.Tamato,
        [430, 1400, 4000, 8640, 17280],
        25,
        0.2,
        625,
        10,
        [20, 10, 0, 0, 0],
        30,
        BerryColor.Red,
        20,
        BerryFirmness.Soft,
        ['This Berry is large and spicy. When eaten during the cold season, it warms the body from inside.'],
    ),

    new Berry(
        BerryType.Cornn,
        [1100, 4000, 8000, 9000, 18000],
        26,
        0.1,
        700,
        10,
        [0, 20, 10, 0, 0],
        30,
        BerryColor.Purple,
        7.5,
        BerryFirmness.Hard,
        ['Its dryness is quite strong. As a result, its true deliciousness can\'t be appreciated by just eating one or two.'],
    ),

    new Berry(
        BerryType.Magost,
        [2400, 6500, 10000, 14400, 28800],
        27,
        0.1,
        750,
        10,
        [0, 0, 20, 10, 0],
        30,
        BerryColor.Pink,
        14,
        BerryFirmness.Hard,
        ['The grown-up flavor and dreamy sweetness of this Berry make it a favorite of Pokémon everywhere.'],
    ),

    new Berry(
        BerryType.Rabuta,
        [2310, 5400, 9500, 12240, 24480],
        28,
        0.1,
        800,
        10,
        [0, 0, 0, 20, 10],
        30,
        BerryColor.Green,
        22.6,
        BerryFirmness.Soft,
        ['Even though it is bitter, it should be eaten peel and all. The hair on the peel cleans the stomach from the inside.'],
    ),

    new Berry(
        BerryType.Nomel,
        [1240, 5200, 10500, 15120, 30240],
        29,
        0.1,
        850,
        10,
        [10, 0, 0, 0, 20],
        30,
        BerryColor.Yellow,
        28.5,
        BerryFirmness.Super_Hard,
        ['This Berry is quite sour overall, with the sourness especially concentrated at the pointed end.'],
    ),

    new Berry(
        BerryType.Spelon,
        [2000, 7000, 12000, 15480, 30960],
        30,
        0.1,
        900,
        10,
        [30, 10, 0, 0, 0],
        35,
        BerryColor.Red,
        13.3,
        BerryFirmness.Soft,
        ['So spicy is the Spelon Berry that, Fire type or not, Pokémon will try to breathe fire after eating a single one.'],
    ),

    new Berry(
        BerryType.Pamtre,
        [3000, 10000, 16400, 18000, 36000],
        31,
        0.1,
        950,
        10,
        [0, 30, 10, 0, 0],
        35,
        BerryColor.Purple,
        24.4,
        BerryFirmness.Very_Soft,
        [
            'This Berry drifted from a faraway sea. It is now cultivated in the Sinnoh region.',
            'It has a tendency to expand into nearby plots.',
        ],
    ),

    new Berry(
        BerryType.Watmel,
        [2300, 3400, 9800, 16560, 33120],
        32,
        0.1,
        1000,
        10,
        [0, 0, 30, 10, 0],
        35,
        BerryColor.Pink,
        25,
        BerryFirmness.Soft,
        ['A bounty of nature that is exceedingly sweet. The Berry is huge, with some discovered that exceed 20\u2033, or 50 cm.'],
    ),

    new Berry(
        BerryType.Durin,
        [10000, 14000, 18000, 21600, 43200],
        33,
        0.1,
        1050,
        10,
        [0, 0, 0, 30, 10],
        35,
        BerryColor.Green,
        28,
        BerryFirmness.Hard,
        ['This Berry is tremendously bitter. Just one bite is enough to instantly stop hiccups.'],
    ),

    new Berry(
        BerryType.Belue,
        [5000, 9800, 14500, 19800, 39600],
        20,
        0.1,
        1100,
        10,
        [10, 0, 0, 0, 30],
        35,
        BerryColor.Purple,
        30,
        BerryFirmness.Very_Soft,
        ['This glossy and colorful Berry has a mouthwateringly delicious appearance. However, it is awfully sour.'],
    ),

    new Berry(
        BerryType.Pinkan,
        [1800, 3600, 7200, 14400, 28800],
        3,
        0.1,
        2500,
        15,
        [0, 0, 35, 0, 0],
        30,
        BerryColor.Pink,
        3.5,
        BerryFirmness.Hard,
        [
            'This Berry endemic to Pinkan Island has an incredibly sweet taste.',
            'It has a vibrant pink pigment, and it is found in such abundance on Pinkan Island that all Pokémon found there are colored Pink!',
        ],
        undefined,
        ['Pinkan Scyther'],
    ),
    //#endregion

    //#region Fourth Generation (Typed)
    new Berry(
        BerryType.Occa,
        [8090, 13200, 16000, 21960, 43920],
        21,
        0.05,
        1200,
        15,
        [15, 0, 10, 0, 0],
        30,
        BerryColor.Red,
        8.9,
        BerryFirmness.Super_Hard,
        [
            'This Berry is said to have grown plentiful in the tropics of the past. It boasts an intensely hot spiciness.',
            'It has a tendency to overtake nearby plants.',
        ],
        undefined,
        ['Charmander', 'Cyndaquil', 'Torchic', 'Chimchar', 'Tepig', 'Fennekin', 'Litten', 'Scorbunny', 'Fuecoco'],
    ),

    new Berry(
        BerryType.Passho,
        [490, 3600, 10800, 21600, 43200],
        22,
        0.05,
        1300,
        15,
        [0, 15, 0, 10, 0],
        30,
        BerryColor.Blue,
        3.3,
        BerryFirmness.Soft,
        [
            'This Berry\'s flesh is dotted with countless tiny bubbles of air that keep it afloat in water.',
            'This Berry promotes the fruiting of nearby Berry plants.',
        ],
        new Aura(AuraType.Harvest, [1.1, 1.2, 1.3]),
        ['Squirtle', 'Totodile', 'Mudkip', 'Piplup', 'Oshawott', 'Froakie', 'Popplio', 'Sobble', 'Quaxly'],
    ),

    new Berry(
        BerryType.Wacan,
        [10, 180, 900, 1800, 3600],
        2,
        0.05,
        250,
        1,
        [0, 0, 15, 0, 10],
        30,
        BerryColor.Yellow,
        25,
        BerryFirmness.Very_Soft,
        [
            'Energy from lightning strikes is drawn into the plant, making the Berries grow big and rich.',
            'The same energy promotes the growth of nearby Berries.',
        ],
        new Aura(AuraType.Growth, [1.1, 1.2, 1.3]),
        ['Pikachu', 'Plusle', 'Minun', 'Pachirisu', 'Emolga', 'Dedenne', 'Togedemaru', 'Morpeko (Hangry)', 'Pawmi'],
    ),

    new Berry(
        BerryType.Rindo,
        [3600, 7200, 16200, 28800, 57600],
        24,
        0.05,
        1400,
        15,
        [10, 0, 0, 15, 0],
        30,
        BerryColor.Green,
        15.5,
        BerryFirmness.Soft,
        [
            'This Berry has a disagreeable "green" flavor and scent typical of vegetables. It is rich in health-promoting fiber.',
            'It has a tendency to expand into nearby plots, but attracts Pokémon that are holding items.',
        ],
        new Aura(AuraType.Pickup, [1.005, 1.01, 1.015]),
        ['Bulbasaur', 'Chikorita', 'Treecko', 'Turtwig', 'Snivy', 'Chespin', 'Rowlet', 'Grookey', 'Sprigatito'],
    ),

    new Berry(
        BerryType.Yache,
        [3600, 14400, 28800, 43200, 86400],
        25,
        0.05,
        1500,
        15,
        [0, 10, 0, 0, 15],
        30,
        BerryColor.Blue,
        13.5,
        BerryFirmness.Very_Hard,
        [
            'This Berry has a refreshing flavor that strikes a good balance of dryness and sourness. It tastes better chilled.',
            'This Berry slows the decay of nearby Berries.',
        ],
        new Aura(AuraType.Decay, [0.9, 0.8, 0.7]),
        ['Jynx', 'Swinub', 'Spheal', 'Snover', 'Snom'],
    ),

    new Berry(
        BerryType.Chople,
        [5400, 10800, 25200, 36000, 72000],
        26,
        0.05,
        1600,
        15,
        [15, 0, 0, 10, 0],
        30,
        BerryColor.Red,
        7.7,
        BerryFirmness.Soft,
        [
            'This Berry contains a substance that generates heat. It can even heat up a chilly heart.',
            'Growing these Berries will promote Egg growth.',
        ],
        new Aura(AuraType.Egg, [1.01, 1.02, 1.03]),
        ['Mankey', 'Makuhita', 'Riolu', 'Scraggy', 'Crabrawler'],
    ),

    new Berry(
        BerryType.Kebia,
        [100, 200, 400, 600, 86400],
        1,
        1,
        50,
        1,
        [0, 15, 0, 0, 10],
        30,
        BerryColor.Green,
        8.9,
        BerryFirmness.Hard,
        [
            'This Berry is a brilliant green on the outside. Inside, it is packed with a dry-flavored, black-colored flesh.',
            'It has a tendency to overtake nearby plants.',
            'Due to its poisonous nature, it increases the chances of mutations near it.',
        ],
        new Aura(AuraType.Mutation, [1.2, 1.4, 1.6]),
        ['Grimer', 'Spinarak', 'Gulpin', 'Skorupi', 'Salandit', 'Toxel'],
    ),

    new Berry(
        BerryType.Shuca,
        [7200, 16200, 32400, 39600, 79200],
        28,
        1,
        1700,
        15,
        [10, 0, 15, 0, 0],
        30,
        BerryColor.Yellow,
        4.2,
        BerryFirmness.Soft,
        [
            'The sweetness-laden pulp has just the hint of a hard-edged and fragrant bite to it.',
            'Growing these Berries will soften the ground around it, increasing the chances of replanting.',
        ],
        new Aura(AuraType.Replant, [1.01, 1.02, 1.03]),
        ['Sandshrew', 'Larvitar', 'Numel', 'Hippopotas'],
    ),

    new Berry(
        BerryType.Coba,
        [9000, 12600, 16200, 19800, 39600],
        29,
        0.05,
        1800,
        15,
        [0, 10, 0, 15, 0],
        30,
        BerryColor.Blue,
        27.7,
        BerryFirmness.Very_Hard,
        ['This Berry is said to be a new kind that is a cross of two Berries brought together by winds from far away.'],
        undefined,
        ['Farfetch\'d', 'Murkrow', 'Tropius', 'Chatot'],
    ),

    new Berry(
        BerryType.Payapa,
        [4680, 11880, 23400, 34200, 68400],
        30,
        0.05,
        1900,
        15,
        [0, 0, 10, 0, 15],
        30,
        BerryColor.Purple,
        25.1,
        BerryFirmness.Soft,
        [
            'This Berry is said to sense human emotions for the way it swells roundly when a person approaches.',
            'The same behavior affects nearby plants, causing additional mutations.',
        ],
        new Aura(AuraType.Mutation, [1.1, 1.2, 1.3]),
        ['Mr. Mime', 'Natu', 'Ralts', 'Chingling'],
    ),

    new Berry(
        BerryType.Tanga,
        [450, 900, 1800, 3600, 7200],
        3,
        0.5,
        500,
        15,
        [20, 0, 0, 0, 10],
        35,
        BerryColor.Green,
        4.3,
        BerryFirmness.Very_Soft,
        [
            'The flower grows at the tip of this Berry. It attracts Bug Pokémon by letting its stringy petals stream out.',
            'The attracted Bug Pokémon decrease the amount of harvestable Berries in nearby plants.',
        ],
        new Aura(AuraType.Harvest, [0.9, 0.8, 0.7]),
        ['Pinsir', 'Shuckle', 'Shuckle (Corked)', 'Nincada', 'Mothim', 'Sizzlipede'],
    ),

    new Berry(
        BerryType.Charti,
        [8600, 12960, 23040, 37800, 75600],
        32,
        0.05,
        2000,
        15,
        [10, 20, 0, 0, 0],
        35,
        BerryColor.Yellow,
        2.8,
        BerryFirmness.Very_Soft,
        [
            'It is often used for pickles because of its very dry flavor. It can also be eaten raw for its provocative taste.',
            'This Berry plant hardens the surrounding soil, decreasing the chances of replanting.',
        ],
        new Aura(AuraType.Replant, [0.99, 0.98, 0.97]),
        ['Rhyhorn', 'Sudowoodo', 'Aron', 'Bonsly', 'Rockruff'],
    ),

    new Berry(
        BerryType.Kasib,
        [30, 60, 120, 300, 86400],
        1,
        1,
        25,
        1,
        [0, 10, 20, 0, 0],
        35,
        BerryColor.Purple,
        14.4,
        BerryFirmness.Hard,
        [
            'Considered to have a special power from the olden days, this Berry is sometimes dried and used as a good-luck charm.',
            'This Berry causes other nearby Berries to wither away faster.',
        ],
        new Aura(AuraType.Death, [1.25, 1.5, 2.0]),
        ['Gastly', 'Misdreavus', 'Shedinja', 'Drifloon'],
    ),

    new Berry(
        BerryType.Haban,
        [10800, 21600, 43200, 86400, 172800],
        34,
        0,
        4000,
        15,
        [0, 0, 10, 20, 0],
        35,
        BerryColor.Red,
        2.3,
        BerryFirmness.Soft,
        [
            'If a large enough volume of this Berry is boiled down, its bitterness fades away. It makes a good jam.',
            'This Berry requires a lot of energy to grow, but isn\'t fussy about what it consumes, it helps other plants by removing toxins from the soil.',
        ],
        new Aura(AuraType.Decay, [0.8, 0.6, 0.5]),
        ['Dratini', 'Bagon', 'Gible', 'Druddigon', 'Drampa', 'Applin', 'Exposed Applin'],
    ),

    new Berry(
        BerryType.Colbur,
        [2880, 10080, 19440, 27000, 54000],
        35,
        0.05,
        2300,
        15,
        [0, 0, 0, 10, 20],
        35,
        BerryColor.Purple,
        3.8,
        BerryFirmness.Super_Hard,
        [
            'Tiny hooks grow on the surface of this Berry. It latches on to Pokémon so it can be carried to far-off places.',
            'It has a tendency to overtake nearby plants.',
            'It also prevents Kasib from mutating.',
        ],
        undefined,
        ['Houndour', 'Absol', 'Stunky', 'Zorua', 'Impidimp'],
    ),

    new Berry(
        BerryType.Babiri,
        [7200, 16200, 32400, 64800, 129600],
        36,
        0.05,
        2400,
        15,
        [25, 10, 0, 0, 0],
        35,
        BerryColor.Green,
        26.5,
        BerryFirmness.Super_Hard,
        [
            'This Berry is very tough with a strong flavor. It was used to make medicine by people in the past.',
            'This Berry plant is very hardy and resistant, making it resistant to mutations, and also decreasing the chance of mutations around it.',
        ],
        new Aura(AuraType.Mutation, [0.5, 0.25, 0.0]),
        ['Magnemite', 'Skarmory', 'Beldum', 'Bronzor', 'Cufant'],
    ),

    new Berry(
        BerryType.Chilan,
        [240, 1430, 2970, 7200, 14400],
        10,
        0.05,
        500,
        15,
        [0, 25, 10, 0, 0],
        35,
        BerryColor.Yellow,
        3.3,
        BerryFirmness.Very_Soft,
        ['This Berry can be cored out and dried to make a whistle. Blowing through its hole makes an indescribable sound.'],
        new Aura(AuraType.Egg, [0.99, 0.98, 0.97]),
        ['Snorlax', 'Girafarig', 'Swablu', 'Munchlax', 'Audino', 'Skwovet'],
    ),

    new Berry(
        BerryType.Roseli,
        [2410, 5040, 12600, 25200, 50400],
        38,
        0.05,
        2500,
        15,
        [0, 0, 25, 10, 0],
        35,
        BerryColor.Pink,
        3.3,
        BerryFirmness.Hard,
        [
            'This Berry is sweet with a hint of bitterness and has a lingering sweet scent. It is often dried and used to make tea.',
            'The scent of this Berry plant attracts wild Pokémon.',
        ],
        new Aura(AuraType.Attract, [1.02, 1.04, 1.07]),
        ['Clefairy', 'Togepi', 'Ralts'],
    ),

    new Berry(
        BerryType.Snover,
        [3600, 7200, 10800, 14400, 28800],
        5,
        0.01,
        1250,
        15,
        [0, 0, 20, 0, 10],
        35,
        BerryColor.Green,
        5,
        BerryFirmness.Soft,
        ['This berry grows around the waist of certain Snover.'],
        undefined,
        ['Snover (Berry)'],
    ),
    //#endregion

    //#region Fifth Generation
    new Berry(
        BerryType.Micle,
        [3960, 7920, 15840, 31680, 63360],
        1,
        0.05,
        2600,
        20,
        [0, 40, 10, 0, 0],
        60,
        BerryColor.Green,
        4.1,
        BerryFirmness.Soft,
        [
            'This Berry has a very dry flavor. It has the effect of making other food eaten at the same time taste sweet.',
            'The scent of this Berry plant repels wild Pokémon.',
        ],
        new Aura(AuraType.Attract, [0.99, 0.97, 0.95]),
        ['Hoopa'],
    ),

    new Berry(
        BerryType.Custap,
        [3240, 8280, 13320, 27360, 54720],
        1,
        0.05,
        2700,
        20,
        [0, 0, 40, 10, 0],
        60,
        BerryColor.Red,
        26.7,
        BerryFirmness.Super_Hard,
        [
            'The flesh underneath the Custap Berry\'s tough skin is sweet and creamy soft.',
            'This inspires Pokémon to train harder.',
        ],
        new Aura(AuraType.Xp, [1.005, 1.01, 1.015]),
        ['Burmy (No Coat)'],
    ),

    new Berry(
        BerryType.Jaboca,
        [1875, 3750, 7500, 15000, 30000],
        1,
        0.05,
        2800,
        20,
        [0, 0, 0, 40, 10],
        60,
        BerryColor.Yellow,
        3.3,
        BerryFirmness.Soft,
        [
            'The cluster of drupelets that make up this Berry pop rhythmically if the Berry is handled roughly.',
            'The sound of these Berries attracts rare wild Pokémon.',
        ],
        new Aura(AuraType.Roaming, [1.01, 1.02, 1.03]),
    ),

    new Berry(
        BerryType.Rowap,
        [5760, 9000, 14040, 21240, 42480],
        1,
        0.05,
        2900,
        20,
        [10, 0, 0, 0, 40],
        60,
        BerryColor.Blue,
        5.2,
        BerryFirmness.Very_Soft,
        [
            'In days of old, people worked the top-shaped pieces of this Berry free and used them as toys.',
            'These berries make catching efforts worth more.',
        ],
        new Aura(AuraType.Ev, [1.005, 1.01, 1.015]),
    ),

    new Berry(
        BerryType.Kee,
        [4680, 9360, 18360, 36360, 72720],
        1,
        0.05,
        3000,
        20,
        [30, 30, 10, 10, 10],
        60,
        BerryColor.Yellow,
        5.7,
        BerryFirmness.Very_Hard,
        ['This Berry remains poisonous until fully ripened. Once ripe it has a spicy and sweet complex flavor.'],
    ),

    new Berry(
        BerryType.Maranga,
        [5040, 10080, 20160, 40320, 80640],
        1,
        0.05,
        8000,
        20,
        [10, 10, 30, 30, 10],
        60,
        BerryColor.Blue,
        19.4,
        BerryFirmness.Very_Hard,
        ['This Berry resembles the Durin Berry, though its spikes are less pronounced. It is quite delicious when roasted.'],
    ),

    new Berry(
        BerryType.Liechi,
        [21600, 43200, 86400, 172800, 345600],
        0.5,
        0,
        10000,
        20,
        [30, 10, 30, 0, 0],
        40,
        BerryColor.Red,
        11.1,
        BerryFirmness.Very_Hard,
        ['This Berry is surrounded by mystery. It is rumored to be imbued with the power of the sea.'],
        undefined,
        ['Manaphy'],
    ),

    new Berry(
        BerryType.Ganlon,
        [21600, 43200, 86400, 172800, 345600],
        0.5,
        0,
        10000,
        20,
        [0, 30, 10, 30, 0],
        40,
        BerryColor.Purple,
        3.3,
        BerryFirmness.Very_Hard,
        ['This Berry is surrounded by mystery. It is rumored to be imbued with the power of the land.'],
    ),

    new Berry(
        BerryType.Salac,
        [21600, 43200, 86400, 172800, 345600],
        0.5,
        0,
        10000,
        20,
        [0, 0, 30, 10, 30],
        40,
        BerryColor.Green,
        9.5,
        BerryFirmness.Very_Hard,
        ['This Berry is surrounded by mystery. It is rumored to be imbued with the power of the sky.'],
    ),

    new Berry(
        BerryType.Petaya,
        [10800, 21600, 43200, 86400, 432000],
        0.5,
        0,
        15000,
        20,
        [30, 0, 0, 30, 10],
        40,
        BerryColor.Pink,
        23.7,
        BerryFirmness.Very_Hard,
        [
            'This Berry is surrounded by mystery. It is rumored to be imbued with the power of all living things.',
            'This power revitalizes and prevents other berries from withering.',
        ],
        undefined,
        ['Mew'],
    ),

    new Berry(
        BerryType.Apicot,
        [10800, 21600, 43200, 86400, 432000],
        0.5,
        0,
        15000,
        20,
        [10, 30, 0, 0, 30],
        40,
        BerryColor.Blue,
        7.5,
        BerryFirmness.Hard,
        ['This is a very, very mystifying Berry. There is no telling how it can be used, or what may happen if it is used.'],
    ),

    new Berry(
        BerryType.Lansat,
        [10800, 21600, 43200, 86400, 432000],
        0.5,
        0,
        15000,
        20,
        [30, 10, 30, 10, 30],
        50,
        BerryColor.Red,
        9.7,
        BerryFirmness.Soft,
        ['This is said to be a legendary Berry. Holding it supposedly brings great joy.'],
    ),

    new Berry(
        BerryType.Starf,
        [10800, 21600, 43200, 86400, 432000],
        0.5,
        0,
        15000,
        20,
        [30, 10, 30, 10, 30],
        50,
        BerryColor.Green,
        15.3,
        BerryFirmness.Super_Hard,
        ['This Berry is considered a mirage. It was said to be so strong that it had to be abandoned at the world\'s edge.'],
        new Aura(AuraType.Shiny, [1.005, 1.01, 1.015]),
        ['Jirachi'],
    ),

    new Berry(
        BerryType.Enigma,
        [10800, 21600, 43200, 86400, 604800],
        0.5,
        0,
        15000,
        20,
        [40, 10, 0, 0, 0],
        60,
        BerryColor.Purple,
        15.5,
        BerryFirmness.Hard,
        ['A completely enigmatic Berry. It apparently has the power of the stars that fill the night sky.'],
        undefined,
        ['Detective Pikachu'],
    ),

    new Berry(
        BerryType.Hopo,
        [10800, 21600, 43200, 86400, 604800],
        1,
        0,
        15000,
        25,
        [15, 40, 35, 30, 25],
        50,
        BerryColor.Gold,
        5.8,
        BerryFirmness.Very_Soft,
        ['A truly mythical Berry native to harsh northern lands. It was first created by a Pokémon believed to have shaped the world.'],
    ),
    //#endregion

    //#endregion
];
